### ISSUE TITLE
申请成为 reviewer

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#106]
鉴于现在的任务分配情况差不多了，剩下的内容我也并不擅长。粗略看过本书译文之后，发现语句的通顺度尚不如意，因此自荐申请成为审校者，为已经翻译过的内容修改润色。

不过作为统领全书行文风格和术语标准的审校者，至少要具备一定的翻译经验。本人是 [Go-zh](https://github.com/Go-zh) 项目的翻译和负责人，代表译文有 [实效 Go 编程](https://go-zh.org/doc/effective_go.html) 、 [Go 编程语言规范](https://go-zh.org/ref/spec.old) （旧译版，新版仍未完成）和 [包文档](https://go-zh.org/pkg/) 等官方文档，以及 [命名的学问](https://blog.go-zh.org/package-names) 、[反射法则](https://blog.go-zh.org/laws-of-reflection) 与 [Go 切片：用法和本质](https://blog.go-zh.org/go-slices-usage-and-internals) 等官方博文，偶尔也去 MDN 和 Wiki 上译些文档。

因此，本人希望贡献自己的力量，让 Pro Git 第二版更加严谨细致，简明易读，也能让这本自己很喜欢的书以最好的状态面世。

**Comment by archermind** [comment]
=无比支持

**Comment by networm** [comment]
@OlingCat 还有接近10篇未翻译啊，要不要先帮忙翻译完啊？

**Comment by networm** [comment]
@OlingCat 现在你就是审校者了，之间在对应的 PR 上的修改提意见就可以。

**Comment by OlingCat** [comment]
@networm 整理了一下，目前还剩
 gitweb
 hosted
 05-distributed-git
 1-distributed-git
 contributing
 maintaining
 3-maintaining
 rerere
 1-git-other-environments
 powershell
我先看看哪些比较熟悉再决定吧

**Comment by sanddudu** [comment]
\ 欧林喵 /

**Comment by networm** [comment]
@OlingCat rerere 我刚翻译完初版，你可以先去掉这个。

**Comment by OlingCat** [comment]
@networm OK

**Comment by networm** [comment]
@OlingCat contributing maintaining 这两个较长，需要有经验的人来翻译，要不先翻译这两个？

**Comment by sanddudu** [comment]
@networm contributing 我已经在翻译
#111

**Comment by networm** [comment]
@sanddudu  "book\05-distributed-git\sections\contributing.asc" 我是说这个。
