### ISSUE TITLE
问一个白痴的问题，PR如果需要修改的话，大家是怎么弄的？重新建一个，还是在原来的基础上接着改？

### ISSUE THREAD

**Issue by archermind** [progit/progit2-zh#107]
加入我提了 PR #100 ，不满意要继续修改，是在 PR #100 的基础上接着修改重新提 PR #105 吗？

这样的话，如果PR #105  merge进去，那不是就有两个提交历史了吗？

commit 105
commit 100

但是 commit 100 不是有问题吗？也需要被合并进去吗？

**Comment by networm** [comment]
@archermind 其实是可以继续在原有的 PR 上提交的，不用再新开一个分支，要不然审查的意见都得来回找，而且你 105 与 101 的区别不太方便看。

**Comment by networm** [comment]
@archermind Git 本来就是用来记录历史的，有问题很正常，而且都是文本，存起来并不占什么空间。
而且就算是你最后一次 105 是完美的，假如以后要修改呢，还会有提交的，不可能这次提交后对应的文件永远不改变。

**Comment by archermind** [comment]
@networm OK
