### ISSUE TITLE
请大家在提交 PR 前自我审查一下

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#109]
**大家在翻译前一定要先将第一版中对应的章节阅读一遍**
尽量保证翻译的质量，特别是一些计算机术语。

**在提交前请多过几遍中英文的差别，确定翻译是否正确**
有些英文的关键内容没翻译出来，有些缺失，在检查时可以轻松发现。

**在提交前一定要在预览中仔细审查，找出所有可见的问题。**
大家必须做到实时预览，可以用浏览器插件或者特别的编辑器：
[Editing AsciiDoc with Live Preview | Asciidoctor](http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/)

预览时不要预览对应的文件，而是要预览父目录中的 asc 文件，这样图片才可以显示出来。
例如你要修改 "\book\03-git-branching\sections\nutshell.asc"，你需要预览 "\book\03-git-branching\1-git-branching.asc"

请大家在提交 PR 前努力修正各种非中文标点错误、英文前后留空格、英文专有名词大小写拼写等等常见问题。

**提交的 PR 命名要规范**
如你翻译的文件是 book/04-git-server/sections/gitweb.asc
那么标题就是是 Translate 04-git-server gitweb
规则是 Translate 加上 将 book sections .asc 去掉的路径

**一个 Pull Request 中只能含有一个章节**
含有多个章节的请自行拆分为不同的分支，分别发送 Pull Request。

因为审查也非常耗费时间，一个 300 行的 [Translated 03-git-branch/sections/basic-branch-and-merging by archermind · Pull Request #105 · progit/progit2-zh](https://github.com/progit/progit2-zh/pull/105/files) 就花费了我 70 分钟审查，如果只是因为一些小毛病反反复复修改的话，浪费的是大家的时间。

有任何问题欢迎提交 Issue。

**Comment by networm** [comment]
@networm
@Geno1024
@archermind
@neo1218
@wych42
@liwenzhuo
@spacewander
@WispZhan
@TenphyX
@oranzhang
@sanddudu
@branchzero
@jsenjoy
@zwpaper
@Gnahceg
@banxi1988
@garyzhucode
@leshiv
@adaiguoguo
@jiayouxjh
@xiaket

**Comment by branchzero** [comment]
收到

**Comment by Geno1024** [comment]
嗯，重要指示已收到。

**Comment by Geno1024** [comment]
下午提交之前自查了差不多20分钟。

**Comment by networm** [comment]
真的不想因为标点符号、空格等排板小问题打字浪费时间啊，关键还得来回改。

**Comment by sanddudu** [comment]
收到

**Comment by spacewander** [comment]
Ok

**Comment by sanddudu** [comment]
另外，“预览时不要预览对应的文件，而是要预览父目录中的 asc 文件” 这句不知道怎么理解...

**Comment by networm** [comment]
@sanddudu 后面的例子看懂了吗？

**Comment by tonghuix** [comment]
把这写到 README 里如何？

**Comment by networm** [comment]
@tonghuix 我认为我们需要的是这个 [progit2/CONTRIBUTING.md at master · progit/progit2](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md)

**Comment by tonghuix** [comment]
确实需要！

**Comment by networm** [comment]
@oranzhang @neo1218 @branchzero @WispZhan @Geno1024 
**一个 Pull Request 中只能含有一个章节**
含有多个章节的请自行拆分为不同的分支，分别发送 Pull Request。

**Comment by branchzero** [comment]
收到

**Comment by networm** [comment]
这是什么情况，你们都有 Github 客户端吗？都能马上收到通知？

**Comment by Geno1024** [comment]
@networm 有点歧义。一个章节的定义是不是指 https://github.com/progit/progit2-zh/issues/68 中的一行？

**Comment by networm** [comment]
@Geno1024 是的

**Comment by networm** [comment]
@branchzero @neo1218 @Geno1024 感谢如此迅速的修改，我会将你们原来的 PR 关闭。

**Comment by zwpaper** [comment]
收到，已修正。

**Comment by networm** [comment]
@zwpaper 看到你回复我还以为把你丢下了，赶紧去找了一圈，指派给你的任务应该就一个。

**Comment by zwpaper** [comment]
@networm 昨天有点事，才上线，看到 review 的问题就回复了，刚更新了 PR。

**Comment by networm** [comment]
哦，了解了，我以为你回复我刚刚发的问题呢。

**Comment by Gnahceg** [comment]
收到

**Comment by networm** [comment]
已进入审校阶段，关闭此 Issue。
