### ISSUE TITLE
[翻译约定] revision应该翻译成“修订版本”还是“版本”？

### ISSUE THREAD

**Issue by spacewander** [progit/progit2-zh#140]
第一版第6章中，“Revision Selection”中的“Revision”是翻译成“修订版本”的。
不过在 https://github.com/archermind/git/blob/master/po/zh_CN.po 里面， “revision”多翻译成“版本”。
那么，“revision”应该翻译成“修订版本”呢，还是“版本”呢？或者两者皆可，依上下文决断？

**Comment by sanddudu** [comment]
revision 原意就是修订、修订版、审校本，version 才指版本
语言文件里应该多数是根据使用的环境进行的意译
个人认为还是需要根据上下文进行选择

**Comment by OlingCat** [comment]
建议译作“修订版”以便和 version 区分。

**Comment by networm** [comment]
建议译作“修订版本”，与“版本”对应。
