### ISSUE TITLE
有关反引号两侧的空格

### ISSUE THREAD

**Issue by devbean** [progit/progit2-zh#146]
反引号一般用于有特殊格式的代码片段，英文原文中反引号两侧均有空格，个人认为，中文翻译中，反引号两侧的空格应该删除，以保持译文的紧凑。由于生成的代码片段带有特殊的格式，删除了空格也不会引起混乱。

**Comment by spacewander** [comment]
目前大部分情况下的做法是保留两侧空格……可以试下在后期统一用脚本替换

**Comment by networm** [comment]
我觉得可以在后期生成 PDF、HTML 时看看效果再决定如何解决。

**Comment by networm** [comment]
后期统一处理。
