### ISSUE TITLE
是不是应该统一一下术语的翻译

### ISSUE THREAD

**Issue by leo108** [progit/progit2-zh#15]
有不少不能直译的单词，不同的译者可能会翻译成不同的词，会给读者带来困惑

**Comment by archermind** [comment]
@devbean 到目前为止TRANSLATION_NOTES里面还没有一个翻译对照表吧？我看到有的同学将command翻译成指令，有的同学将其译成命令，风格不统一啊。而且貌似这个repo大家积极性不高？不如我利用业余时间，先整理一部分TRANSLATION_NOTES然后大家来慢慢补充，给后面翻译的同学一个参考。

**Comment by devbean** [comment]
目前还没有统一的对照表，如果你有时间的话可以做一个出来。之前因为个人原因比较忙，最近应该可以腾出手来继续翻译了

**Comment by archermind** [comment]
@devbean 我正在准备翻译对照表，我会尽快更新到TRANSLATION_NOTES里面的。

**Comment by devbean** [comment]
直接在 https://github.com/progit/progit2-zh/issues/45 讨论
