### ISSUE TITLE
关于 “shortname of the Git repository URL” 的译法

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#153]
目前的 shortname 译作“缩写”，个人感觉“别名”、“短名”或“简写”比较好。

首先“URL的缩写”没办法定义，因为你完全还可以取一个新的名字，可以不是URL中的任何字符串。其次还有 local path 的说法，甚至还可以设置独立的 fetch URL 和 push URL。例如：
```
[remote "origin"]
	url = ../my/project.git
	pushurl = https://github.com/My/Project.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
其实上面这三条信息合起来才叫一个 remote repository，就这点来说“缩写”也是不合适的，因为是给它取的一个名字。

各位有何高见？

**Comment by networm** [comment]
我认为叫“简写”较合适，因为英文的原意就是简化、缩短之间，而且“简写”符合我们日常的用语习惯。
刚刚搜到一个 [线上聊天的英文简写](http://www.douban.com/note/79909098/) 内容，可见“简写”已被广泛接受。

**Comment by OlingCat** [comment]
OK
