### ISSUE TITLE
降低文中“你”字的使用频率

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#154]
鉴于中文的习惯，下上下问确定客体为“你”时可以省略掉一些。读者也不想在阅读是“被命令”做什么事情吧？

**Comment by networm** [comment]
嗯，我在翻译时遵循的原则是尽量还原原文的意思，看样在 v2 中需要根据中文习惯去掉一些无用的信息。

**Comment by robinwen** [comment]
不知道职业的翻译是怎样的要求，但是我想上下文确定客体为“你”时可以省略“你”的翻译的一个前提是不是仍然要保证译文的主谓要一致？即句子的主语需要是句子谓语的执行者？

比如这一句：
Git doesn't automatically infer your command if you type it in partially.
之前译文是：
Git 并不会在输入部分命令时自动推断出命令。

我总觉得省略掉“你”之后，虽然也能读通，但中文文法上会有问题，因为“输入”的主语并不是 Git，而是 you；“推断”的主语才是Git。所以我认为这里这样翻译比较合适：

Git 并不会在你输入部分命令时自动推断出该命令。

**Comment by buginux** [comment]
所见略同，之前没看到这个issue，我也刚刚在审校过的一小节里提了类似的建议。

**Comment by OlingCat** [comment]
@robinwen 嗯这个确实是需要“你”的。
我的方法是，遇到拿不准的表达方式，就对着一个完全不懂计算机的人说一句话，只要他感觉到句子啰嗦或语感奇怪，就重新组织语言来表达清意思，也因此我的翻译速度很慢。

**Comment by robinwen** [comment]
@OlingCat 这是一个好办法！慢点我觉得不是问题，质量更关键。

**Comment by oldsharp** [comment]
+1
所以这个建议的实施，是等到最后统一处理呢，还是让各位译者在审阅过程中自行处理掉呢？

**Comment by networm** [comment]
@oldsharp 这种问题可不是批处理可以解决的，要根据特定情况特定分析解决，所以要在审阅的过程中处理。

**Comment by oldsharp** [comment]
@networm 是的，我也这么认为 ;-)

**Comment by OlingCat** [comment]
话说..大家在去掉“你”字之前能否先自己读一下？ @sanddudu 注意到好多句子已经没有主语了= =||

**Comment by oldsharp** [comment]
我个人的体会：因为，之前是完全按照原文翻译，“你”的出现频率相当之高。修正过程中，虽然会试读，但有可能会出现纠正过度…

**Comment by OlingCat** [comment]
@oldsharp 那就先放下，等把这种过度修正的习惯（或惯性？）缓和之后再重新读，添加主语吧....

**Comment by networm** [comment]
这里希望审校者能提出意见。

**Comment by sanddudu** [comment]
@OlingCat：我觉得没必要了统一“你”和“我们”，在语境里跟着做的就是“我们”，可以做的是“你”就差不多了，或者怎么顺嘴怎么来

**Comment by sanddudu** [comment]
另外“我们”比较 friendly
如果觉得“你”太多了可以适当的转化

**Comment by oldsharp** [comment]
昨天下午因为赶时间，没来得及表述关于“缺少主语”的问题。我的观点是这样的：

在翻译过程中，会遇到这样的场景：某些译文的单句，独立来看的确缺少主语，但是结合上下文语境，句子的主语是可以明确界定的。

例如 https://github.com/progit/progit2-zh/pull/115/files#diff-772163a55c3fd697af639e23b0122c70L59 ：

>
59  Now, you can add content to Git and pull it back out again.
60  You can also do this with content in files.
61  For example, you can do some simple version control on a file.
62  First, create a new file and save its contents in your database:
...
71  Then, write some new content to the file, and save it again:

目前的译文如下：

>
59  至此，你已经掌握了如何向 Git 中存入内容，以及如何将它们取出。
60  我们同样可以将这些操作应用于文件中的内容。
61  例如，可以对一个文件进行简单的版本控制。
62  首先，创建一个新文件并将其内容存入数据库：
...
71  接着，向文件里写入新内容，并再次将其存入数据库：

可以看到，上述译文中的 61、62、71 行，单独拎出来看，严格来说都是缺少主语的；但是结合上下文语境，读者可以确定默认主语是“我们”，所以阅读起来并不突兀。并且，原文的 62、71 行，也把主语省略了。

上述场景处理方法，在技术类书籍、文档的翻译工作中，比较常见。**这种情况下省略主语是恰当的**，不省略反而会像所有祈使句都加上“你”一样，显得啰唆了。

当然，除此之外，主语不能省略，不然就是语病了。

**Comment by networm** [comment]
大家说得都很有道理，我觉得 @oldsharp 将大家说的整理一下加到 TRANSLATION_NOTES 里面吧！

**Comment by oldsharp** [comment]
我发现我之前举的例子有不妥当的地方，因为有部分句子是祈使句，而祈使句本来就可以省略主语，即使单独成句也没问题。
但我所说的“根据上下文省略主语”的情况还是存在的，各位不妨参考。

**Comment by oldsharp** [comment]
@networm 已经提交相应的 PR。
