### ISSUE TITLE
一些中文与英文的语序不同的要怎么处理？

### ISSUE THREAD

**Issue by Geno1024** [progit/progit2-zh#172]
刚刚看了一下 `06-github` 的 `4-managing-organization` ，其中第 6 行：
` 类似于个人帐户，组织帐户提供一个命名空间用于存放所拥有的项目，但是也有很多不同的地方。 `
对应的原文是：
` Like personal accounts, Organizational accounts have a namespace where all their projects exist, but many other things are different. `
可以看到这个中文翻译使用了原文的英文语序。
我不知道这样是否可以，就是我们在翻译的时候，使用中文的语序。
但是对于例如 where 引导的从句来说，在翻译时将它们放在从句主语之前，这样有时候会使句式变得看起来复杂或者甚至难以理解。
我负责的翻译部分是 `B-Embedding-git` 整章，遇到这种比较复杂的句式（例如：主语 + 谓语 + 宾语，从句宾语 + 从句谓语 + 从句主语 + 从句宾语补足语），我习惯于把它们调换成中文语序，但是这种调换很复杂，很奇怪，还容易出错，即使不出错，出来的句子也是奇奇怪怪的。
所以，大家觉得，要用哪个？或者介于两者之间？

**Comment by robinwen** [comment]
我自己在做一些翻译的时候也会碰到复杂的英语句子的问题，如果硬按照英语来翻译的话，我觉得非常难受，所以在这种情况下我会转向优先采用意译，在中文可以表达清楚的前提下再尽量和原句的语序相近。

具体的做法是：
1. 改写英语原句，把复杂的长句用标准的主+谓+宾的简单句写出来。这个步骤的一个额外好处就是可以帮助你确认自己是否真正理解了英语原句。
2. 翻译每一个简单句。
3. 综合各个翻译过来的中文简单句，使用一个或多个稍微复杂的中文句子表达原意。也就是说，一个英语原句，此时我可能会采用多个中文译句来表达。
4. 再综合英文原句，适当做调整。

供参考。翻译的三个标准：“信”、“达”、“雅”中的“达”其实就有“不拘泥原文形式”的含义，即译文要通顺明白。当然，前提是“信”：不歪曲原文。

**Comment by robinwen** [comment]
我还有一个技巧，就是把一些非限制性定语从句或补足语用括号的方式表达出来，因为我记得这些信息本身就是额外的补充说明，去掉之后也不会影响理解，所以在中文译文里放到括号里或许是一个办法。

**Comment by Geno1024** [comment]
@robinwen 我试过用括号，虽然它容易理解多了，然而对于非翻译组人员有时会误认为这是注释。

**Comment by robinwen** [comment]
呃，我可能没有完全理解了背景，所以被误认为是注释会有什么问题吗？

可能我的翻译风格会偏暴力一些，因为我理解“翻译”的首要任务是信息传达，格式当然也重要，但是如果因为格式等原因可能造成信息偏差，那我会果断放弃格式的考虑，优先保证信息传达。所以我的建议是，如果被误认为是注释会导致理解偏差，那么的确是需要再斟酌一下；如果不影响理解，那么我认为被当成注释就注释吧~ :-D

**Comment by Geno1024** [comment]
@robinwen 我的意思是一般来说括号里的东西总是给人一种可有可无的感觉，而我们为了帮助理解而加的括号的内容是和括号外的东西同等重要的，所以可能会造成理解偏差。

**Comment by archermind** [comment]
我同意 @robinwen 的观点
>1. 改写英语原句，把复杂的长句用标准的主+谓+宾的简单句写出来。这个步骤的一个额外好处就是可以帮助你确认自己是否真正理解了英语原句。

关于这个问题，我特地请教过我的英文老师，确实不必拘泥于英文的形式，要符合中文的文法和习惯。
