### ISSUE TITLE
遇到英文中的缩写，应该如何更好的表达其意思呢？

### ISSUE THREAD

**Issue by archersmind** [progit/progit2-zh#178]
在翻译的时候遇到了这样的问题，英文原文是：

>Some larger projects also have a `proposed` or `pu` (proposed updates) branch that has

我的译文是：
>一些大型项目还有一个 `proposed`（建议） 或 `proposed updates`（建议更新）分支

在翻译的时候，我把`pu`这个短语给丢了，当时纠结了一下，用怎样的方式结合才可以把 `pu`， `proposed updates`， `建议更新` 这些信息都传递给读者呢？

**Comment by Geno1024** [comment]
` proposed updates`  （建议更新，pu）
或者在 pu 前面加个“简称”
这样如何？

**Comment by networm** [comment]
> 一些大型项目还有一个 `proposed`（建议，proposed） 或 `pu`（建议更新，proposed updates）分支

这样如何？

**Comment by archermind** [comment]
最好能找到一些范例来佐证，我下去再查一查。

**Comment by ahlijin** [comment]
前面用中文，括号内先全称在逗号缩写，比如说：万维网（World Wide Web，WWW），有时候强调或者特殊用法需要使用引号：Berners-Lee首次提出了“语义Web”（semantic Web）

**Comment by networm** [comment]
@ahlijin 这样翻译大部分地方可以了，可能个别地方需要针对上下文自行处理，方式灵活一些即可。
