### ISSUE TITLE
命令中的 option 应该翻译成什么？

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#186]
> If you pass the option `--system` to `git config`, it reads and writes from this file specifically.

这其中的 `--system` option 应该翻译为 `选项` 还是 `参数`，书中有大量类似的地方，需要统一一下。

**Comment by robinwen** [comment]
我认为 option 应该翻译成 选项 比较好。参数 应该是对应 parameter 这个词吧。

**Comment by Geno1024** [comment]
@robinwen 
option 选项
parameter 参数
+1
这感觉已经是通用的翻译了

**Comment by networm** [comment]
我个人也是认为 `选项` 较好，但问题还是先放两天让大家看下再说。

**Comment by ahlijin** [comment]
个人认为应该翻译成选项
另外，对于前面的动词，英文中很多混用，但中文“使用”-“选项”，“传递”-“参数”会更好一些

**Comment by networm** [comment]
@ahlijin 但是这可能会造成混乱，因为上下文会混合使用。

**Comment by archersmind** [comment]
`选项` +1，一旦确定了之后记得更新一下翻译对照表。

>#: archive.c:11
msgid "git archive [<options>] <tree-ish> [<path>...]"
msgstr "git archive [<选项>] <树或提交> [<路径>...]"

上面这段摘之 [Git 软件包的简体中文翻译]( https://github.com/git/git/blob/master/po/zh_CN.po)

**Comment by sanddudu** [comment]
In computer programming, a parameter is a special kind of variable, used in a subroutine to refer to one of the pieces of data provided as input to the subroutine.
其实 progit 基本没有说过参数，只有提到 option，参数只在示例里出现

**Comment by networm** [comment]
@archersmind @sanddudu 确定为“选项”了，已合并 PR。
