### ISSUE TITLE
02-git-basics undoing一节中的一个翻译问题

### ISSUE THREAD

**Issue by robinwen** [progit/progit2-zh#188]
在Translate 02-git-basics undoing v2中(链接在[这里](https://github.com/progit/progit2-zh/pull/151/files))，原文82行是如下一句：

While `git reset` _can_ be a dangerous command if you call it with `--hard`, in this instance the file in your working directory is not touched.

当前的译文是：

如果使用 `--hard` 选项调用 `git reset` 命令则它 _会_ 是一个危险的命令，在这种情况下**工作目录中的文件将会丢失所有的修改**。

加重部分的含义似乎和原文的字面意思不符合。我看到这个是之前@pktangyue 提出的修订建议。想问一下为什么这样翻译？我认为应该翻译成“工作目录中的文件并不会被修改”。是不是有什么我对git和这个命令还不够熟悉的地方？

**Comment by networm** [comment]
@robinwen 在这种情况下 指的是前面的用 --hard 的 git reset 命令。
因为 git reset --hard 后面不能接路径，所以 在这种情况下 不是指前面的例子。
is not touched 指的是文件像未改动之前一样没有人碰过，按照 git reset --hard 的实际效果来看。
本质是 git reset --hard 会将工作目录中的内容也重置掉。

**Comment by wych42** [comment]
git reset --hard 实际效果就把当前的工作目录重置到上一个commit的状态，所以这么翻译意思是对的。

**Comment by oldsharp** [comment]
如果严格按照原文的意思，我赞同 @robinwen 的意见。

原文：
> While `git reset` _can_ be a dangerous command if you call it with `--hard`, in this instance the file in your working directory is not touched. Calling `git reset` without an option is not dangerous - it only touches your staging area.

当前译文：
> 调用加 `--hard` 选项的 `git reset` 命令 _会_ 很危险，它会让工作目录中的文件丢失所有的修改。调用不加任何选项的 `git reset` 则不危险 - 它只会修改暂存区域。

单就译文所陈述的 Git 知识点来看，是没问题的；但注意原文以 While 开头，所以原文第一句应该是一个让步状语从句——while 在此处作连词，**表转折**。第二句则是对第一句的补充说明。

请看《Oxford Dictionary of English》中 [while 词条](http://www.oxforddictionaries.com/definition/english/while)的连词部分：

![while2](https://cloud.githubusercontent.com/assets/980500/8822071/4d6fb8ba-3095-11e5-99c2-4ab23bd45907.png)

原文语境更贴近条目 2.1（虽然、尽管，表转折），而不会是条目 1（当……时候，表时间状语从句），也不会是条目 2（表示并列、对比）。所以我认为，更贴近原文的译法是：
> 虽然在调用时加上 `--hard` 选项_可以_令 `git reset` 成为一个危险的命令，但本例中工作目录内的文件并不会被修改。不加选项地调用 `git reset` 并不危险——它只会修改暂存区域。

（顺带提一下的是，个人认为，中文词组两边加“_”表强调的，不用再像英文原文那样再加上一对空格符。）

**Comment by pktangyue** [comment]
@oldsharp 按照之前的翻译，git 初学者并不能很好的理解 `git reset --hard` 的危险性。我用反义的意思强调出危险性在哪里。
如果使用 --hard 选项调用 git reset 命令则它 会 是一个危险的命令，
这里的 `则` 就是根据 `while` 的转折语气翻译的。

**Comment by OlingCat** [comment]
赞同 @pktangyue 的意见，尽管原译法最贴近原文字面意思，但官方文档有时不大能考虑到初学者的立场，我们这么强调不算过分。

另外，个人不建议使用斜体来表示强调。就我个人的经历，大多数汉字字体的斜体不仅有虚化而且显示效果很差，反而起不到强调的作用。我看过的一些书的中文翻译版（例如SICP）会使用楷体作为名词或强调，排版效果还不错。个人建议，在文中使用粗体表示强调，斜体表示注释。

@oldsharp 至于为啥要加空格，我觉得不是因为排版规定问题，而是因为不加空格的话 Github 的 md 有时会解析失败= =||

**Comment by robinwen** [comment]
Sorry... 这段时间太忙了，没有时间参与大家的讨论。。:joy: 过段时间忙完了再回来看。。

**Comment by oldsharp** [comment]
**一、**

1. 争议处原文是以 While 开头的从句；
2. 争议处原文所处的这个 Note，一共两句话。从整个 Note 的语境看，其主要目的是向初学者阐述 `git reset HEAD <file>...` 用于撤销暂存时并没有危险性，而不是作为警告出现；
3. 紧接着这个 Note 的原文是这样的：

> For now this magic invocation is all you need to know about the `git reset` command. We'll go into much more detail about what `reset` does and how to master it to do really interesting things in <<_git_reset>>.  
到目前为止这个神奇的调用就是你需要对 `git reset` 命令了解的全部。我们将会在 <<_git_reset>> 中了解 `reset` 的更多细节以及如何掌握它做一些真正有趣的事。

显然，原作者并没有打算在这里点明 `git reset --hard` 具体危险在哪里，他认为这件事情应当留给[后文详细解释 `reset` 的章节](http://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified#_git_reset)来完成——潜台词是，到目前为止，初学者只需知道他可以放心大胆地按照 `git status` 所提示的那样操作，就够了。当然，如果有想要深究的读者，希望继续了解 `--hard` 的细节，他只需点击一下原文给出的链接。我觉得，这样更贴近《Pro Git》针对初学者的定位；

综合上述三点，我还是**坚持**我的意见：争议处的翻译应当遵从原文意思，不必另作强调。


**二、**

@pktangyue 您提到：
>如果使用 --hard 选项调用 git reset 命令则它 _会_ 是一个危险的命令，
这里的 `则` 就是根据 `while` 的转折语气翻译的。

1. #151 最新版本译文中，此处并没有“则”这个转折；即使按照您的译法，那么原文中的“in this instance the file in your working directory is not touched.”还是无从对应——**您的译法（或者说当前译法）相当于增加了一段“译者注”，同时隐式地略去了一段原文，然而却并没有作任何相应的说明或标注**。
2. 并且，按照 @networm 在本 thread 中对当前译法的[解释](https://github.com/progit/progit2-zh/issues/188#issuecomment-118904189)，我认为有一定偏差：1) “in this instance”所指代的就是前文的例子，而不是 `git reset --hard`；2) 对“is not touched”的解释有点牵强。

所以，如果 finally 仍然确实觉得有必要作警告处理，我建议，可以考虑**如下方案**：

> 虽然在调用时加上 `--hard` 选项**可以**令 `git reset` 成为一个危险的命令（译注：可能导致当前工作目录中所有进度丢失！），但本例中工作目录内的文件并不会被修改。不加选项地调用 `git reset` 并不危险——它只会修改暂存区域。


**三、**

很赞同 @OlingCat 的：

> 个人建议，在文中使用粗体表示强调，斜体表示注释。

**Comment by networm** [comment]
现在再看发现之前我讲的确有问题，同意 @oldsharp 的说法。

**Comment by networm** [comment]
> 虽然在调用时加上 `--hard` 选项**可以**令 `git reset` 成为一个危险的命令（译注：可能导致工作目录中所有当前进度丢失！），但本例中工作目录内的文件并不会被修改。不加选项地调用 `git reset` 并不危险——它只会修改暂存区域。

最终决定采用 @oldsharp 所提出的方案，仔细思考后觉得这个方案是最合适的。
