### ISSUE TITLE
招募记录

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#192]
这里会将已经发布的招募贴子地址记录下来，方便之后追溯、清理。

**Comment by networm** [comment]
ProGit 2nd 中文版 翻译协作计划 - V2EX
https://v2ex.com/t/198736

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 - V2EX
https://v2ex.com/t/202180#reply12

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划
http://www.douban.com/group/topic/77855035/

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 (评论: Pro Git)
http://book.douban.com/review/7544894/

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划
http://www.douban.com/group/topic/77854461/

**Comment by Geno1024** [comment]
GitHub 家园
在一个 QQ 群里发。。。

**Comment by networm** [comment]
Git版本控制 178364525
Git中文 23541011
Git中文 215314429
GitHub家园② 193091696

以上QQ群已发。

**Comment by Geno1024** [comment]
GitHub 家园 225932282
已发。

**Comment by IceNature** [comment]
ProGit 2nd 中文版 审校协作计划
http://bbs.csdn.net/topics/391080891
@networm

**Comment by networm** [comment]
@IceNature 这里就可以。

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 » 社区 » Ruby China
https://ruby-china.org/topics/26683

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 - Golang中国
http://golangtc.com/t/55b7ab93b09ecc22f6000269

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 - F2E
http://f2e.im/t/1201

**Comment by networm** [comment]
ProGit 2nd 中文版 审校协作计划 - CNode
https://cnodejs.org/topic/55b7ae641557dd98790d3732

**Comment by sanddudu** [comment]
全栈工程师 364021031
