### ISSUE TITLE
审校验收问题

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#198]
原定的是每一个章节都经由三个人审校后算完成，但是需不需要一个人来最终验收呢？
刚开始 @OlingCat 申请成为 Reviewer 的时候就想要做这件事，见 #106 ，但当时的内容还未完全翻译完成，时机不成熟，现在可以了。
请大家各抒己见，讨论一下。

>  OlingCat commented on 17 Jun

> 鉴于现在的任务分配情况差不多了，剩下的内容我也并不擅长。粗略看过本书译文之后，发现语句的通顺度尚不如意，因此自荐申请成为审校者，为已经翻译过的内容修改润色。

> 不过作为统领全书行文风格和术语标准的审校者，至少要具备一定的翻译经验。本人是 Go-zh 项目的翻译和负责人，代表译文有 实效 Go 编程 、 Go 编程语言规范 （旧译版，新版仍未完成）和 包文档 等官方文档，以及 命名的学问 、反射法则 与 Go 切片：用法和本质 等官方博文，偶尔也去 MDN 和 Wiki 上译些文档。

> 因此，本人希望贡献自己的力量，让 Pro Git 第二版更加严谨细致，简明易读，也能让这本自己很喜欢的书以最好的状态面世。

**Comment by networm** [comment]
@Geno1024
@Gnahceg
@IceNature
@TenphyX
@WispZhan
@adaiguoguo
@ahlijin
@archersmind
@banxi1988
@branchzero
@buginux
@byr-gdp
@garyzhucode
@gisphm
@jiayouxjh
@jsenjoy
@leshiv
@liwenzhuo
@neo1218
@networm
@oldsharp
@oranzhang
@peizh
@pktangyue
@qinglangee
@robinwen
@sanddudu
@secondwtq
@spacewander
@tonghuix
@wych42
@xiaket
@xinqiu
@zwpaper

请大家各抒己见，讨论一下上述问题。

**Comment by Geno1024** [comment]
觉得吧，那三个人一致同意就行啦。

**Comment by branchzero** [comment]
每个人的语言组织都有所不同，最好有一个人能够把所有翻译的语言组织方式统一一下，要不然估计读起来会有些乱。

**Comment by archersmind** [comment]
@networm 不需要太集中化管理，这样就失去了协作的意义了。三个人来review一节，没有大的问题，三个人读起来都舒服的话，就可以放过了。众口难调，不可能让每个人都happy

**Comment by IceNature** [comment]
同楼上，三个人再读一遍都读着舒服的话就可以合并了

**Comment by robinwen** [comment]
这个事情的处理和个人参与这个翻译项目的期望有关。有的人希望为国内同行提供一本较高质量的译本，所以大概会希望有一个终审进行统一把关；有的人希望发扬平等协作的精神，认为参与比结果更重要；还有人可能有别的期望。

我个人倾向于由一个或几个人组成终稿统筹小组，主要做：
1. 审校格式、标点等，确保没有问题；
2. 尽量统一一下语言风格；
3. *不做*内容检验(这个是当前三人协同审校的事情)。

**Comment by xinqiu** [comment]
要不要对照第一版的语言风格看看？

**Comment by networm** [comment]
@robinwen 我倾向于你说的第二点——即统一语言风格，尽量让读者看到的像是一个作者的风格。其他的都不用处理。

**Comment by networm** [comment]
@xinqiu 我认为不用与第一版的语言风格一致。

**Comment by networm** [comment]
我觉得三个人审校完之后就合并后，所有审校格式、标点、语言风格等问题统一放到后期处理。这样也可以提升项目进度，让大家更有干劲。

**Comment by archersmind** [comment]
@networm 

>我觉得三个人审校完之后就合并后，所有审校格式、标点、语言风格等问题统一放到后期处理

保持大家积极性，不错～

**Comment by networm** [comment]
@archersmind 因为项目从计划开始翻译到现在，还没有任何一个章节进入主干，有些 PR 已经放了快两个月了！

**Comment by archersmind** [comment]
@networm 是的，确实令人着急，但是还是要按部就班，大家先review完再merge

**Comment by IceNature** [comment]
有一点我不太清楚。看前面说的现在的审校只需要修改翻译错误的地方不需要再考虑语句是否通顺是吗？

**Comment by sanddudu** [comment]
@IceNature 现在是两个都要考虑
最后的 review 应该只要考虑格式之类的

**Comment by networm** [comment]
@IceNature 刚刚 @sanddudu 的解释就是答案。

**Comment by buginux** [comment]
我也倾向于认为统一一下风格，毕竟如果同一章，甚至同一节风格读起来都不一样的话，对于普通的读者可能会造成不好的体验吧。

**Comment by ahlijin** [comment]
我也有这个想法，最后统一由几个人review一下，统一一下一些语言的组织。至少每章要统一，整本书由一个人来看不太现实

**Comment by OlingCat** [comment]
呃..说来惭愧。本人之前略忙，因此并没有正式认领过任务，只是东一榔头西一棒槌地提些建议。之后我会有空余的时间来审校。我倾向于先让三个人通过审校后并入主分支，等生成阅读版后再根据效果继续修订。如果本书要出版的话，语言风格再由一两个人来统一。

2015-07-25 16:00 GMT+08:00 justaway <notifications@github.com>:

**Comment by wych42** [comment]
现在的问题是没有标准，三个人review完了之后就没有下文了。

我觉得在这一波全部review完成后，再来一次交叉审阅。现在做到信和达，下一波做到达。

**Comment by networm** [comment]
@wych42 交叉审阅该用什么形式做呢？

**Comment by wych42** [comment]
@networm  现在这种三个人review的形式可以，但是需要有两到三个人从头到尾把关语言组织、风格这种，其他人参照这个来，互相提出评价和改进。

**Comment by networm** [comment]
@wych42 我感觉交叉审阅实际操作起来很麻烦，不如我们先合并到主干，等都完成了再统一语言风格。

**Comment by jiayouxjh** [comment]
建议明确建立一个语言格式规范以及标点规范的标准，这样大家按照这个标准来先从格式方面进行审校，在确保风格统一格式没有问题之后，可以再对于个别细节进行推销完善。

**Comment by spacewander** [comment]
三人review之后就合并到主干吧，最后交由一个审核小组进行终稿风格的统一就好了。

**Comment by networm** [comment]
@Geno1024
@Gnahceg
@IceNature
@TenphyX
@WispZhan
@adaiguoguo
@ahlijin
@archersmind
@banxi1988
@branchzero
@buginux
@byr-gdp
@garyzhucode
@gisphm
@jiayouxjh
@jsenjoy
@leshiv
@liwenzhuo
@neo1218
@oldsharp
@oranzhang
@peizh
@pktangyue
@qinglangee
@robinwen
@sanddudu
@secondwtq
@spacewander
@tonghuix
@wych42
@xiaket
@xinqiu
@zwpaper

OK，最终决定在三个审校后直接合入主干，最终由一个审核小组统一风格。

**Comment by Geno1024** [comment]
收到。

**Comment by ahlijin** [comment]
**OK**
