### ISSUE TITLE
annotated tag 翻译问题

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#205]
这两个词组的翻译问题

annotated tag lightweight tag
1. 含附注标签 轻量级标签
2. 注释标签 轻量标签
3. 注解标签 轻量标签  现在 Git 官方中文

我个人倾向于使用方案1 “含附注标签 轻量级标签”，因为感觉“注释”与“标签”是平级的，而英文中的原意是标签是主语。

请大家讨论一下，最终也会决定 Git 官方库里的中文翻译。

Translate 02-git-basics tagging v2 by networm · Pull Request #155 · progit/progit2-zh
https://github.com/progit/progit2-zh/pull/155/files

**Comment by networm** [comment]
Add definations by networm · Pull Request #204 · progit/progit2-zh
https://github.com/progit/progit2-zh/pull/204

**Comment by oldsharp** [comment]
@networm 你可以看一下 jiangxin/git#4 ，所有的 tag 翻译都在这里面了。
我刚才稍微想了下，感觉“注释标签”比较适合 Git 中文本地化里面的语境，因为那里面基本上都是提示信息/错误信息，比较简洁。
“含附注标签”则更适合我们《Pro Git》的翻译语境。

**Comment by IceNature** [comment]
感觉 1 更好
`annotated tag` 直接译为`附注标签`怎么样？

**Comment by oldsharp** [comment]
中和一下，“含注释标签”、“轻量级标签”，如何？

**Comment by oldsharp** [comment]
请看“However, there were unannotated tags: try --tags.”（Git 中文本地化 5055 行），这里的“unannotated tag”如何翻译？
我当时考虑到这个，所以认为“带注释标签”、“非注释标签”比较匹配。
不过最后还是把“带”给去掉了。

**Comment by networm** [comment]
@oldsharp 未含附注标签

**Comment by IceNature** [comment]
简洁点 附注标签 和 未注标签 可以吗？ @oldsharp @networm

**Comment by networm** [comment]
@oldsharp “unannotated tag” 这个指的是轻量级标签吧？

**Comment by networm** [comment]
> 含附注标签是存储在 Git 数据库中的一个完整对象。它们是可以被校验的；其中包含打标签者的名字、电子邮件地址、日期时间；还有一个标签信息；并且可以使用 GNU Privacy Guard （GPG）签名与验证。

也就是说其中并不是只有注释或提交信息，而是有其他相关的所有信息。

**Comment by buginux** [comment]
倾向使用“附注”，感觉比较好。

**Comment by oldsharp** [comment]
@IceNature “附注标签”不错，“未注标签”感觉有点怪，不如“未附注标签”。

@networm 是的，指的就是轻量级标签。

> 也就是说其中并不是只有注释或提交信息，而是有其他相关的所有信息。

你的意见很有道理，说服了我。我之前仅从语感简洁角度考虑了，没有考虑到这层。

那么就决定采用“含附注标签”和“轻量级标签”。Git 中文本地化那边的 PR 我去做相应修改。

**Comment by networm** [comment]
@oldsharp [附注_百度百科](http://baike.baidu.com/view/362683.htm) [注释_百度百科](http://baike.baidu.com/view/110472.htm) 看百度百科这两个链接内容的话，觉得是可以用注释的；但有一个问题是说“注释”这个词在计算机领域用的太多了，参见：[注释 (计算机语言) - 维基百科，自由的百科全书](https://zh.wikipedia.org/zh/%E6%B3%A8%E9%87%8A_(%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%AF%AD%E8%A8%80))，而且主要是在计算机程序语言中使用，我认为很容易发生歧义。
所以我个人倾向于使用“含附注标签”，当然如果是出于简洁性的考虑，“注释标签”也是个次要选择，看看 Git 中文化那边如何评论吧。

**Comment by oldsharp** [comment]
@networm 好。

**Comment by networm** [comment]
官方用的 注解标签 这个呢？看起来也是个不错的选择。

**Comment by oldsharp** [comment]
“注解标签”、“非注解标签”、“轻量标签”，这样吗？

**Comment by networm** [comment]
@oldsharp 是的

**Comment by jiangxin** [comment]
看了大家的讨论，比较赞同“附注标签”。

注解、注释标签在 Git 中文本地化都有出现，不严谨。而且 注解、注释本身既可作为动词，又可作为名词，没有 "附注标签" 准确。

**Comment by oldsharp** [comment]
根据 @jiangxin 的建议，最后我们项目参照 Git 中文本地化项目，定为“附注标签”、“未附注标签”、“轻量标签”吧。
需要作相应修改的 PRs 有： #204 , #155 , #137 .

**Comment by networm** [comment]
@oldsharp 同意。

**Comment by networm** [comment]
@oldsharp #155 已经合并至主干，无法修改，但是我已合并 #207 来修改 tagging 章节。

**Comment by oldsharp** [comment]
@networm 好的。这个 issue 现在应该可以 close 掉了。
