### ISSUE TITLE
reapply 如何翻译？

### ISSUE THREAD

**Issue by IceNature** [progit/progit2-zh#209]
#165 中有一句：
>You can save a stash on one branch, switch to another branch later, and try to reapply the changes.

之前 `reapply the changes` 翻译为 重演更改，我觉得有点病句，大家怎么看？

**Comment by sanddudu** [comment]
再次进行修改
如何？

**Comment by sanddudu** [comment]
看了一下，翻译成“再次提交修改”比较好

**Comment by networm** [comment]
我个人倾向于 “重演”，因为较简洁；否则的话是“重新应用”，这也符号 Git 里这个操作的实质；而“再次进行修改”，在 Git 某些地方可不是这样的。

**Comment by Geno1024** [comment]
如此简洁的单词，不应该有过长的翻译。支持“重演”，或者“复用”之类的，也许是生造出来的词。

**Comment by sanddudu** [comment]
我比较同意“重新应用修改”，第一版也是这么翻译的，意思更清晰。
重演和复用我认为是咬文嚼字的结果，偏离了原本的意思，英文单词的形式本身就很灵活，简洁应该是建立在能把话说清楚的基础上。

**Comment by IceNature** [comment]
度娘百科 重演：再度上演,比喻旧景重现
重指的是再次 不是 重新。这个词re-apply ，re做前缀，应该指的是重新的意思。
我觉得对修改来说 演 总有点不太对劲……只是感觉

**Comment by sanddudu** [comment]
@IceNature 生物学中的重演有自己的英文单词，叫 recapitulation
(biology) The reenactment of the embryonic development in evolution of the species.

**Comment by networm** [comment]
@sanddudu 我建议是“重新应用”而不是“重新应用修改”，“修改”是 "the changes"。

**Comment by sanddudu** [comment]
@networm 我前面已经说了，同意 “重新应用”...

**Comment by IceNature** [comment]
如果意见一致 重新应用 我就 close 了
