### ISSUE TITLE
Commit message 翻译成“提交信息”还是“提交说明”

### ISSUE THREAD

**Issue by Kyle-ak** [progit/progit2-zh#212]
英文直译应为“提交信息”，但是实际上 Commit message 是针对该 Commit 的一个说明，意译为“提交说明”更加直观，符合它的实际定义。

**Comment by networm** [comment]
我倾向于“提交信息”，这已成为一个通用的词汇，很多版本控制软件都使用这个。

**Comment by OlingCat** [comment]
“提交信息” 在很多书籍中已经约定俗成了，就这个好了。
