### ISSUE TITLE
第一章中图片路径错误

### ISSUE THREAD

**Issue by FrozenYogurtPuff** [progit/progit2-zh#215]
导致图片无法加载

**Comment by networm** [comment]
@FrozenYogurtPuff 可以说一下是哪一个章节的哪一行出问题了。

**Comment by FrozenYogurtPuff** [comment]
01-introduction的about-version-control.asc中
三张图片路径分别为
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/sections/images/local.png
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/sections/images/centralized.png
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/sections/images/distributed.png
应当分别修改为
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/images/local.png
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/images/centralized.png
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/images/distributed.png
第一章其他部分同理
***
第二章中recording-changes.asc下的图片路径应由
https://github.com/progit/progit2-zh/blob/master/book/02-git-basics/sections/images/lifecycle.png
改为
https://github.com/progit/progit2-zh/blob/master/book/02-git-basics/images/lifecycle.png

**Comment by sanddudu** [comment]
@FrozenYogurtPuff 这些图片地址在生成书本后会自动进行处理，线上版也是，Github 中插入的图片是直接基于相对地址的（即文中的地址），所以并不需要修改。
线上版本均可以正常显示：http://git-scm.com/book/zh/v2/%E8%B5%B7%E6%AD%A5-%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E6%8E%A7%E5%88%B6

**Comment by FrozenYogurtPuff** [comment]
> 这些图片地址在生成书本后会自动进行处理，线上版也是，Github 中插入的图片是直接基于相对地址的（即文中的地址），所以并不需要修改。

谢谢 受教了
