### ISSUE TITLE
统一 last commit 与 next commit 的译法

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#218]
目前分别译作 “最后一次（个）提交” 和 “下一个提交”，但我觉得“上一次提交”和“下一次提交”比较好，大家认为呢？

**Comment by networm** [comment]
last commit 还有译作“最近一次提交”的，是不是要根据上下文决定如何翻译？

**Comment by OlingCat** [comment]
可以，在强调最近一次时就译作“最近一次提交”，在 last 和 next 同时出现，强调次序时就译作 “上一次提交”和“下一次提交”。

**Comment by oldsharp** [comment]
在这个 issue 提出之前，我的一个 PR 里面也有遇到类似问题：https://github.com/progit/progit2-zh/pull/137#discussion_r35948084
当时在那里面我给统一成“最新提交”了（ b92da27 ）。

这些地方，是否需要最后全书统一一下？

**Comment by networm** [comment]
@oldsharp @OlingCat 最后需要统一一下，建议再讨论讨论，根据不同的情境了解下。

**Comment by lilydjwg** [comment]
不建议将其翻译成具有时间意义的词。因为一旦涉及时间，你就得注意，是创作时间还是提交时间？如果是指创作时间的话，那么显然最后一次提交可以比其它很多提交都旧；如果是指提交时间的话，在特殊情况下它也可以不是最新的（比如有协作者的系统时间是错的，或者是故意伪造的时间）。

原文没有表达关于时间的信息的话，译文也不要有。last 不是 latest。

**Comment by oldsharp** [comment]
很好的点。

我的理解：
创作时间和提交时间，后者更接近 last commit 要表达的意思。但是正如之前所说，存在系统时间错误和故意伪造时间的可能。
但是有一点可以肯定：提交历史组成的 DAG ，其逻辑上的先后顺序是确定的（parent commit），和创作、提交时间无关。所以可以认为 last commit 明确指代的是逻辑上的最后提交。我们翻译时候可以适当考虑这点。

**Comment by OlingCat** [comment]
若无异议的话，二者译法采用“上一次提交”和“下一次提交”。

本问题将在 #391 完成后解决。

**Comment by OlingCat** [comment]
目前来看，last commit 的译法其实可以视上下文而定，有时“最后一次提交”更妥当些，毕竟它不是个专有名词。
