### ISSUE TITLE
建议 Index 在指代“三棵树”时保留不译

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#219]
在 `07-git-tools reset` 中，HEAD、Index 和工作目录经常同时提到，既然 HEAD 没有翻译，那么 Index 也应该不翻译。现在翻译成“索引”太过模糊，所以并没有提供有用的信息。

**Comment by networm** [comment]
我认为可以保留“Index”不译，但是还有一个“暂存区”这个要不要统一呢？

**Comment by robinwen** [comment]
我没有参与那个部分的翻译和审校，不是特别清楚上下文，所以可能说得不太对。

我反而觉得在这里Index可以翻译成"索引(Index)"这样的中英双语。"暂存区"也可以使用中英双语的方式翻译。我认为HEAD不翻译的原因是这4个大写字母连在一起时其实是git中的一个专有符号，而不再是类似index、stage这样的术语名词。对于术语，我们是可以翻译的，但是对于专有符号是可以保留原文不翻译的。
