### ISSUE TITLE
fork 和 pull request 怎么翻译？

### ISSUE THREAD

**Issue by devbean** [progit/progit2-zh#22]
有关 GitHub 的 fork 和 pull request 怎么翻译？大家给点意见？

**Comment by leo108** [comment]
根据 #14 ，pull保留英文，所以pull request根据不同语境可以翻译成 `pull请求`和`请求pull`

**Comment by mllyx** [comment]
我建议直接保留英文，因为这些单词都对应了git中的具体命令。
或者给定中文的同时，增加英文说明，例如：拉取(pull)、复刻(fork)

**Comment by tonghuix** [comment]
Pull翻译成“拉取”是合适的。
Fork建议翻译为“派生”

**Comment by devbean** [comment]
直接在 https://github.com/progit/progit2-zh/issues/45 讨论

**Comment by lhaotian** [comment]
pull 我在心里翻译成“拖走”。发送一个拖走请求，把没用的东西拖走，留下有用的

**Comment by MichaelCcccc** [comment]
> 学习一下
