### ISSUE TITLE
/book/05-distributed-git/images/managed-team-flow.png图片有误 & 提议适当修改示例中的人名

### ISSUE THREAD

**Issue by morefreeze** [progit/progit2-zh#220]
在[这里](https://github.com/progit/progit2-zh/pull/162/files#diff-3d3ace4ad381a11140fadb216dd1ceb9R480) 从前面知道John 与 Jessica 在特性A上工作，同时 Jessica 与 Josie 在特性B上工作，而且“但是一封来自 Josie 的邮件告知一些初始工作已经被推送到服务器上的 featureBee 上了。” 可以知道Josie是在B（或Bee）分支，已经和@networm确认图片原版也搞错了

另外提议：这里这么命名真有点自找麻烦，写成Alice Bob Candy会更好点，Alice, Bob分别对应AB两个分支，Candy则是同时参与两上分支的角色，这三个J的英文名让中国读者看起来特别容易弄晕（我在确认上面的错误就反复看了几次名字是否看错了）

**Comment by Geno1024** [comment]
Alice, Bob...这名字，赞同。

**Comment by OlingCat** [comment]
这个想法不错，给官方提个建议？

**Comment by oldsharp** [comment]
@morefreeze 可以去 https://github.com/progit/progit2 提一个 PR 试试？
或者如果上游不采纳，我们也可以考虑翻译时候改一下名字？
我有个顾虑的地方就是，Alice 和 Bob 一般是密码学资料里的人名，都快成专有名词了，这会不会有什么影响？（好像也没什么影响…）

**Comment by OlingCat** [comment]
呃..我在好多其它的书里也见过这三个名字。

**Comment by morefreeze** [comment]
@oldsharp 这个名字是啥可以让他们去想，我要不先去那边提个issue试试吧

**Comment by Geno1024** [comment]
@OlingCat 其实 Alice 和 Bob 的名字大有来历呢。

**Comment by OlingCat** [comment]
突然想起 Matrix67 的妻子这篇 [Alice 和Bob 的故事](http://localhost-8080.com/2014/02/story-of-alice-and-bob/)

**Comment by Geno1024** [comment]
@OlingCat https://en.wikipedia.org/wiki/Alice_and_Bob

**Comment by morefreeze** [comment]
https://github.com/progit/progit2/issues/357
吐槽英文你就输了

**Comment by networm** [comment]
@morefreeze 你那个标题可以短点儿吗？
