### ISSUE TITLE
backport 如何翻译？

### ISSUE THREAD

**Issue by secondwtq** [progit/progit2-zh#224]
出现在 [05-distributed-git maintaining](https://github.com/progit/progit2-zh/pull/136/files#diff-5814a68fe8bb0a97847f30d019e88b9bL338) 和 [07-git-tools advanced-merging](https://github.com/progit/progit2-zh/pull/169/files#diff-3164721915dedfeab08945973dfc0042L622) 中。

貌似 `向后移植` 比较多一些（[Wikipedia](https://zh.wikipedia.org/wiki/%E5%90%91%E5%BE%8C%E7%A7%BB%E6%A4%8D)），其他的 `反向移植`，`相反移植` 感觉不够直白。

**Comment by jeffsui** [comment]
我结合上下文认为 翻译为重新合并到 跟贴切一些。

**Comment by networm** [comment]
@oldsharp @robinwen 你们看看这个如何翻译？

**Comment by archersmind** [comment]
>Backporting is the action of taking parts from a newer version of a software system or software component and porting it to an older version of the same software.

Wikipedia 上是这么解释的，意思是`把新版本上的东西移植到老版本上去`，那么翻译成`向后移植`我认为是没有问题的。

因为，比较新的版本或者提交是在前面的（设想用`gitk`/`git log`查看提交历史的情形）。

**另外**，我们可以加个括号，括号内写：
（译者注：原文是 ....）

**Comment by secondwtq** [comment]
@jeffsui 关于这个我有两个认识：

* `backport` 属于一个`专有名词`。
* 这个 `backport` 和其他的 `port` 之类所不同的地方在于，其是把新版本中的一些东西移植到老版本中，这层意思在翻译中应有所体现。

**Comment by oldsharp** [comment]
05-distributed-git maintaining
```
and `maint` for maintenance backports
和用于维护性向后移植工作（maintenance backports）的 `maint` 分支
```

07-git-tools advanced-merging 
```
In the meantime some bugfix on ``master'' needs to be backported into your `release` branch.
与此同时 ``master'' 分支上的某些 bugfix 需要向后移植回 `release` 分支。
```
