### ISSUE TITLE
git-scm.com上的url地址还是第一版的

### ISSUE THREAD

**Issue by wwek** [progit/progit2-zh#23]
当访问http://git-scm.com/book
点击左边不同语言的导航
点击简体中文
http://git-scm.com/book/zh
发现会重定向到
http://git-scm.com/book/zh/v1
需要手动改为
http://git-scm.com/book/zh/v2 才可以看到第二版。

我懒一下这里发个issues。 作者联系官网改下。

**Comment by wwek** [comment]
奥看了下。还没翻译完呢·

**Comment by networm** [comment]
@wwek 等待中文版全部翻译完成后会更新此链接，因为不能让大家阅读翻译了一半的书籍啊。
