### ISSUE TITLE
关于 work on 的灵活译法

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#231]
大家先看一下[例句](http://www.iciba.com/work_on)，然后再想想 work on the code 有没有更好的译法？
个人想直接译作“编写代码”应该可以。
比如[这句](https://github.com/progit/progit2-zh/pull/171/files#diff-f54f755ad1f12a241ca1a8263c0af189R357)可以译作：
“你很有可能正在使用子模块，因为你确实想在子模块中编写代码，同时还想在主项目上编写代码（或者跨子模块工作）。”

**Comment by networm** [comment]
虽然 work on code 可能不光是指编写，也有可能是查错、删除、审核之类的，但出于简洁性的考虑，“编写代码”就足够了。

**Comment by OlingCat** [comment]
@networm 呃..其实查、删、审其实都属于“编”的范畴....
