### ISSUE TITLE
Pull request 翻译问题

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#234]
Pull Request 现在可以有三种译法：
1. 直译，“拉取请求”
2. 意译，“合并请求”
3. 不译，"Pull Request"

我认为 Pull Request 是 GitHub 创造的一个专有功能，是非常特别的！GitHub 还为此保存了第一台写出 Pull Request 功能的笔记本，这个功能可以说是一个划时代的功能，极大地促进了开源软件的交流。
所以我个人倾向于不译或是直译，不知道大家有什么看法？

**最终候选决定：选择使用“拉取请求”，在首次出现时会加上原来的英文“Pull Request”、缩写“PR”、其他的用法如“合并请求”。而且还会用一个简短的文字介绍一下这个功能，如：拉取请求意为请求对方从自己这里拉取。**

请大家尽量提出问题，此 Issue 截止时间为 20150815 2400 +0800。

![Pull request notebook](http://static.inside.com.tw/wp-content/uploads/2014/03/25.jpg)
▲ 寫出「Pull Requests」的電腦，據說當時已經舊到會「電」人了 XD

[舊金山現場] 拜訪章魚貓的家：GitHub 總部 3.0 - Inside 硬塞的網路趨勢觀察
http://www.inside.com.tw/2014/03/13/github-hq-3

**Comment by Geno1024** [comment]
先挑一下错别字然后走人 ._.
GitHub 还`为`此

**Comment by IceNature** [comment]
合并请求，我觉得已经习惯了，大家到知道说的是什么
突然换成 `拉取请求` 反而会让人觉得有点怪

**Comment by OlingCat** [comment]
个人论点：
直译“拉取请求”就是发送一个请求让对方来从我这里拉取然后合并的意思；
意译“合并请求”就是发送一个让对方合并的请求，就是合并请求。
如果直译成“拉取请求”，那么请求从对方那边拉取还是请求对方从我这边拉取后合并？
而且实际上对方不用拉取，看着没问题就合并了，所以最终动作还是合并。

**Comment by sanddudu** [comment]
我比较同意 @OlingCat 的意见

**Comment by networm** [comment]
> Merging via command line
> 
> If you do not want to use the merge button or an automatic merge cannot be performed, you can perform a manual merge on the command line.
> 
> Step 1: From your project repository, check out a new branch and test the changes.
> 
> git checkout -b networm-09-git-and-other-scms_client-tfs master
> git pull https://github.com/networm/progit2-zh.git 09-git-and-other-scms_client-tfs
> 
> Step 2: Merge the changes and update on GitHub.
> 
> git checkout master
> git merge --no-ff networm-09-git-and-other-scms_client-tfs
> git push origin master

以上是手动合并一个 Pull Request 所要进行的步骤，可以看到，第一步中的第二个命令就是要从 Pull Request 的创建者的仓库中拉取数据，由此我认为，翻译为“拉取请求”最为合理，抑或者不译。

而合并这个最后都会进行的操作，我认为完全没有必要，因为只要两个历史分叉了，要到一起就必然有合并，而这儿并不是 GitHub 上协作的核心。

**Comment by M1seRy** [comment]
貌似Pull Request翻译成合并请求的比较多吧！

**Comment by networm** [comment]
我们这里讨论的时候不要以哪个用的多为准，而是以正确的为准！

**Comment by networm** [comment]
git pull = git fetch + git merge
git merge = git merge

也就是说拉取本身已经包含了合并的意思，所以这里翻译为“拉取请求”是再贴切不过！

**Comment by OlingCat** [comment]
呃.. @networm 的论点有点儿说服我了。
不过很多时候的中文并不是以“仔细推敲后发现正确”来读，而是以“我看上去是这么理解的”而读的。如果一个词虽然翻译得不好但是很多人都已经接受了，那么重新修改后即便正确也是不大得人心的。

**Comment by OlingCat** [comment]
啊，我收回以上观点。这本书的重要性不言而喻，如果我们能就此确立标准把以前的译法纠正过来的话，再好不过了。比如以前的 rebase 从“衍合”改成了“变基”。

**Comment by M1seRy** [comment]
现在一些论坛博客这个词直接就不翻了，存在即合理吧！我记得以前Google 的MapReduce怎么翻都不太理想，现在基本就直接用这个单词了！

**Comment by networm** [comment]
@OlingCat 我刚才用 Google 分别搜索了一下"拉取请求"与"合并请求"，发现"合并请求"中大部分并不是与 Git 相关，反而是"拉取请求"与 Git 相关的多一些。这反而说明"拉取请求"更受欢迎一些！
而"合并请求"对一个从来没用过 Git 的人，或者是并不了解 Git 的人，很难联想到是"Pull Request"，而是"Merge Request"，等他们真正到网站上看的时候，发现根据自己的理解根本没找到对应的功能！

我认为从各方面来说"拉取请求"都是一个最合适的选择，其次是不译，最次才是"合并请求"。

**Comment by OlingCat** [comment]
@networm 拉取并不包含合并的意思啊，merge 指的不同分支上吧？同一个分支上的叫fast-forward

**Comment by networm** [comment]
@OlingCat git pull 本身就有抓取后并合并的功能，所以这里才认为拉取=抓取+合并。

其次，同一个分支合并只不过默认的行为是 fast-forward，其实合并的时候也可以指定 git merge --no-ff 来生成一个合并提交的，参见我上面的例子：Step 2 的第二行命令 `git merge --no-ff networm-09-git-and-other-scms_client-tfs`

**Comment by liangpengfei** [comment]
这种东西，感觉并不用翻译啊。。。如果硬是要翻译的话，“合并请求”更好一些吧

**Comment by networm** [comment]
> home — Bitbucket
> https://bitbucket.org/dashboard/pullrequests

Bitbucket 中文翻译也是使用的"拉取请求"。

**Comment by OlingCat** [comment]
@networm 那么我们在首次译作“拉取请求”时译注一下“拉取请求意为向对方发送请求来拉取自己的更改”如何？因为“向某人发送一个拉取请求”在中文语境中的意思一般是“我向你请求一个我要拉取的权限”。

**Comment by Geno1024** [comment]
@skyleft :
>非要直译的话，还不如译为 请求拉取

**Comment by networm** [comment]
英文版的 ProGit v2 中使用的是两个大写名词"Pull Request" [progit2/2-contributing.asc at master · progit/progit2](https://github.com/progit/progit2/blob/master/book/06-github/sections/2-contributing.asc)，应该是把 Pull Request 当作一个专有名词使用了，所以我觉得应该不译。

**Comment by sanddudu** [comment]
我认为这个词出现的主要原因是 Github 上的贡献流程主要是 fork 为主，而之前通常都是使用不同的分支进行工作，在接受修改的时候就只需要进行合并（merge），而 fork 出现后，需要从不同的项目进行拉取（pull）

**Comment by OlingCat** [comment]
好吧我现在倾向于“拉取请求”了。

**Comment by Geno1024** [comment]
@Hilovaiserillis：
>拉取请求……
吧

@yylzl：
>不译

@skyleft：
>非要直译的话，还不如译为 请求拉取

@慕瑾：
>对 英文语序都是反的

@sndnvaps：
>请跟我说，PR

**Comment by oldsharp** [comment]
不译我个人不太赞同。
作为名词，“XX请求”的形式比较合理。
我会选择“拉取请求”，作为 Pull Request 的正式翻译，体现与 Merge Request 的区分。

**Comment by networm** [comment]
GitLab 中的 Merge Request 为什么叫这个，我说明一下：GitHub 中想要为一个项目贡献，必须先 Fork 一份自己的仓库，在这个仓库开分支弄新内容，然后发送一个 Pull Request，请求项目维护者过来 git pull 拿走内容；而 GitLab 中是同一个仓库下，在一个新分支做了一些内容，向团队中的其他人发送一个 Merge Request，其他人审校通过后合到请求合并的分支，所以这里叫 Merge Request。

综上所述，GitLab 并未新造一个词，只不过是应用环境有所不同。

**Comment by OlingCat** [comment]
我们就叫它 PR 好了，书里初次出现这个词时，用语句解释一下，然后说“拉取请求”和“合并请求”都是出现过的译法，一如 rebase 曾经的译法是“衍合”。

**Comment by Geno1024** [comment]
@OlingCat 提醒了我，我们不是有“曾用名”的说法吗！？

**Comment by archersmind** [comment]
@OlingCat 我同意你加译注的做法。至于 `Pull Request`到底怎么翻译，我现在也有点糊涂，我起初的直觉是`合并请求`可能更好一点。

我也同意 @networm 的观点 `pull = fetch + request`，但是试想一下，如果一个初学者，从网上google Github 的相关内容的时候，发现了我们这本书的某一节（并不是包含第一次出现Pull request而有译注的那一节哦），这个时候他读到了`拉取请求`，他如何能联想到这个词的意思是，请求别人 merge 修改啊？

如果我是初学者，当第一看到 `拉取请求`的时候，我一定会糊涂（拉取？怎么拉？他拉我还是我拉他？），等我看到对应的英文`Pull Request`的时候，我依旧不明其理（因为我连中文都没看明白，怎么会知道原文的意思呢？）。

**但是**，如果我先看到中文`合并请求`，再看到英文`Pull request` 我立刻就明白 PR的意思是，请求别人合并我的修改。所以说，使用`合并请求`能首先使读者通过比较直白的中文意思而产生一个先觉印象，当再看到英文的时候，就能做一个很清楚的联系了。

综上，我支持`合并请求`。

谢谢

**Comment by archersmind** [comment]
大家的观点都有道理，陈述完观点之后，不如投票吧？

**Comment by M1seRy** [comment]
多在这凉几天吧！结果就出来了！

**Comment by networm** [comment]
我怕在这儿凉多少天都没结果，这个项目的关注度可不高！

**Comment by OlingCat** [comment]
@archersmind  对啊！我已开始就是说的这个问题，到底是谁拉，然而大家都无视咱的担忧= =||
所以就如同大家第一次看到“句柄”和“套接字”时的困惑。不过我想了想，“句柄”和“套接字”这两个名词刚出现时因为译者没有对它做充分的解释，所以才导致一大堆困惑。
所以我就提议第一次出现这个翻译的时候译作“拉取请求”，然后译注解释清楚是“请求对方从自己这里拉取”。

**Comment by OlingCat** [comment]
格式可以这样：

第一次出现这个词的正文：
....什么什么什么拉取请求⑨如何如何....

页脚：
⑨Pull Request，即拉取请求，偶见译作“合并请求”，程序员一般常以缩写“PR”指代。

**Comment by skyleft** [comment]
@Geno1024 完全是由实际场景来的，不过对于翻译这事，何不直接保留Pull Request呢

**Comment by OlingCat** [comment]
不知道大家看过“设计心理学”没有，很多专业设计者看起来非常合理的设计，用户经常会不知道是做什么的。所以，我们应该挑一个最直观理解的译法，而不是最描述接近本质的译法。而且，同样四个字，并不能容纳太多信息，如果只是指代，我倾向于和 PR 逐词对应的译法，即“拉取请求”。即便它仔细推敲后不如“合并请求”来的贴切，也不大符合中文语法，但加上解释后，对于初读者来说，这是最直观的。

**Comment by sanddudu** [comment]
@OlingCat 这个注释可以直接通过超链接跳转吗... 如果不行，我觉得非常不友好
另外个人认为拉取才是最接近本质，合并才是最直观理解...

**Comment by OlingCat** [comment]
@sanddudu  要看对什么直观了，“拉取请求”对英文和搜索是直观的，这两点也应该考虑进来。而且假如读者对“合并”也没有透彻的理解，那么对于他们来说，这个新词就无关紧要了。

**Comment by sndnvaps** [comment]
还不如直接不翻译吧。 
或者翻译为 `合并请求`
简写为 `PR`

**Comment by networm** [comment]
@sanddudu PDF 和网页中都可以跳转 EPUB MOBI 应该也可以。

**Comment by networm** [comment]
@sanddudu 纸质的不行。

**Comment by networm** [comment]
@archersmind 我不赞同从中间看还能理解东西的做法，任何一个东西都是从前往后学习的，一个没学过“套接字”的人从中间看书的，估计他很难看懂，难道说因为需要照顾这样的人，每一个地方都加上注释？每一个地方都用长篇大论讲述细节？书设计的时候就是假定你看完前面的，后面就不用再讲了，最起码也应该从那章开始，而不是那章的中间开始。

**Comment by Geno1024** [comment]
看了群里的讨论，瞬间觉得，这和这本书的定位有关系了。
我们希望它成为一本什么呢？
是想让别人想到一个什么问题，可以随时翻阅其中的具体某一章节；
还是想把它成为一本课本，可以从头学到尾，学完扔了，需要的时候再重新整本书复习一遍？
毕竟词典里不教字母的写法。

**Comment by networm** [comment]
@Geno1024 我认为就算是字典，也没办法做到随意打开一章节就能了解全部内容，也会在解释中遇到不理解的，然后跳到另一个地方寻求解释。
比如 Git 分支 这一章，如果这个人上来直接看 远程分支 这一小节，请问他能理解吗？在不看 分支的简介 这一小节的基础上？本质上，要求读者看书的时候要有一些基本概念，而基本概念最少也得从本章开始。

**Comment by networm** [comment]
最终决定：选择使用“拉取请求”，在首次出现时会加上原来的英文“Pull Request”、缩写“PR”、其他的用法如“合并请求”。而且还会用一个简短的文字介绍一下这个功能，如：拉取请求意为请求对方从自己这里拉取。

请大家尽量提出问题，此 Issue 截止时间为 20150815 2400 +0800。

**Comment by archersmind** [comment]
>不知道大家看过“设计心理学”没有，很多专业设计者看起来非常合理的设计，用户经常会不知道是做什么的。所以，我们应该挑一个最直观理解的译法，而不是最描述接近本质的译法。而且，同样四个字，并不能容纳太多信息，如果只是指代，我倾向于和 PR 逐词对应的译法，即“拉取请求”。即便它仔细推敲后不如“合并请求”来的贴切，也不大符合中文语法，但加上解释后，对于初读者来说，这是最直观的。

@OlingCat 其实不止是设计师，程序员也常常被`冤枉`，可能给出一个让读者容易接受的译法更加重要。

>最终候选决定：选择使用“拉取请求”，在首次出现时会加上原来的英文“Pull Request”、缩写“PR”、其他的用法如“合并请求”。而且还会用一个简短的文字介绍一下这个功能，如：拉取请求意为请求对方从自己这里拉取。

@networm 既然已经决定了`拉取请求`的译法，那么对于现存的`合并请求`的译法怎么处理呢？是择机一起重新改过吗？

**Comment by networm** [comment]
@archersmind 今晚24：00前如果没有异议的话就会采用这个意见，现在的`合并请求`会在所有章节都合并到主干后处理。

**Comment by yulincoder** [comment]
依老夫之见，不如译为“请求拉取”
