### ISSUE TITLE
system-wide翻译问题

### ISSUE THREAD

**Issue by jeffsui** [progit/progit2-zh#236]
-_`PREFIX`_ is similar, but for the system-wide configuration.
-  Git looks for this file at `$PREFIX/etc/gitconfig`.
  +_`PREFIX`_ 也类似，除了用于系统范围配置。

我个人理解此处应该体现出环境的特点,不同的配置影响不同的作用范围,所以 翻译成 系统级别 更贴切。

**Comment by sanddudu** [comment]
同意

**Comment by networm** [comment]
同意

**Comment by OlingCat** [comment]
同意

**Comment by lilydjwg** [comment]
同意

**Comment by liuxilu** [comment]
已经被改过来了。关issue @networm

**Comment by networm** [comment]
Closed by #382
