### ISSUE TITLE
版本计划

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#239]
简要列一下未来的版本计划，其中的日期为截止时间。
- 2.0.0 20150816 审校协作计划完成，所有章节合并入主干。
- 2.1.0 20150818 内容更新至英文最新版。
- 2.2.0 统一全书术语，见 [WIKI](https://github.com/progit/progit2-zh/wiki/Unify)。
- 2.3.0 全书由三人小组负责风格统一。

大家有什么想法都可以提出来，欢迎在此讨论！

**Comment by networm** [comment]
1.2.0 与 1.3.0 的时间并不是非常确定，有可能需要提前。

**Comment by YueLinHo** [comment]
我大概看了 Log，覺得與英文同步的方式似乎不太好追蹤！？
請問，與英文同步的具體做法是?

**Comment by oldsharp** [comment]
On Tue, 26 Jan 2016, Yue Lin Ho wrote:

> 我大概看了 Log，覺得與英文同步的方式似乎不太好追蹤！？
> 請問，與英文同步的具體做法是?

之前的做法是，在某个时间点，针对上游的某个特定提交做一次 catch-up。
据我所知，类似这样的同步目前只做了一次，就是 tag v2.1.0。

**Comment by YueLinHo** [comment]
但是在 tag v2.1.0 之後合併了 PR #265，它看起來也是一個 sync (合併點: d8327367923dab4cded6f9d9b81adf59bde5c418)，距離 tag v2.1.0 有 20 個 commits(如下圖)

![image](https://cloud.githubusercontent.com/assets/5831804/12603097/82b949a2-c4ea-11e5-9ca8-e98b512943f9.png)

**Comment by YueLinHo** [comment]
查看 PR #265 的 `Files Changed` 後才發現不是 :sweat_smile:

**Comment by oldsharp** [comment]
On Tue, 26 Jan 2016, Yue Lin Ho wrote:

> 查看 PR #265 的 `Files Changed` 後才發現不是 :sweat_smile: 

;-)

**Comment by YueLinHo** [comment]
請問，是否考慮用 merge 的方式來做 sync?

**Comment by oldsharp** [comment]
On Tue, 26 Jan 2016, Yue Lin Ho wrote:

> 請問，是否考慮用 merge 的方式來做 sync?

是指接受 Pull Requests 吗？

**Comment by YueLinHo** [comment]
像這樣:

![image](https://cloud.githubusercontent.com/assets/5831804/12604842/445b864c-c4fa-11e5-8ce9-33f1304c0b25.png)

把英文版的 commit 合併到一個 sync 分支(圖中示例是 tw_sync_test)，如果中文已完全翻譯，合併時便會產生衝突，這個衝突其實是幫忙指出英文版有修改的地方，然後針對有衝突的地方檢查是否需要更新翻譯內容。(不過，有個小前提，英文版和中文版的行號最好對齊，解衝突時比較容易解。)

(我在尋求有沒有更好的方式...)

**Comment by YueLinHo** [comment]
也可以考慮用 rebase --preseve-merge 把個中文版 master rebase 到英文版 master 上頭，然後一樣解衝突。(不過，我還沒試過... :smile: )

**Comment by networm** [comment]
v2.1.0 同步英文版的方式如下：
找到中文版本的英文基础版本，比较英文最新版本与基础版本间的差异，根据差异修改中文版本。

**Comment by networm** [comment]
版本计划中止
