### ISSUE TITLE
fork 译作“派生”如何？

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#240]
以前不记得从哪见过这个译法，个人觉得不错，于是想听听各位的意见。

**Comment by networm** [comment]
https://github.com/jiangxin/git/pull/6/files#diff-464912b277c8ce74ecad8c785c503facR55

现在的建议是用派生，复刻，但我建议去除复刻。

**Comment by oldsharp** [comment]
我当时的想法是这样的：“派生”用在 Git 内部的分支 fork 操作；“复刻”用在 GitHub 等托管平台的仓库 fork 操作。所以才把两个翻译都加了上去，由译者根据场景决定使用哪一个翻译。

私货：“复刻”这个译法是我从[这里](http://rime.im/)看到的，一直难以忘怀，私以为，音译+意译，完美。可能是我对中州韵项目比较有好感吧 ;-)

**Comment by networm** [comment]
“复刻”这个译法我认为用在 GitHub 中是不合适的，因为 Fork 之后实际上你的项目与源项目间有一个关系，这个关系甚至可以继承下来，如 C->B->A，A是最初的项目，B Fork A，C Fork B，在 Graphics > Members 如 https://github.com/progit/progit2-zh/network/members 可以看到所有的继承关系，所以我建议使用“派生”。

**Comment by sanddudu** [comment]
为什么翻译对照表的存在感这么弱...
fork ⇒ [派生] (或根据上下文保留原文不翻译)

**Comment by networm** [comment]
@sanddudu 因为现在在决定翻译对照表中的条目应该翻译成什么。

**Comment by taichunmin** [comment]
目前台灣也在決定翻譯對照表，請見 <https://nchueecsec.hackpad.com/Git-Pro-2-hdsV2m1i7ab>

**Comment by Geno1024** [comment]
@taichunmin 专业词汇，特别是计算机方面的，简体中文地区的翻译和繁體中文地區的翻译差别好大 ._.有时候还可以细细品味一番繁體中文地區的翻译，感觉总有新发现 ._.

**Comment by Geno1024** [comment]
@taichunmin 看了一下你们对 rebase 的讨论，嗯，之前用的是衍合，后来某个 commit 把它们全部改为变基，后来貌似还有一次讨论，最终还是用了“变基”。
看到 repository，忽然想到一个词，仓储式存储（查了一下貌似是我臆造出来的一个词，不过“仓储式”貌似也是一个前缀了）。
Pull 中那个“突然想乱一下”，#234 也有过一个类似的说法 233
评论第 34 条下“CT”的第三次出现中提到“不過我看現在台灣用語越來越大陸化的趨勢”，啊？
看完了，过一会去你们那里评论 233

哦对啦这边的 233 相当于你们那边的 XD，2333 对应 XDD，23333 对应 XDDD，同理可推。

**Comment by taichunmin** [comment]
@Geno1024 感覺要決定翻譯詞真的是頗麻煩
有空倒是可以互相交流 :smile: 

沒去過中國大陸，也沒有什麼中國朋友，所以對 233 真的是第一次看到，哈。

**Comment by networm** [comment]
我们是不是也应该弄一个像繁体中文那样的文档，每一个词大家都可以评论，现在的结果是如果确定一个词如何翻译后，对应的 Issue 会关闭，其他人并不能追溯其相关的讨论。

**Comment by taichunmin** [comment]
在台灣這邊，是決定在 hackpad 上面討論，然後等書快翻譯完的時候，會把這個翻譯表加到書裡面當作附件。

**Comment by archersmind** [comment]
@taichunmin 中文简体的翻译对照表是我整理的，当时参考了台湾团队的成果，当时我记得好像有发邮件知会你，不知道你有没有收到。再次感谢你们的帮助，thanks

**Comment by archersmind** [comment]
@networm 当时我也是想学习台湾团队做hackpad，但是我hackpad好像被bolck了。

**Comment by taichunmin** [comment]
@archersmind 雖然說沒有收到信，大概是被擋了吧。 但是開源的東西就是歡迎使用 :smile: 

話說簡體的翻譯怎麼突然進度飆升阿?  是突然有一大堆人參與嗎?  還是有什麼特殊的技巧之類的呢?

**Comment by Geno1024** [comment]
@taichunmin 我们只是写了一个 #192 而已。

**Comment by archersmind** [comment]
@taichunmin 这个就要归功与 @networm 啦。他加入之后积极推动进度，对于已经认领任务而有“消失”的人，果断“开除”他们，然后 @networm 还在国内各个论坛加大宣传力度，邀请了很多同好。最最重要的是，他近乎7x24 在线，任何讯息他都会在很快的时间给予回复。具体的你可以私底下和他交流。

**Comment by networm** [comment]
@taichunmin 从5月份开始就已经招募人员翻译了，但是只提了 PR 并没有合并。6月份进入审校阶段，每一个章节要求至少三人审校，直到昨天才全部审校完。但是 status.json 里的进度并没有更新，昨晚才更新，所以会发现进度突然就到100%了。

**Comment by sanddudu** [comment]
@taichunmin 你可以简单的理解成把一个 meme 扔到 ptt 上面之后的回帖数增加速度 XD

**Comment by sanddudu** [comment]
@taichunmin 不过 ptt 吹水打炮的人会比较多，虽然也有大学的板块
我也不太了解台湾有什么比较大的技术社区（因为我都是泡 komica 之类的地方 XD）

**Comment by taichunmin** [comment]
原來是這樣，感謝告知。  看來繁體中文還有好長一段路阿，一起加油。 :smile:
