### ISSUE TITLE
英文版同步计划

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#245]
v2.0.0 在翻译时是基于当时刚开简体中文仓库的版本 881cf5ff40dba7ae8337311ee44c52c97c4b94a5 进行翻译的。
现在，v2.0.0 已经完成，v2.1.0 的主要任务就是与英文版 20150813 090501 -0700 6390e50270cd04a3b67f9312fde5dca3ccf78cce 同步。

建议查看差异方法：克隆两份官方仓库，A 检出到 6390e502，B 检出到 881cf5ff，使用 Beyond Compare 或类似的比较软件进行文件夹对比，找到差异再手动地转移到中文版对应的文件中，然后进行翻译。

由于英文版最近一年更新的内容并不是非常多，所以任务不按小节分，而是按章分。截止时间 20150818 180000 +0800。
要求：所有提交信息参考 https://github.com/progit/progit2-zh/pull/246/commits 以“Sync”开头，后接章名、节名，中间用空格分隔。
PR 的名字为 “Sync”加章名，空格分隔。

**20150818 18:16:00 全部同步完成**

进度表：
 - [x] [others](https://github.com/progit/progit2-zh/pull/251) @networm 20150818
 - [x] [01-introduction](https://github.com/progit/progit2-zh/pull/248) @sanddudu 20150817
 - [x] [02-git-basics](https://github.com/progit/progit2-zh/pull/249) @sanddudu 20150817
 - [x] [03-git-branching](https://github.com/progit/progit2-zh/pull/260) @networm 20150818
 - [x] [04-git-server](https://github.com/progit/progit2-zh/pull/252) @networm 20150818
 - [x] [05-distributed-git](https://github.com/progit/progit2-zh/pull/254) @networm 20150818
 - [x] [06-github](https://github.com/progit/progit2-zh/pull/259) @networm 20150818
 - [x] [07-git-tools](https://github.com/progit/progit2-zh/pull/257) @archersmind 20150818
 - [x] [08-customizing-git](https://github.com/progit/progit2-zh/pull/255) @IceNature 20150818
 - [x] [09-git-and-other-scms](https://github.com/progit/progit2-zh/pull/250) @networm 20150820
 - [x] [10-git-internals](https://github.com/progit/progit2-zh/pull/258) @branchzero 20150818
 - [x] [A-git-in-other-environments](https://github.com/progit/progit2-zh/pull/246) @IceNature 20150817
 - [x] [B-embedding-git](https://github.com/progit/progit2-zh/pull/256) @IceNature 20150818
 - [x] [C-git-commands](https://github.com/progit/progit2-zh/pull/247) @IceNature 20150817

**Comment by IceNature** [comment]
认领 A-git-in-other-environments

**Comment by Geno1024** [comment]
认领 B-embedding-git

**Comment by IceNature** [comment]
好吧我又来了……
认领 C-git-commands

**Comment by sanddudu** [comment]
认领 01-introduction

**Comment by sanddudu** [comment]
认领 02-git-basics

**Comment by sanddudu** [comment]
认领 03-git-branching

**Comment by archersmind** [comment]
我来一个 06-github

**Comment by IceNature** [comment]
认领 08-customizing-git

**Comment by Geno1024** [comment]
时间不允许，取消认领。

**Comment by branchzero** [comment]
10-git-internals 认领

**Comment by IceNature** [comment]
B-embedding-git 认领

**Comment by archersmind** [comment]
BUG BUG
https://github.com/progit/progit2-zh/blob/master/book/07-git-tools/sections/subtree-merges.asc

这后半段都没翻译，怎么merge进去了？

**Comment by archersmind** [comment]
@leo108 太不负责任了吧？

**Comment by leo108** [comment]
@archersmind 之前一直是翻译一点合一点的，没说非得全部翻完才merge，最近一阵公司事情比较多，没有跟上翻译进度，非常抱歉

**Comment by archersmind** [comment]
@leo108 好吧，我来补齐，上下文没看，可能质量不高，到时候请你review下吧。

**Comment by archersmind** [comment]
@networm 07-git-tool sync 完毕。

**Comment by networm** [comment]
与英文版已全部同步完成！
