### ISSUE TITLE
“bare repository”翻译问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#261]
我们项目目前翻译为“裸仓库”。
Git 中文本地化项目翻译为“纯仓库”。
需要在这两个中间选择一个。

**Comment by networm** [comment]
“裸仓库”较能清晰地反应出仓库的状态——没有工作目录。所有我建议使用“裸仓库”。

**Comment by oldsharp** [comment]
我觉得“纯仓库”也能反映没有工作区、索引的状态，取其纯粹、纯净之意。
其实这两个我有点纠结，只能说稍微偏向“纯”仓库吧。
“裸”仓库因为第一版 progit 的翻译先入为主，可能暂时让我觉得更习惯些。但是仔细考虑，觉得“纯”好像更好。

**Comment by sanddudu** [comment]
洁净呢？

**Comment by oldsharp** [comment]
@sanddudu 是指翻译成“洁净仓库”吗？还是说“纯”会和 clean 冲突？

**Comment by jeffsui** [comment]
bare repository  我建议使用“裸仓库”。

**Comment by oldsharp** [comment]
下午趁有空时候查了下《Git 权威指南》，发现这里面“bare repository”用的也是“裸”仓库😰
![bare-repo](https://cloud.githubusercontent.com/assets/980500/9351967/18bd5ddc-4690-11e5-9191-a44e477ff3e7.png)
不知在 Git 中文本地化项目中改为“纯”仓库，是否有什么特殊原因。可能我需要与 @jiangxin 沟通一下。

**Comment by oldsharp** [comment]
Jiangxin 认为“纯仓库”的用法在 tortoise git 中出现，并认为比“裸仓库”更文雅。所以选择使用“纯”。具体见：https://groups.google.com/forum/#!msg/gotgit/x6w2rlZ4xrc/S-R6IeBbFQAJ 。

所以 Git 中文本地化项目会继续使用“纯仓库”的译法。

至于在 progit2-zh 项目中选择哪个，大家可以给出各自的结论。如果大多意见认为“裸仓库”更适合，我会在 #265 中作相应修改。否则改为使用“纯仓库”。

**Comment by oldsharp** [comment]
#265 已经合并，目前采用了“纯仓库”的译法。
