### ISSUE TITLE
“submodule”翻译问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#262]
我们项目目前翻译为“子模块”。
Git 中文本地化项目翻译为“子模组”。
需要在这两个中间选择一个。

**Comment by networm** [comment]
翻译成”子模组“是有什么特别的原因吗？

**Comment by networm** [comment]
简体的叫法多用“模块”吧，繁体多用这种“模组”吧？

**Comment by oldsharp** [comment]
@networm 应该没有特别的原因，我也不是很清楚。

**Comment by networm** [comment]
我认为这种译法应该充分考虑简体中文的习惯，所以我建议使用“子模块”。“模块”也是国内的技术书常用的词。

**Comment by oldsharp** [comment]
@networm 嗯，的确，比如 kernel module，大陆这边的说法一般是“内核模块”，港台的说法一般是“内核模组”。

**Comment by oldsharp** [comment]
港台的说法好像是“核心模组”。

**Comment by networm** [comment]
模组，国内是不用的。。。

**Comment by jeffsui** [comment]
I suggest “子模块”。

**Comment by oldsharp** [comment]
@networm 我知道为什么 Git 中文本地化那边翻译为“子模组”了，因为刚《Git 权威指南》里面用的就是“子模组”。
不过我认为“子模块”更适合简体中文环境下使用。这里的讨论结果也是如此。那么我们项目就用“子模块”了。
我可以尝试把那边也统一过来。

**Comment by archersmind** [comment]
`模组` 应该是繁体里面用的比较多。对应的，简体里面说`模块化` 繁体中文里说`模組化`

**Comment by oldsharp** [comment]
@archersmind yep 😉

**Comment by oldsharp** [comment]
Jiangxin 认为“模组”从原文“module”角度而言，比“模块”更精妙。所以 Git 中文本地化会继续使用“模组”译法。

如果各位认为没有必要和 Git 中文本地化项目保持统一，那么 progit2-zh 项目会继续使用“模块”。
