### ISSUE TITLE
“commit message”翻译问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#263]
目前的翻译是“提交信息”，但是这样的话“commit information”（指与某个特定提交相关的信息，包括 commit message、commit author、commit date、parent 等）应该如何翻译？

因此我提议将“commit message”译作“提交说明”。

**Comment by OlingCat** [comment]
但是提交信息似乎已经约定俗成了，不如退一步改 commit information 的译法吧？

**Comment by oldsharp** [comment]
@OlingCat 但是我发现 commit info 确实很难再找到比较简练的译法😰
之前我遇到要翻译 commit info 的情况，为了避免困惑，只能处理成类似“与某某提交相关的信息”这种比较冗长的妥协译法，因为黄金译法已经被 commit msg 给占了😅

**Comment by OlingCat** [comment]
info 译作 “提交数据”、“提交资料”呢？
呃...看来只好改 msg 了= =||

**Comment by networm** [comment]
“提交信息”使用地实在是太过广泛了，很多软件、书籍都用这个，就像 iOS 系统，短信应用英文是 messages 中文是 信息，还是建议使用“提交信息”，修改其他部分。

**Comment by oldsharp** [comment]
@networm 不过考虑到《progit》的影响力，我们如果确认有更适合的译法，说不定可以借此把习惯用法扭转过来😉

**Comment by networm** [comment]
关键有一点，在我刚开始用VCS的时候，直觉就管这个东西叫“提交信息”。

**Comment by oldsharp** [comment]
提交说明 http://drinking.github.io/blog/2015/03/14/how-to-write-commit/

提交消息 http://www.ibm.com/developerworks/cn/linux/l-git/index.html

**Comment by jeffsui** [comment]
“提交信息"

**Comment by oldsharp** [comment]
刚才花时间查找了一下网络上的相关资料，除了我之前列出的质量较高的引用之外，发现 @ruanyf 阮一峰老师的一篇 blog [《Git 使用规范流程》](http://www.ruanyifeng.com/blog/2015/08/git-use-process.html) 中使用了“提交信息”：

![commit-msg-03](https://cloud.githubusercontent.com/assets/980500/9352201/eddc6de0-4691-11e5-9ad5-9ef7b982b210.png)

另外，[《Git 简明指南》](http://rogerdudler.github.io/git-guide/index.zh.html)也使用了“提交信息”的说法：

![commit-msg-04](https://cloud.githubusercontent.com/assets/980500/9352245/58253740-4692-11e5-9ada-35faac79858b.png)

不过《Git 权威指南》中使用的是“提交说明”：

![commit-msg-01](https://cloud.githubusercontent.com/assets/980500/9352289/b5229d98-4692-11e5-8d6b-b73bde607806.png)
![commit-msg-02](https://cloud.githubusercontent.com/assets/980500/9352292/bb76fc52-4692-11e5-95c6-1badef68f4d0.png)

我感觉关于“commit message”目前并没有一个统一确定的译法？
我个人仍然认为“提交说明”是更优的选择。

**Comment by archersmind** [comment]
@oldsharp 确实 **好像** 比较优，改或者不改我觉得影响很小。

**Comment by secondwtq** [comment]
我个人偏向于对于 `commit information`，使用 `类似“与某某提交相关的信息”这种比较冗长的妥协译法`。
至于 `commit message`，两种译法都可以表达原意。

主要理由是这样更清晰，首先很明显 `commit information` 和 `commit message` 两个短语意思是不一样的，而对于（没有阅读英文原文的）一般读者来说，不会去刻意区别 `提交信息` 与 `提交说明`，而实际上虽然可能 `提交信息` 更接近 `commit information`，但是很多人习惯里就把 `提交信息` 当作 `commit message`（我平常也是这么用的）。如果同时使用 `提交信息` 和 `提交说明` 的话，很容易造成混淆。

**Comment by oldsharp** [comment]
就此问题请教了 @jiangxin ，他的意见是

> commit log, commit message 在公司里用“提交说明”的比较多。

并赞同使用“提交说明”，详见 https://groups.google.com/forum/#!msg/gotgit/x6w2rlZ4xrc/S-R6IeBbFQAJ 。

关于 progit2-zh 选择哪一个，请各位说下自己的结论？

我仍然强烈建议使用“提交说明”。

**Comment by OlingCat** [comment]
“提交说明”确实是更好的译法，现在的问题就是应该遵循习惯还是通过权威把习惯改回来了。

**Comment by oldsharp** [comment]
应当推广好的译法 ;-)

**Comment by networm** [comment]
我认为可以使用“提交说明”。

**Comment by oldsharp** [comment]
已将相应修改 push 到 #265 。
