### ISSUE TITLE
“authentication”、“authorization”翻译问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#264]
目前我们项目将“authentication”译作“授权”，我认为这是不准确的。

根据 http://gitolite.com/gitolite/gitolite.html#auth ：

> - Authentication is the process of verifying that you are who you claim to be. An authentication system will establish that I am the user "sitaram" on my work system. The one behind gmail will similarly establish that I am "sitaramc". And so on...
>
> - Authorization is the process of asking what you want to do and deciding if you're allowed to do it or not.

因此我提议：
  - “authentication”译作“认证”；
  - “authorization”译作“授权”（我 `grep` 了一下全书发现没有出现“authorization”所以我们可以不用写入术语表）。

**Comment by networm** [comment]
同意“认证”。

**Comment by jeffsui** [comment]
同意“认证”。
