### ISSUE TITLE
“home directory”翻译问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#266]
目前的选择有：
- 家目录
- 主目录
- 用户目录

参见 https://github.com/progit/progit2-zh/pull/223#discussion_r36953879 中的讨论。

**Comment by networm** [comment]
建议使用“用户目录”。

**Comment by archersmind** [comment]
能不能直接翻译成 `Home 目录` 啊？

`用户目录` 到底是哪个用户？Linux 是多用户的。
`主目录`？那 **主和次** 是怎么分出来的？

**Comment by networm** [comment]
翻译成 `Home 目录` 的问题在于 Linux 下有 /home 目录，起名成这样容易引起歧义。

其次，在 https://github.com/progit/progit2-zh/pull/223#discussion_r36953879 的原文是 

> in the ``git'' user's home directory

是指当前用户的根目录，所有我建议使用 `用户目录`。

**Comment by archersmind** [comment]
@networm 了解。如果是单纯讨论一个特例，我觉得没问题。但是，我们需要确定出一个**统一**译法吗？

**Comment by oldsharp** [comment]
@networm “用户目录”有一个比较尴尬的问题是，如果面对类似“that user's home directory”这样的句子，译为“那位用户的用户目录”会显得比较奇怪，需要处理成“那位使用者的用户目录”这样。

我查阅了一些公开资料：

  - 中文维基百科的“[家目录](https://zh.wikipedia.org/wiki/%E5%AE%B6%E7%9B%AE%E5%BD%95)”条目：
![home-02](https://cloud.githubusercontent.com/assets/980500/9353305/e7e089b4-4699-11e5-8a60-9346c2c2e7bf.png)

  - 中文维基百科的“[文件系统层次结构标准](https://zh.wikipedia.org/wiki/%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84%E6%A0%87%E5%87%86#.E7.9B.AE.E5.BD.95.E7.BB.93.E6.9E.84)”条目：
![home-01](https://cloud.githubusercontent.com/assets/980500/9353424/bf843dca-469a-11e5-911f-176ad0a3da46.png)

  - Arch Linux FHS 简体中文维基中的[相关条目](https://wiki.archlinux.org/index.php/Arch_filesystem_hierarchy_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.2Fhome:_.E7.94.A8.E6.88.B7.E7.9B.AE.E5.BD.95)：
![home-03](https://cloud.githubusercontent.com/assets/980500/9353689/dcad3170-469c-11e5-9950-f44ab7c6d30f.png)
![home-04](https://cloud.githubusercontent.com/assets/980500/9353713/0995c314-469d-11e5-993c-0aa5a8bd036f.png)

  - 《鳥哥的 Linux 私房菜 》（繁体中文）中[相关章节](http://linux.vbird.org/linux_basic/0210filepermission.php#filepermission_type)：
![home-05](https://cloud.githubusercontent.com/assets/980500/9353719/2062718c-469d-11e5-9096-7c1465dce017.png)


  - 《鳥哥的 Linux 私房菜 》（简体中文）中[相关章节](http://vbird.dic.ksu.edu.tw/linux_basic/0210filepermission_3.php)：
![home-06](https://cloud.githubusercontent.com/assets/980500/9353981/49ecefbc-469f-11e5-8560-5fc1dd4d1b2f.png)


  - Filesystem Hierarchy Standard 的[中文翻译](http://wylmer_cn.gitbooks.io/filesystem-hierarchy-standard/content/3-root-filesystem/8-home.html)，译者是是 @Wylmer ：
![home-07](https://cloud.githubusercontent.com/assets/980500/9354010/6f2ebc1a-469f-11e5-9350-9c738ecd5e68.png)


可以看到，“家目录”占多数；如果担心上述部分资料是从繁体中文转换而来，我特地对比过这些页面的其他术语，都换成了更适合简体中文的用词——所以可以认为“家目录”是有意保留的翻译。

**Comment by archersmind** [comment]
@oldsharp  :+1:

**Comment by branchzero** [comment]
实际情况下，各个文章中 家目录 用的频率比较高，如果论准确的话，还是 用户目录 比较准确。
如何取舍实在不太好确定啊

**Comment by networm** [comment]
我当为当翻译的时候 user's home directory 可以不翻译 home，而是直接译为 用户目录。

**Comment by OlingCat** [comment]
同意用户目录，个人已经习惯这么说了。

**Comment by lilydjwg** [comment]
支持「家目录」，「家」与「home」一词对应这样了解英文的用户也十分容易建立关联。「主目录」也可。

「用户目录」不太像一个专有名词（term），用户可以理解成「我自己所拥有（own）的目录」。特别看一下 @networn 所举的例子，翻译后这种歧义十分明显。

「主目录」与「用户目录」有类似的问题，但是这个词用得比较多，所以我也支持和使用。Nautilus 使用的是「主文件夹」。

**Comment by kilofox** [comment]
user's home directory 翻译为“用户的家目录”，从学术的角度来看，我看可行，毕竟能够和英文对照上。我们可以效仿日本语言的做法，根据本国没有的词汇，可以引进的原则，引进“家目录”一词也不是不行。
意译为“用户目录”，容易产生歧义，因为很多目录都是用户的。
译为“用户的用户目录”更是不妥。
我同意 lilydjwg 的说法。

**Comment by networm** [comment]
这个还是看用户习惯，大部分书里面都是使用的“用户目录”，这是一种约定俗成的用法。

**Comment by lilydjwg** [comment]
@networm 「大部分」？我怎么好像一个也没有见过呢（翻译拙劣到眼疼的不算）？

**Comment by lilydjwg** [comment]
我在 Twitter 发起了一个[投票](https://twitter.com/lilydjwg/status/708979044226703360)。

**Comment by lilydjwg** [comment]
我在 Google+ 上也发起了一个[投票](https://plus.google.com/u/0/+%E7%99%BE%E5%90%88%E4%BB%99%E5%AD%90/posts/5Xs3QJSKmzX)。

我能发起投票的地方就只有这么多了。

**Comment by networm** [comment]
@lilydjwg 希望能给出一些权威的参考资料。

**Comment by lilydjwg** [comment]
@networm 你自己都不给让我给？我已经给了「大部分用户习惯」的资料了。

**Comment by networm** [comment]
还是需要更多的人参与讨论这个问题。

**Comment by oldsharp** [comment]
依云 wrote:

> 我在 Twitter 发起了一个[投票](https://twitter.com/lilydjwg/status/708979044226703360)。
> 我在 Google+ 上也发起了一个[投票](https://plus.google.com/u/0/+%E7%99%BE%E5%90%88%E4%BB%99%E5%AD%90/posts/5Xs3QJSKmzX)。

感谢 @lilydjwg 。
根据这两个投票结果来看，我觉得“主目录”可以作为最终结果。

**Comment by OlingCat** [comment]
没有异议的话就定为“主目录了”。
