### ISSUE TITLE
7.2 Git 工具 - 交互式暂存中描述文字错误

### ISSUE THREAD

**Issue by liufangjie** [progit/progit2-zh#276]
第一段中的“如果运行 git adds 时使用” 
应该改为" 如果运行 git add 时使用",其中的"git adds"多输入了个"s"

**Comment by networm** [comment]
好的，收到，这个记起，统一改。

**Comment by liufangjie** [comment]
OK

**Comment by networm** [comment]
你要是改的话我就给合并了！我建议仔细阅读下，找出一个章节中所有能找到的错误，然后提一个 PR。

**Comment by liufangjie** [comment]
我是在看的时候偶然发现这个问题的，刚才我提交了一个PR后来又关闭了，你们还是在做统一校对的时候修改吧。

**Comment by networm** [comment]
你可以再将那一节仔细看一遍，然后将所有找出的错误修正后再提一个 Pull Request。

**Comment by networm** [comment]
统一审校现在正在进行，见 #270 ，但只是针对之前翻译计划开始前就已翻译完成的章节。现在你发现问题后可以直接提 PR 修正。

**Comment by liufangjie** [comment]
已经提交PR了

**Comment by networm** [comment]
已合并。
