### ISSUE TITLE
Acrobat Reader DC 提示无法提取内嵌字体，系统已安装思源字体

### ISSUE THREAD

**Issue by pupie** [progit/progit2-zh#282]
环境：
Win7 x64 Eng Ultimate， 区域已设置为简体中文PRC，
Adobe Reader DC 2015.008.20082 简体中文版。
问题：
打开progit-zh.775.pdf 提示无法提取内嵌字体KECSBW+SourceHanSansSC-light。
从github下载最新思源字体安装重新打开也是同样问题。

**Comment by networm** [comment]
http://forum.atlas.oreilly.com/t/could-atlas-support-noto-sans-cjk-opensource-font/207/10

官方回复说正在调查这个字体问题。

**Comment by networm** [comment]
我又在官方重提了一个问题：

ProGit2-zh pdf font missing - O'Reilly Atlas Support Forum
http://forum.atlas.oreilly.com/t/progit2-zh-pdf-font-missing/239

**Comment by xiaobin2008** [comment]
Win7 x64 中文版
Adobe Reader DC 15.2048 简体中文版
progit-zh.823.pdf 仍然提示上面的错误，文件无法正常浏览。

**Comment by networm** [comment]
@xiaobin2008 Oreilly Atlas官方正在解决此问题。

**Comment by macarthor** [comment]
@networm 繁体中文的pdf用foxit就可以打开，而且才不到8MB，咱们简体中文是不是也得加加油 (ง •̀_•́)ง

**Comment by networm** [comment]
@macarthor 这个问题不是我们可以解决的问题，而是官方使用的 Oreilly Atlas 服务的问题！已向官方论坛提过问题了，一直没解决。如果需要中文版的 PDF，可自行前往 Release 页面下载。

**Comment by networm** [comment]
Releases · progit/progit2-zh
https://github.com/progit/progit2-zh/releases

**Comment by macarthor** [comment]
@networm 繁体中文不也是用atlas build的么。。。

**Comment by networm** [comment]
@macarthor 现在是 Oreilly Atlas 有问题，我们没法查，我们并不清楚哪个地方的什么文字或设置导致它出问题了，明白吗？

**Comment by YueLinHo** [comment]
壞消息是：
![image](https://cloud.githubusercontent.com/assets/5831804/14414453/c19772f0-ffc5-11e5-8751-fd8ace9d84a4.png)
From http://forum.atlas.oreilly.com/
