### ISSUE TITLE
官方自动构建的PDF版本乱码

### ISSUE THREAD

**Issue by Refactoring** [progit/progit2-zh#286]
如题,从官方下载PDF版本 https://progit2.s3.amazonaws.com/zh/2015-08-31-f1d9d/progit-zh.790.pdf ，内容全是乱码。(789版本也是.)
不知反馈到这里合适不?

**Comment by networm** [comment]
#282 一样的问题。

**Comment by coreywei** [comment]
乱码+1

**Comment by sanddudu** [comment]
@networm 可以考虑把个人构建的版本传到 release

**Comment by Rivsen** [comment]
813版本也是乱码的，无论是用chrome打开还是用okular都是

**Comment by sanddudu** [comment]
@Refactoring @coreywei @Rivsen 
官方的电子书生成平台目前出现问题，仍在解决。
在此之前，请下载下面链接中的 PDF 文件：
http://pan.baidu.com/s/1pJDue5X

**Comment by lzhr** [comment]
@sanddudu 请问这是用什么编译生成的？

**Comment by networm** [comment]
@lzhr 使用的是 O'Reilly Atlas 服务
https://atlas.oreilly.com/

**Comment by networm** [comment]
#347 fixed this problem
