### ISSUE TITLE
「shell」还是「外壳」？

### ISSUE THREAD

**Issue by lilydjwg** [progit/progit2-zh#287]
「shell 命令」、「在 shell 中执行」，还是「外壳命令」、「在外壳中执行」？

我推荐使用「shell」一词，因为这是目录被广泛接受的用法。而「外壳」一词，我猜测是早期翻译尝试时引入的一个用法，但是并没有被广泛接受。我看到「外壳」就像看到台湾地区用语一样有种陌生感。

**Comment by wongsyrone** [comment]
我也赞成使用 shell，外壳单独看还行，如果在意群中突然看见这个词会很别扭

**Comment by networm** [comment]
同意

**Comment by OlingCat** [comment]
倾向于不翻译。
不过一直不理解为啥 kernel 作为内核如此通用而与之对应的 外壳 却少有耳闻= =||

**Comment by wongsyrone** [comment]
按照维基百科的说法，外壳包含CLI和GUI

**Comment by lilydjwg** [comment]
@OlingCat 谁知道……
@wongsyrone 是的，具体指什么要看语境。像 GNOME shell 啊 Explorer shell 也有。另外我记得浏览器的 chrome（Mozilla 的术语）翻译过来也是外壳。

**Comment by wongsyrone** [comment]
@lilydjwg  @OlingCat 
可能是因为分属不同的项目吧，kernel主要是Linux，而shell的许多内容应该是属于GNU的吧，前者影响力大，后者比较庞杂，而且作为基础工具不易引起注意，仅是猜测。
PS：貌似有点跑题了

**Comment by lilydjwg** [comment]
嗯……既然没人反对的话我什么时候 PR 一下啦。

**Comment by OlingCat** [comment]
@lilydjwg Now!
