### ISSUE TITLE
bundle instell 会在json 1.8.1上出现问题

### ISSUE THREAD

**Issue by jinzhao1994** [progit/progit2-zh#295]
系统是 OS X EI Capitan 10.11.2
Ruby是使用brew安装的
我自己并不会ruby...我也不清楚这个问题与这个仓库有没有关系...
在网上搜索过后，使用brew update的方式解决了
报错信息如下

Installing json 1.8.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -r ./siteconf20160113-5928-12cubrb.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/usr/local/Cellar/ruby/2.3.0/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/json-1.8.1/gem_make.out

**Comment by jinzhao1994** [comment]
另外，生成的pdf不带页码么？有没有什么办法让他带着页码呢？

**Comment by networm** [comment]
这个问题应该和仓库没有关系，这只是 gem 安装的问题。
生成的 PDF 的确不带页码，不过如果使用 PDF 阅读器看的话，PDF 阅读器上有页码。

**Comment by jinzhao1994** [comment]
哦...好的..谢谢~
