### ISSUE TITLE
生成的 ePub 文件语言为 "en"，iBooks 中无法正常选择中文字体

### ISSUE THREAD

**Issue by wsxyeah** [progit/progit2-zh#297]
生成的 ePub 文件语言属性为 "en"，导致 iBooks 中无法正常选择中文字体，并且行距非常小。

**Comment by networm** [comment]
请尝试使用下面这个版本：
https://github.com/progit/progit2-zh/releases/download/v2.1.1/progit-zh-v2.1.1.mobi

**Comment by networm** [comment]
构建方式已更新，请前往 [Git - Book](https://git-scm.com/book/zh/v2) 下载新版本。

**Comment by networm** [comment]
经过测试 ProGit v2.1.58 的 epub 可以在 macOS Mojave 10.14.6 与 iOS 13.3.1 图书应用中切换中文字体为原字体、苹方、黑体、宋体、楷体、圆体。
* [Release 2.1.58 · progit/progit2-zh](https://github.com/progit/progit2-zh/releases/tag/2.1.58)
