### ISSUE TITLE
很多链接目标地址仍然都是错误的英文链接，会链接到404页面

### ISSUE THREAD

**Issue by kilofox** [progit/progit2-zh#303]
很多链接目标地址仍然都是错误的英文链接，是不是应该统一更新一下？
比如 A3.1 中的“初次运行 Git 前的配置”的链接目标地址，目前是“_first_time”，正确的地址应该是“起步-初次运行-Git-前的配置”。

**Comment by networm** [comment]
你可以找出所有的链接错误，详细的位置、上下文等，在这里描述下，方便修复。

**Comment by YueLinHo** [comment]
@kilofox 已先提供了一個錯誤的地方，或許應該先了解原因，以及初步的解法。

剛測了原文是否也有一樣的問題？結果有一樣的問題！

再查了原文版的 issue，已有人回報：[progit2 issue #454](https://github.com/progit/progit2/issues/454)

**Comment by kilofox** [comment]
整个 A3.1 一节的“词条”类链接基本上都是错误的，原因是直接复制了英文原版的词条链接，而没有翻译过来。全部替换成对应的词条就可以了。
根据英文版的链接规则，在词条前加一个下划线，中文版的链接应该也是加一个下划线（不过这只个猜测，需要实验）。比如“_first_time”对应“_起步-初次运行-Git-前的配置”。

**Comment by YueLinHo** [comment]
@kilofox 你可以追一下 [progit2 issue #454](https://github.com/progit/progit2/issues/454)，大概就會知道它其實是 **git-scm.com 的問題**，過去有一段時間是OK的，但又壞了，而且是**所有 link 都壞了**。所以並不是 zh 版的問題，甚至也不是 en 版的問題。

**Comment by YueLinHo** [comment]
@kilofox 你可以追一下 [progit2 issue #454](https://github.com/progit/progit2/issues/454)，大概就會知道它其實是 **git-scm.com 的問題** ([git-scm.com issue 633](https://github.com/git/git-scm.com/issues/633))，過去有一段時間是OK的，但又壞了，而且是**所有 link 都壞了**。所以並不是 zh 版的問題，甚至也不是 en 版的問題。

**Comment by kilofox** [comment]
嗯，确实，英文版也有问题。应该是链接配置的问题。
