### ISSUE TITLE
Plumbing 和 Porcelain 的翻译问题

### ISSUE THREAD

**Issue by Geno1024** [progit/progit2-zh#317]
翻译约定中使用“管件”和“瓷件”，感觉在通词达意方面比不上[真正使用时的场景](https://github.com/progit/progit2-zh/blob/master/book/10-git-internals/sections/plumbing-porcelain.asc)中的“底层命令”和“高层命令”来得通彻[摊手]。

**Comment by liuxilu** [comment]
有理

**Comment by OlingCat** [comment]
已将翻译改为：
plumbing => 底层命令
porcelain => 上层命令

本问题将在 #391 完成后修复。

**Comment by OlingCat** [comment]
Fixed by #398
