### ISSUE TITLE
Error of zh version pdf

### ISSUE THREAD

**Issue by lamuguo** [progit/progit2-zh#319]
https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf

不是很确定是我的编码问题还是怎么回事，总的来说就是：我看到的是乱码。能不能劳烦看一下？多谢！

**Comment by Geno1024** [comment]
😐是的，官方构建平台出了一些问题，这个以前已经提过 Issue，但是还没有解决。

😐现在请先使用我们自己构建的版本查看。

**Comment by YueLinHo** [comment]
See https://github.com/progit/progit2-zh/releases

**Comment by lamuguo** [comment]
Great! Thanks for your quick resp!

**Comment by YueLinHo** [comment]
Also see issue #286
