### ISSUE TITLE
中文 PDF 版本中符号 “⅔" 没有正确显示

### ISSUE THREAD

**Issue by huwan** [progit/progit2-zh#321]
位置：progit2-zh/book/10-git-internals/sections/packfiles.asc

> 通过打包对象减少了 ⅔ 的磁盘占用空间

这一句中的⅔在中文 PDF 中显示为一个信封图标。

**Comment by networm** [comment]
已确认，的确是这样，估计是字体渲染问题。

**Comment by liuxilu** [comment]
这怎么能忍？我去把它改成2/3（PS显示的那个字符不是信封）

**Comment by liuxilu** [comment]
我修好了 @networm

**Comment by networm** [comment]
@liuxilu 你修好了，但是没推上来啊，任何一个 PR 里面都没有你的提交啊

**Comment by liuxilu** [comment]
是我疏忽了，忘记写上issue编号：https://github.com/progit/progit2-zh/commit/455f4ece1de89d2dde28019cee189735a897fb24
另外[issue#375](https://github.com/progit/progit2-zh/issues/375)(f15bed7c688008f6c1b0b480c3947428ed01a0f7)[issue#365](https://github.com/progit/progit2-zh/issues/365)(88cdf68ee776e47ccb63669737b7ac1f640d4abc)我也修好了
@networm
