### ISSUE TITLE
dangling 单词翻译约定讨论

### ISSUE THREAD

**Issue by pityonline** [progit/progit2-zh#322]
[翻译约定](https://github.com/progit/progit2-zh/blob/954d8e85edfadd639f8111c371982d4a76680b3b/TRANSLATION_NOTES.asc#d)中 `dangling object` 一词约定翻译为**摇摆对象**，建议翻译成**悬空对象**，感觉这个使用场景更多的意思是悬空，孤立。

**Comment by tonghuix** [comment]
靠谱

**Comment by OlingCat** [comment]
同意

Tong Hui <notifications@github.com>于2016年10月17日周一 12:29写道：

**Comment by oldsharp** [comment]
当时我们修订术语表时候主要参照了 Git 官方的中文本地化术语表：https://github.com/git/git/blob/master/po/zh_CN.po

我曾就“dangling object”的翻译这个问题质疑过 Git l18n 的维护者 Jiangxin（见 https://github.com/jiangxin/git/pull/6#discussion-diff-36059770 ），但最后还是保留了“摇摆”这个翻译。

> oldsharp on Aug 3, 2015
> Its rare in computer science area, to translate "dangling" as "摇摆".  Maybe "悬空对象" is a better choice? (See https://zh.wikipedia.org/wiki/%E8%BF%B7%E9%80%94%E6%8C%87%E9%92%88 )

> jiangxin on Aug 4, 2015
> I prefer 摇摆. some dangling objects are useful, others are just trash.

> oldsharp on Aug 4, 2015
> Oh I see.
> The conception of Git's dangling object is unlike the wild pointer in some programming language - the Git objects may be referenced again later.
> Yeah, that's my fault.  Agree with "摇摆".

**Comment by oldsharp** [comment]
不过如果 progit2-zh 项目决定使用“悬空对象”或者“悬垂对象”，也没有问题，不一定都按照 Git l18n 来。
比如“submodule”，Git l18n 的翻译是“子模组”，progit2-zh 用的是“子模块”。
