### ISSUE TITLE
Git官网中文版电子书未更新/无法下载

### ISSUE THREAD

**Issue by Zhang-Xianglong** [progit/progit2-zh#325]
Git官网中文版电子书的html格式已更新，但无法下载；其他格式尚未更新。

之前的html格式是可以下载的，求解。

**Comment by YueLinHo** [comment]
幾個月前負責自動 build 的 Atlas 停止服務了，所以很久沒有更新；
(https://github.com/progit/progit2/issues/625#issuecomment-269381115)

但最近設法可以讓 html 可以自動更新
(https://github.com/git/git-scm.com/pull/917)

但隨後有一些問題
(https://github.com/git/git-scm.com/issues/929)
我猜問題出在這裡

**Comment by Zhang-Xianglong** [comment]
我尝试在CentOS6.8下搭建了一个环境，但是到asciidoctor-pdf-cjk-kai_gen_gothic-install这步就执行不下去了，总是连接超时。

**Comment by YueLinHo** [comment]
git scm 目前想不出解決方案，所以暫時將下載移除了
see https://github.com/git/git-scm.com/pull/983

@Zhang-Xianglong 我不是很了解技術細節，或許你可以 follow 我提供的 link 的討論串，提出你的看法和疑問，或許你可以幫得上一些忙。
