### ISSUE TITLE
02-git-basics/sections/recording-changes.asc -- Removing Files

### ISSUE THREAD

**Issue by yingang** [progit/progit2-zh#33]
> Another useful thing you may want to do is to keep the file in your working tree but remove it from your staging area.

> 另外一种情况是，我们**想把文件从 Git 仓库中删除**（亦即从暂存区域移除），但仍然希望保留在当前工作目录中。

上述标粗体的部分从原文中看不出类似的意思，是否需要修改？

**Comment by archermind** [comment]
@yingang 和第一版翻译的一样，建议保留（保留粗体部分）

**Comment by networm** [comment]
@yingang 已解决的问题，关闭。
