### ISSUE TITLE
PDF eBook editing error

### ISSUE THREAD

**Issue by doudoubean** [progit/progit2-zh#343]
An edit error appeared on page 12，line 16。The detail is as follow:
因为 Git 在保持向后兼容方便表现很好
I think this ought to be modified like this. It's content is below:
因为 Git 在保持向后兼容方面表现很好

**Comment by networm** [comment]
progit2-zh/installing.asc at master · progit/progit2-zh
https://github.com/progit/progit2-zh/blob/master/book/01-introduction/sections/installing.asc

已修正，等待下次打包更新。
