### ISSUE TITLE
为何不按照英文版原书的句式来翻译

### ISSUE THREAD

**Issue by pei-han** [progit/progit2-zh#346]
如题，例如：
![image](https://user-images.githubusercontent.com/1300292/35425665-6a844f5c-0297-11e8-876c-33f19d986347.png)
![image](https://user-images.githubusercontent.com/1300292/35425671-780cce38-0297-11e8-9255-78be2f15ecb1.png)

我明白，中英文语法和句式的不同，很多情况下确实需要变换。
红框处的对比，个人觉得不需要转换句式的地方，遵照原句式翻译是不是更好？

**Comment by tonghuix** [comment]
应该是翻译者的个人风格，技术文档关键是准确，无歧义。我认为并无一定要按原文的必要。
