### ISSUE TITLE
07-git-tools/reset 翻译有误

### ISSUE THREAD

**Issue by kikyous** [progit/progit2-zh#348]
https://github.com/progit/progit2-zh/blob/master/book/07-git-tools/sections/reset.asc

![](https://git-scm.com/book/en/v2/images/reset-ex3.png)

`接着运行 git commit，它首先会移除索引中的内容并将它保存为一个永久的快照，然后创建一个指向该快照的提交对象，最后更新 master 来指向本次提交。`

在阅读上面一段的时候就感觉不对，因为结合上下文git commit并不会`移除`索引中的内容

然后查看了一下英文原文：
`Then we run git commit, which takes the contents of the Index and saves it as a permanent snapshot, creates a commit object which points to that snapshot, and updates master to point to that commit.`

这里用的是`takes`,并没有移除的意思，所以中文翻译应该改成`它首先会取得索引中的内容`

**Comment by networm** [comment]
你可以尝试提交一个 Pull Request

**Comment by kikyous** [comment]
我想先来确定一下这是否是一个错误

**Comment by networm** [comment]
不一定，你需要查看翻译时对应的英文版本，在 Issues 里有与英文版同步的问题，你可以找一下

**Comment by networm** [comment]
这里的确是会移除索引区的内容生成一次新提交，你看看应该如何翻译，找到一个合适的方法表达出这层意思来？

**Comment by kikyous** [comment]
没有移除啊，看下面的一段：
`此时如果我们运行 git status，会发现没有任何改动，因为现在三棵树完全相同。`
如果索引区被移除了，三棵树不能相同
而且看我附的图片，index里面是有内容的

**Comment by networm** [comment]
是的，我说错了，为了防止误导后来的人，我把上面那句删除了。你可以提交一个 PR 来修正此问题。
