### ISSUE TITLE
add description and website

### ISSUE THREAD

**Issue by kikyous** [progit/progit2-zh#353]
Pro Git  2nd Edition - https://git-scm.com/book/zh/v2

**Comment by networm** [comment]
如果要改动，你可以直接提交一个 Pull Request

**Comment by kikyous** [comment]
![image](https://user-images.githubusercontent.com/818616/39686469-cd78adb6-51fb-11e8-9abc-830af06d1915.png)
这个地方可以pr吗？

**Comment by networm** [comment]
这个地方我也改不了，需要英文作者才能改
