### ISSUE TITLE
对"you"翻译成"您"的不解

### ISSUE THREAD

**Issue by h404bi** [progit/progit2-zh#36]
我是看第一版然后找过来的，发现还没翻译完。看了一下翻译发现约定了将"you"翻译成"您"，对此不解。
我知道"您"能表示礼貌，但在一本技术类的书籍/说明文档中通篇都是"您您您"，读起来不觉得拗口难受吗？读者都是抱着学习的心态读书的，感觉更应该是"虚心请教"，而不是感觉"被抬高"吧。我读过的工具书还真没见过通篇用尊称的（虽然读得不多）。建议用回"你"，或者像繁体版本那样用"读者"（不过会没有用"你"那么亲切）。

如有不对，请见谅。

**Comment by TenphyX** [comment]
非常同意。我在翻译第四章，不管是翻译的时候用“您”还是翻译完回过头自己再读一遍，都觉得很别扭。
第一版也全部翻译为“你”了。

**Comment by oldsharp** [comment]
我也觉得用“你”更加适合。

**Comment by archermind** [comment]
无法更同意，第一版里面一直都是使用“你”，建议在醒目的地方标识出中文翻译对照表。

**Comment by devbean** [comment]
那我们到最后再统一一下吧

**Comment by networm** [comment]
我印象中看的技术书里面的代词都是“你”而不是“您”啊！我们翻译这个东西要结合语言习惯来看吧，这个“您”读起真的是相当拗口啊！

**Comment by tonghuix** [comment]
“你”确实比“您”更好。但另一方面，这个敬称在某些场合是可以考虑这么翻译的。在技术文档里并不需要如此。

**Comment by archermind** [comment]
@devbean 的意思是最后的时候再进行统一。既然大家都觉得`你`更加合适，那么我们 find all `您` replaced with `您`。OK ？

**Comment by devbean** [comment]
按照大家讨论的意思，已经修改过 NOTES 里面的内容了，谁方便的话可以统一替换一下

**Comment by h404bi** [comment]
Close, https://github.com/progit/progit2-zh/commit/b7b0b563b7449c6ecaf4360723dbc3e812d12624
