### ISSUE TITLE
 bundle exec rake book:build

### ISSUE THREAD

**Issue by heguangzhi** [progit/progit2-zh#362]
[root@izbp18p2ymht9zenckfaiez progit2-zh]# bundle exec rake book:build
rake aborted!
LoadError: cannot load such file -- github_changelog_generator
/home/www/progit2-zh/Rakefile:3:in `require'
/home/www/progit2-zh/Rakefile:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
[root@izbp18p2ymht9zenckfaiez progit2-zh]# find  ./ -name  github_changelog_generator 
[root@izbp18p2ymht9zenckfaiez progit2-zh]#

**Comment by liuxilu** [comment]
这不归本项目管啊。关issue @networm

**Comment by networm** [comment]
应该是缺这个东西：
LoadError: cannot load such file -- github_changelog_generator
