### ISSUE TITLE
2.6 git基础 打标签 附注标签 命令行中 是否应该是双引号？

### ISSUE THREAD

**Issue by josephzjw** [progit/progit2-zh#365]
网站上的指令是`git tag -a v1.4 -m 'my version 1.4'`，我敲到windows命令行里面显示`fatal: too many params`，改成双引号就可以了，我看pro-git 英文版的网页上也是双引号。

**Comment by liuxilu** [comment]
因为cmd不支持单引号的引用

**Comment by liuxilu** [comment]
不过得跟原版同步

**Comment by liuxilu** [comment]
我修好了 @networm
