### ISSUE TITLE
书中部分字体渲染问题

### ISSUE THREAD

**Issue by ChuckieChen945** [progit/progit2-zh#371]
3.6 Git 分支 - 变基 章节中的`从这个角度看来，改变提交历史是一种亵渎，你使用_谎言_掩盖了实际发生过的事情。`中的`谎言`二字在PDF,mobi,网页中均无法渲染成斜体。

**Comment by 591097213** [comment]
还有《引言》中的`*第一章*`～`第十章`,`*附录A*`~`*附录C*`等词汇也均无法渲染成黑体

**Comment by ChuckieChen945** [comment]
《2.2 Git 基础 - 记录每次更新到仓库》中``比如`a/**/z` 可以匹配 `a/z`, `a/b/z` 或 `a/b/c/z`等``中的`` `a/**/z` ``,`` `a/b/c/z` ``两处无法被渲染成代码格式

**Comment by networm** [comment]
你找到的这几个问题都是由于标记周围没有添加空格导致的，看起来现在使用的 asciidoc 工具链无法正确处理标记与中文混排的情况。
你如果有兴趣的话可以将错误的地方前后用空格包围来解决此问题，然后可以发一个 PR。
建议在看书的过程中找到并修改，在看完的时候提一个 PR 统一处理。

**Comment by ChuckieChen945** [comment]
好的，我找完后统一处理。
