### ISSUE TITLE
“7.1 Git 工具 - 选择修订版本”中的一句翻译有很大歧义

### ISSUE THREAD

**Issue by itamud** [progit/progit2-zh#373]
原文是: `If you run a git push and your current branch is tracking origin/master, the commits listed by git log origin/master..HEAD are the commits that will be transferred to the server.`，意思是运行 `git push` 命令时推送到远程服务器的提交，和运行 `git log origin/master..HEAD` 命令输出的提交是相同的。

而原译文中是: `如果你执行 git push 并且你的当前分支正在跟踪 origin/master，由 git log origin/master..HEAD 所输出的提交会被传输到远端服务器。`，这句意思是运行 `git log origin/master..HEAD` 所输出的提交会被传输到远端服务器。

原译文该句子有极大歧义，会误导读者。

**Comment by itamud** [comment]
原文是: `If you run a git push and your current branch is tracking origin/master, the commits listed by git log origin/master..HEAD are the commits that will be transferred to the server.`，意思是运行 `git push` 命令时推送到远程服务器的提交，和运行 `git log origin/master..HEAD` 命令输出的提交是相同的。

而原译文中是: `如果你执行 git push 并且你的当前分支正在跟踪 origin/master，由 git log origin/master..HEAD 所输出的提交会被传输到远端服务器。`，这句意思是运行 `git log origin/master..HEAD` 所输出的提交会被传输到远端服务器。

原译文该句子有极大歧义，会误导读者。

**Comment by networm** [comment]
已合并修改
