### ISSUE TITLE
#文字错误 pdf勘误，241页，图中是9e5e6a4，文字是9e5e64a,最后两个字符位置颠倒了。

### ISSUE THREAD

**Issue by Seachal** [progit/progit2-zh#375]
`运行 git reset 9e5e64a 将会使 master 指向 9e5e64a`此段文字上方图中是9e5e6a4

**Comment by networm** [comment]
可以尝试提交一个 PR 修正此问题。

**Comment by liuxilu** [comment]
mark一下，在progit2-zh/book/07-git-tools/sections/reset.asc

**Comment by liuxilu** [comment]
我修好了 @networm
