### ISSUE TITLE
英文版本计划 2

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#383]
英文版同步计划 · Issue #245 · progit/progit2-zh
https://github.com/progit/progit2-zh/issues/245

上次同步已经是 4 年前了，如果有人有兴趣可以按照之前的方法同步。

**Comment by networm** [comment]
@liuxilu 你要不要试试？

**Comment by liuxilu** [comment]
我看看吧，我先把新的英文内容整合进中文版

**Comment by liuxilu** [comment]
码一下，从[这](https://github.com/progit/progit2/commit/553c62a116a7597d63a209fc62107238b93a6fff)开始

**Comment by liuxilu** [comment]
下载了[这个release](https://github.com/progit/progit2/releases?after=2.1.0)进行比较，clone太多网络不行

**Comment by OlingCat** [comment]
@liuxilu 你还在 merge 上游内容吗？

**Comment by liuxilu** [comment]
没，你来做吧

**Comment by OlingCat** [comment]
本问题由 #391 取代。
