### ISSUE TITLE
7.6 章节翻译不准确

### ISSUE THREAD

**Issue by AlbertLarry** [progit/progit2-zh#389]
这个命令是 filter-branch，它可以改写历史中大量的提交，除非你的项目还没有公开并且其他人没有基于要改写的工作的提交做的工作，你不应当使用它

应该改为

这个命令是 filter-branch，它可以改写历史中大量的提交，除非你的项目还没有公开并且其他人没有基于要改写的工作的提交做的工作，**_否则_**你不应当使用它

**Comment by networm** [comment]
已修复
