### ISSUE TITLE
英文版同步计划（commit 0c09fcd5 / tag 2.1.195）

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#391]
我们需要把代码库同步到英文版的 `0c09fcd50d1cc6b358983c9841a1a8d12fe5663c`，即 tag `2.1.195`。
由于合并时无法及时提交，我会在此记录合并的工作进度。在合并过程中，我会适当校对、润色部分语句。

## 任务列表
- [x] both modified:   Rakefile
- [x] added by them:   A-git-in-other-environments.asc
- [x] both added:      B-embedding-git-in-your-applications.asc
- [x] both added:      C-git-commands.asc
- [x] both modified:   README.asc
- [x] both modified:   book/01-introduction/sections/about-version-control.asc
- [x] both modified:   book/01-introduction/sections/command-line.asc
- [x] both modified:   book/01-introduction/sections/first-time-setup.asc
- [x] both modified:   book/01-introduction/sections/help.asc
- [x] both modified:   book/01-introduction/sections/history.asc
- [x] both modified:   book/01-introduction/sections/installing.asc
- [x] both modified:   book/01-introduction/sections/what-is-git.asc
- [x] both modified:   book/02-git-basics/sections/getting-a-repository.asc
- [x] both modified:   book/02-git-basics/sections/recording-changes.asc
- [x] both modified:   book/02-git-basics/sections/remotes.asc
- [x] both modified:   book/02-git-basics/sections/tagging.asc
- [x] both modified:   book/02-git-basics/sections/undoing.asc
- [x] both modified:   book/02-git-basics/sections/viewing-history.asc
- [x] both modified:   book/03-git-branching/sections/basic-branching-and-merging.asc
- [x] both modified:   book/03-git-branching/sections/branch-management.asc
- [x] both modified:   book/03-git-branching/sections/nutshell.asc
- [x] both modified:   book/03-git-branching/sections/rebasing.asc
- [x] both modified:   book/03-git-branching/sections/remote-branches.asc
- [x] both modified:   book/03-git-branching/sections/workflows.asc
- [x] both modified:   book/04-git-server/sections/generating-ssh-key.asc
- [x] both modified:   book/04-git-server/sections/git-daemon.asc
- [x] both modified:   book/04-git-server/sections/git-on-a-server.asc
- [x] both modified:   book/04-git-server/sections/gitlab.asc
- [x] both modified:   book/04-git-server/sections/gitweb.asc
- [x] both modified:   book/04-git-server/sections/hosted.asc
- [x] both modified:   book/04-git-server/sections/protocols.asc
- [x] both modified:   book/04-git-server/sections/setting-up-server.asc
- [x] both modified:   book/04-git-server/sections/smart-http.asc
- [x] both modified:   book/05-distributed-git/sections/contributing.asc
- [x] both modified:   book/05-distributed-git/sections/distributed-workflows.asc
- [x] both modified:   book/05-distributed-git/sections/maintaining.asc
- [x] both modified:   book/06-github/sections/1-setting-up-account.asc
- [x] both modified:   book/06-github/sections/2-contributing.asc
- [x] both modified:   book/06-github/sections/3-maintaining.asc
- [x] both modified:   book/06-github/sections/4-managing-organization.asc
- [x] both modified:   book/06-github/sections/5-scripting.asc
- [x] both modified:   book/07-git-tools/sections/advanced-merging.asc
- [x] both modified:   book/07-git-tools/sections/bundling.asc
- [x] both modified:   book/07-git-tools/sections/credentials.asc
- [x] both modified:   book/07-git-tools/sections/debugging.asc
- [x] both modified:   book/07-git-tools/sections/interactive-staging.asc
- [x] both modified:   book/07-git-tools/sections/replace.asc
- [x] both modified:   book/07-git-tools/sections/rerere.asc
- [x] both modified:   book/07-git-tools/sections/reset.asc
- [x] both modified:   book/07-git-tools/sections/revision-selection.asc
- [x] both modified:   book/07-git-tools/sections/rewriting-history.asc
- [x] both modified:   book/07-git-tools/sections/searching.asc
- [x] both modified:   book/07-git-tools/sections/signing.asc
- [x] both modified:   book/07-git-tools/sections/stashing-cleaning.asc
- [x] both modified:   book/07-git-tools/sections/submodules.asc
- [x] both modified:   book/07-git-tools/sections/subtree-merges.asc
- [x] both modified:   book/08-customizing-git/sections/attributes.asc
- [x] both modified:   book/08-customizing-git/sections/config.asc
- [x] both modified:   book/08-customizing-git/sections/hooks.asc
- [x] both modified:   book/08-customizing-git/sections/policy.asc
- [x] both modified:   book/09-git-and-other-scms/sections/client-hg.asc
- [x] both modified:   book/09-git-and-other-scms/sections/client-p4.asc
- [x] both modified:   book/09-git-and-other-scms/sections/client-svn.asc
- [x] both modified:   book/09-git-and-other-scms/sections/client-tfs.asc
- [x] both modified:   book/09-git-and-other-scms/sections/import-custom.asc
- [x] both modified:   book/09-git-and-other-scms/sections/import-hg.asc
- [x] both modified:   book/09-git-and-other-scms/sections/import-svn.asc
- [x] both modified:   book/09-git-and-other-scms/sections/import-tfs.asc
- [x] both modified:   book/10-git-internals/sections/environment.asc
- [x] both modified:   book/10-git-internals/sections/maintenance.asc
- [x] both modified:   book/10-git-internals/sections/objects.asc
- [x] both modified:   book/10-git-internals/sections/packfiles.asc
- [x] both modified:   book/10-git-internals/sections/plumbing-porcelain.asc
- [x] both modified:   book/10-git-internals/sections/refs.asc
- [x] both modified:   book/10-git-internals/sections/refspec.asc
- [x] both modified:   book/10-git-internals/sections/transfer-protocols.asc
- [x] both modified:   book/A-git-in-other-environments/sections/bash.asc
- [x] both modified:   book/A-git-in-other-environments/sections/guis.asc
- [x] both modified:   book/A-git-in-other-environments/sections/powershell.asc
- [x] both modified:   book/A-git-in-other-environments/sections/zsh.asc
- [x] both modified:   book/B-embedding-git/sections/jgit.asc
- [x] both modified:   book/B-embedding-git/sections/libgit2.asc
- [x] both modified:   book/contributors.asc
- [x] both added:      book/dedication.asc
- [x] both modified:   book/introduction.asc
- [x] both added:      book/preface_ben.asc
- [x] added by them:   book/preface_schacon.asc
- [x] added by them:   ch01-getting-started.asc == ch01-introduction.asc
- [x] added by them:   ch02-git-basics-chapter.asc == ch02-git-basics.asc
- [x] added by them:   ch03-git-branching.asc
- [x] added by them:   ch04-git-on-the-server.asc == ch04-git-server.asc
- [x] added by them:   ch05-distributed-git.asc
- [x] added by them:   ch06-github.asc
- [x] both added:      ch07-git-tools.asc
- [x] added by them:   ch08-customizing-git.asc
- [x] added by them:   ch09-git-and-other-systems.asc == ch09-git-and-other-systems.asc
- [x] both added:      ch10-git-internals.asc
- [x] both added:      index.asc
- [x] both modified:   progit.asc

**Comment by networm** [comment]
Hi @schacon, @OlingCat is responsible for synchronizing Chinese version with English version of ProGit these days. I think he/she is doing a wonderful job. He/she also keeps tracks with other open issues and would solve them too. Could you add he/she as a member so he/she could manage issues?

**Comment by OlingCat** [comment]
正文合并完毕。
接下来的任务：

- [ ] 修复 `Rakefile`
- [ ] 修复 `travis.yml`
