### ISSUE TITLE
7.8章节 勘误

### ISSUE THREAD

**Issue by FrankYuanhao** [progit/progit2-zh#396]
第二版中 7.8（高级合并）- 还原提交（p264）中。 
语句 “同时保留从父结点 #1（C4）开始的所有内容。”，对比英文版为"while keeping all the content from parent #1 (C6)."。父节点描述错误，望更正。

**Comment by networm** [comment]
@OlingCat 这个问题可以检查下

**Comment by OlingCat** [comment]
已修正，本 Issue 会在合并后关闭。

**Comment by OlingCat** [comment]
Fixed by #398
