### ISSUE TITLE
建议将 topic branch 译作「主题分支」

### ISSUE THREAD

**Issue by OlingCat** [progit/progit2-zh#397]
目前 topic branch 是译作「特性分支」的，然而一个 topic branch 未必都是添加新特性的，可能是围绕 bug 修复等某个主题展开的，于是建议将它直译作「主题分支」，类比于「主题活动」。

本问题将在 #391 合并完成后统一替换修改。

**Comment by networm** [comment]
同意

**Comment by OlingCat** [comment]
Fixed by #398
