### ISSUE TITLE
能给这个repo加个short description吗？

### ISSUE THREAD

**Issue by archermind** [progit/progit2-zh#41]
类似：Progit book 2nd Edition, Simplified Chinese version

**Comment by devbean** [comment]
貌似 fork 的项目不能添加

**Comment by archermind** [comment]
@devbean 不应该吧。我从这里fork之后的repo，我可以在自己的repo中加short description啊

**Comment by devbean** [comment]
原始库有的话可以修改，没有的话貌似没找到添加的地址

**Comment by archermind** [comment]
![edit](https://cloud.githubusercontent.com/assets/1461331/7855435/38c795ac-0554-11e5-931c-bd025ac84bf2.png)

看到那个Edit了吗？点一下试试？

**Comment by devbean** [comment]
这个仓库不是我的哦，所有者是 progit，所以我没有权限 edit

**Comment by archermind** [comment]
这里呢？有吗
![screenshot from 2015-05-28 16 14 01](https://cloud.githubusercontent.com/assets/1461331/7855512/daa66a74-0554-11e5-9af2-963c41fc9680.png)

**Comment by devbean** [comment]
这个仓库是你的，所以你有权限，但是 progit/progit2-zh 这个库不是我的，所以没有权限

**Comment by archermind** [comment]
@devbean 对不起，给你添麻烦了，close这个issue吧！
