### ISSUE TITLE
detacthed HEAD书写错误

### ISSUE THREAD

**Issue by slothjun** [progit/progit2-zh#411]
Describe the bug:
分离头指针的英文全称应该是 detached HEAD

Steps to reproduce:

1.Go to 'https://git-scm.com/book/zh/v2'

2.Click on '2.6打标签'

3.Scroll down to '检出标签'

4.See error '离头指针（detacthed HEAD）'

**Comment by networm** [comment]
你可以帮忙提一个 Pull Request 修改一下
