### ISSUE TITLE
关于提高下载速度的几条建议

### ISSUE THREAD

**Issue by Destroyer-LDB** [progit/progit2-zh#418]
我是国内用户，电信网络，下国内的东西很快，但在Github上每秒只有10~20KB，关于提高下载速度，我有以下几条建议：
 * 开一个镜像站；
 * 在国内网盘中发布资源；
 * 压缩文档等。
另外，希望能把英文版的也发一下。

**Comment by networm** [comment]
没有必要，这东西用的人本来就不是很多，维护成本太高。需要的人可以自己解决下载慢的问题，不需要的慢慢下载也没关系。如果你坚持一定要提高下载速度，你可以自己来做这件事。

**Comment by Destroyer-LDB** [comment]
@networm 
好的，那我可不可以在这个issue中发一个百度网盘的链接？里面放上这个文档。

**Comment by networm** [comment]
可以
