### ISSUE TITLE
Git mv操作那部分的最后一段里的批处理重命名是从哪里翻译的？

### ISSUE THREAD

**Issue by nkjackzhang** [progit/progit2-zh#424]
英文是`you can use any tool you like to rename a file`，怎么也体现不出来用其他工具批处理重命名吧。

**Comment by networm** [comment]
直接按照你的想法把这几处都改了，提一个 PR 吧！

**Comment by nkjackzhang** [comment]
> 
> 
> 直接按照你的想法把这几处都改了，提一个 PR 吧！

不知道现在的翻译是以英文的那个版本为准的，我看的是最新的英文版。

**Comment by networm** [comment]
直接用英文版最新版本翻译就行

**Comment by networm** [comment]
建议 @nkjackzhang 抽时间翻译一下！

**Comment by zhangjinbao3114** [comment]
已修订
