### ISSUE TITLE
【2.2 Git基础 - 记录每次更新到仓库】文字输入错序

### ISSUE THREAD

**Issue by wongyah** [progit/progit2-zh#427]
# 【2.2 Git 基础】→【记录每次更新到仓库】

## 中文译文

现在我们的机器上有了一个 真实项目 的 Git 仓库，并从这个仓库中检出了所有文件的 工作副本。 通常，你会对这些文件做些修改，每当完成了一个阶段的目标，想要**将记录下它**时，就将它提交**到到**仓库。

## 修正建议

现在我们的机器上有了一个 真实项目 的 Git 仓库，并从这个仓库中检出了所有文件的 工作副本。 通常，你会对这些文件做些修改，每当完成了一个阶段的目标，想要**将它记录下来**时，就将它提交**到**仓库。**

**Comment by networm** [comment]
你直接改下文件提个 PR 吧

**Comment by zhangjinbao3114** [comment]
已解决
