### ISSUE TITLE
新版本git已经使用switch 和restore代替了checkout，但是翻译中还没有修改

### ISSUE THREAD

**Issue by LiuZengqiang** [progit/progit2-zh#442]

**Comment by networm** [comment]
1. 现在这两个命令还处在测试期，没有稳定。
2. 需要等 ProGit 英文版增加之后中文版翻译才会更新。
3. 如果有需求，请在 ProGit 英文版提交 Issue

**Comment by dnxxymcj** [comment]
> 1. 现在这两个命令还处在测试期，没有稳定。
> 2. 需要等 ProGit 英文版增加之后中文版翻译才会更新。
> 3. 如果有需求，请在 ProGit 英文版提交 Issue

英文版的已经更新了

**Comment by networm** [comment]
你要是有兴趣可以直接翻译，然后发送 Pull Request。
