### ISSUE TITLE
【服务器上的Git · GitLab · 基本用途】 小节 （PDF 121 页）语句翻译错误

### ISSUE THREAD

**Issue by cangyin** [progit/progit2-zh#446]
【服务器上的Git · GitLab · 基本用途】 小节
> 你会被要求填写项目名称， ~也就是~ 这个项目所属的命名空间，以及它的可视层级。

 原文为

> You’ll be asked for the project’s name, **which** namespace it should belong to, and what its visibility level should be

建议译为

> 你需要填写项目名称，项目所属命名空间，以及它的可视层级。

**Comment by networm** [comment]
练习使用 GitHub，提一个 Pull Request 来修改吧！

**Comment by cangyin** [comment]
项目贡献规范太多，看不过来。

**Comment by cangyin** [comment]
这个项目有 errata 网址吗

**Comment by networm** [comment]
规范其实内容不多，简单看下，然后就可以改了。
