### ISSUE TITLE
检查 Update TRANSLATION_NOTES.asc pull request

### ISSUE THREAD

**Issue by devbean** [progit/progit2-zh#45]
请大家首先检查 [Update TRANSLATION_NOTES.asc pull request] (https://github.com/progit/progit2-zh/pull/44)，以便为统一翻译做准备。

**Comment by archermind** [comment]
这个翻译对照表，我参考了tw团队整理的单词，从中挑拣出重要的词汇。然后对比查找中文第一版中的翻译，整理出了这个表，希望大家提出宝贵意见。

**Comment by devbean** [comment]
repository 翻译成资料库还是仓库？好像这两个名字都有翻译

**Comment by 8loser** [comment]
覺得使用倉庫比較適合，用資料庫像是database

**Comment by archermind** [comment]
我对比第一版的，作者把他repository翻译成仓库，所以我决定和第一版一致。

**Comment by archermind** [comment]
大家热情不高，好沮丧，有没有at all 功能 ？

**Comment by tonghuix** [comment]
我已经发inline comment了，希望可以完善

**Comment by archermind** [comment]
@tonghuix 我也一一回复了，下面我会进一步改进，谢谢！
