### ISSUE TITLE
需要制定翻译用“术语表”

### ISSUE THREAD

**Issue by tonghuix** [progit/progit2-zh#46]
浏览既有的Issues的时候发现，大家对很多Git术语尚没有形成统一的认识。我个人认为，按照一般翻译规则，还是需要一张“术语表”。而且已翻译的版本也是根据翻译者水平，各有理解。

我个人还是比较推崇蒋鑫写的《Git权威指南》一书里的翻译，或者后来的第二本[《Got Github》](http://www.worldhello.net/gotgithub/)。比如他对一些常用的术语有一些翻译：

Frok - 派生
Pull - 拉取
Push - 推送
Rebase - 变基
Pull Request - 合并请求
…

同时蒋鑫也是Git的贡献者之一，因此他的中文翻译带有一定权威性，因此我建议是否可以将蒋鑫翻译的一些术语提出来，作为术语表供社区翻译者参考？

**Comment by tonghuix** [comment]
看到#45 已经在发出Pull Request了，还是一起去完善那个吧！

**Comment by devbean** [comment]
直接在 https://github.com/progit/progit2-zh/issues/45 讨论吧
