### ISSUE TITLE
第3章《分支的新建与合并》的翻译“暂存（stashing）”是否有歧义、前后不一致

### ISSUE THREAD

**Issue by hihaojie** [progit/progit2-zh#464]
如链接所指，此处`stashing`翻译为“暂存”，在前文中`Staged`被译为“已暂存”，而在《贮藏与清理》中`stash`被译为“贮藏”。翻译前后存在不一致，且有歧义。

https://github.com/progit/progit2-zh/blob/a11fb45eaa0ec694d0ef3e38d34d4977690704ce/book/03-git-branching/sections/basic-branching-and-merging.asc?plain=1#L68C55-L68C55

**Comment by hasban12138** [comment]
暂存的问题已经修改
不过全文搜索翻译 这个确实对我的英语水平提出了严苛的考验 这个以我的英语水平真的无能为力了 ( ´_ゝ｀)

**Comment by networm** [comment]
在中文版本里全局搜索“暂存”检查用的对不对就行了。

**Comment by hasban12138** [comment]
xd 但这个确实不只是用的对不对的问题了 需要每一个都要和原版进行对照 需要确定上下文正确 而且也不只是“暂存”可能需要进行修改 这种的修改确实以我的英语水平有点难度了

**Comment by networm** [comment]
没事，那就不用弄了
