### ISSUE TITLE
【显示错误】2.2 Git 基础 - 记录每次更新到仓库

### ISSUE THREAD

**Issue by hasban12138** [progit/progit2-zh#468]
[中文版](https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E8%AE%B0%E5%BD%95%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E5%88%B0%E4%BB%93%E5%BA%93)本这一段是 
```
使用两个星号（）表示匹配任意中间目录，比如 a//z 可以匹配 a/z 、 a/b/z 或 a/b/c/z 等
```
![image](https://github.com/progit/progit2-zh/assets/33484052/9dd9912f-a131-4cf8-a506-3690545d71fc)

而在[英文版](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository)本是
```
You can also use two asterisks to match nested directories; a/**/z would match a/z, a/b/z, a/b/c/z, and so on
```
![image](https://github.com/progit/progit2-zh/assets/33484052/7343014d-72b7-46c6-a30b-086dee9210fc)

git上是正确的 但是在显示时是错误的

**Comment by networm** [comment]
合并了，后续注意看下看看官网 HTML 与 PDF 有没有改对

**Comment by hasban12138** [comment]
好的 不过请问大约需要多久能刷新呢

**Comment by networm** [comment]
看起来不会刷新了，构建一直失败
fix 2.2章 星号（*）显示错误 · progit/progit2-zh@a79913e
https://github.com/progit/progit2-zh/actions/runs/7032757931

**Comment by networm** [comment]
现在打包系统增加了一个书籍内的链接有效性检查，如果发现无法访问就会打包失败。
如果你有兴趣的话，可以看下英文原版是怎么改的，然后提交一下对应的修复。

**Comment by networm** [comment]
先在中文版里面找到错误 URL 所在的章节，然后去英文版对应章节里看下改成什么了。

**Comment by hasban12138** [comment]
[2.2 Git 基础 - 记录每次更新到仓库](https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E8%AE%B0%E5%BD%95%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E5%88%B0%E4%BB%93%E5%BA%93)  book已经更新
![image](https://github.com/progit/progit2-zh/assets/33484052/68d534fe-c048-49d7-9a8c-faa1f770766c)
