### ISSUE TITLE
领取翻译任务 02-git-basics

### ISSUE THREAD

**Issue by tonghuix** [progit/progit2-zh#47]
我会尽快翻译第2章的如下章节：

02-git-basics/sections/viewing-history.asc
02-git-basics/sections/undoing.asc
02-git-basics/sections/remotes.asc
02-git-basics/sections/tagging.asc
02-git-basics/sections/aliases.asc

**Comment by devbean** [comment]
可以直接修改章节认领(https://github.com/progit/progit2-zh/issues/7)

**Comment by tonghuix** [comment]
没加到组里，是没法修改#7 Issue 的。。

**Comment by archermind** [comment]
@tonghuix 你去看看 #7 issue 我最后的评论，这个章节被另一个哥们给认领了，但是他好久没动静了，我本来也想认领这个章节的。如果你想翻译的话，建议你可以给 @alamier 发个mail确认一下。

**Comment by tonghuix** [comment]
哦好的，看来只能如此了
