### ISSUE TITLE
asciidoctor-pdf 生成的pdf中文没有显示

### ISSUE THREAD

**Issue by tonghuix** [progit/progit2-zh#48]
操作系统是Debian 8
除pdf之外，其他格式都是正常的。

这个问题我搜索了一下asciidoctor-pdf，可看到这个Issues[1]和相关讨论[2]。

[1] https://github.com/asciidoctor/asciidoctor-pdf/issues/82
[2] http://discuss.asciidoctor.org/How-to-generate-fonts-td2358.html

**Comment by archermind** [comment]
这个问题，我这边已经confirm了确实无法显示中文。

**Comment by archermind** [comment]
有解决方法吗？ @tonghuix 标题改的醒目一点，help wanted 让更多的人看到。

**Comment by tonghuix** [comment]
我没权限加。。。

目前依旧没找到解决办法， 我对asc不熟悉，不像markdown和pandoc那么熟悉。

**Comment by archermind** [comment]
at 错了， @devbean 请帮忙给这个issue 加  help wanted label

**Comment by weghst** [comment]
@archersmind 兄台 asciidoctor 中文排版有问题，你有找到解决方案吗？

**Comment by archersmind** [comment]
@weghst 时间太久我忘记了，不好意思。目前应该没什么问题了吧。
