### ISSUE TITLE
章节「5.2 分布式 Git - 向一个项目贡献」中对源自 Tim Pope 的提交信息模板的翻译可能不够准确，

### ISSUE THREAD

**Issue by Netheril** [progit/progit2-zh#481]
本书第 5.2 章中包含一个对源自 Tim Pope 的提交信息模板的翻译，其中第二段译文如下：

> 如果必要的话，加入更详细的解释文字。在大概 72 个字符的时候换行。
> 在某些情形下，第一行被当作一封电子邮件的标题，剩下的文本作为正文。
> 分隔摘要与正文的空行是必须的（除非你完全省略正文），
> 如果你将两者混在一起，那么类似变基等工具无法正常工作。

这段译文对应的原文是：

> More detailed explanatory text, if necessary.  Wrap it to about 72
> characters or so.  In some contexts, the first line is treated as the
> subject of an email and the rest of the text as the body.  The blank
> line separating the summary from the body is critical (unless you omit
> the body entirely); tools like rebase will confuse you if you run the
> two together.

这里最后一句的翻译感觉不够准确。参考 [Tim Pope 的原始博客](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) 可知，这里的含义实际上是「如果你将两者混在一起，那么在使用例如变基这样的工具时，它们会生成难以阅读的输出，让人困惑」。当前翻译容易让人误以为此时变基工具无法运行，建议相应修改。

**Comment by networm** [comment]
可以提交一个 Pull Request
