### ISSUE TITLE
PDF版本中的这条命令不在一行了

### ISSUE THREAD

**Issue by Sherry520** [progit/progit2-zh#489]
原文：
![image](https://github.com/user-attachments/assets/51b00d9c-11eb-4838-a215-ca6456477927)

译文：
![image](https://github.com/user-attachments/assets/2a7f49d6-0168-4a67-86ac-98e2f4c1f2df)

但是代码这部分[blob/master/book/10-git-internals/sections/refs.asc](https://github.com/progit/progit2-zh/blob/master/book/10-git-internals/sections/refs.asc)看起来没啥问题啊，和pdf对应版本的代码也一样[blob/2.1.67/book/10-git-internals/sections/refs.asc](https://github.com/progit/progit2-zh/blob/2.1.67/book/10-git-internals/sections/refs.asc?plain=1)
![image](https://github.com/user-attachments/assets/f71459b7-3a8b-4d5e-a997-89e581e03bb1)

PDF版本 2.1.67-1-g9e5df436, 2024-03-04

**Comment by networm** [comment]
这个无所谓，排版问题，到这儿正好换页了。

**Comment by Sherry520** [comment]
就是一开始我以为，下边那个hash是输出结果，结果没输出，看了原文才知道那也是输入



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 21:55 |
| 收件人 | ***@***.***> |
| 抄送至 | Yuhang ***@***.***>***@***.***> |
| 主题 | Re: [progit/progit2-zh] PDF版本中的这条命令不在一行了 (Issue #489) |

这个无所谓，排版问题，到这儿正好换页了。

**Comment by networm** [comment]
还是一样的问题，因为字体不同，一行的内容被自动换行了。

**Comment by Sherry520** [comment]
嗯嗯，那就这样吧，不动了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 22:03 |
| 收件人 | ***@***.***> |
| 抄送至 | Yuhang ***@***.***>***@***.***> |
| 主题 | Re: [progit/progit2-zh] PDF版本中的这条命令不在一行了 (Issue #489) |

还是一样的问题，因为字体不同，一行的内容被自动换行了。
