### ISSUE TITLE
这个翻译的不文明

### ISSUE THREAD

**Issue by Sherry520** [progit/progit2-zh#494]
附录B中[libgit2](https://github.com/progit/progit2-zh/blob/master/book/B-embedding-git/sections/libgit2.asc#libgit2)，翻译太粗俗了

原文：
![image](https://github.com/user-attachments/assets/49ad6358-c2cb-449f-a39a-cc127680264d)

译文：
![image](https://github.com/user-attachments/assets/a9f89a10-45a2-4392-9ecb-f3360ad1ca67)

**Comment by Geno1024** [comment]
painful 翻译为“蛋疼”我认为没有问题（

**Comment by networm** [comment]
你可以给个更好的建议看看
