### ISSUE TITLE
devbean 如果你太忙的话，可以换一个或者加一个人为collaborator吗？

### ISSUE THREAD

**Issue by archermind** [progit/progit2-zh#50]

**Comment by archermind** [comment]
每天上Github来处理一下PR和Issue 应该不是什么问题吧？

**Comment by devbean** [comment]
我也想增加合作者，看谁有时间来协作管理一下，不过这个项目不是我的，我没有权限增加，需要与 progit 联系下

**Comment by tonghuix** [comment]
加上我吧，最近我用Github比较频繁

**Comment by archermind** [comment]
@tonghuix 那你联系一下progit的人，cc上 @devbean OK ？

**Comment by tonghuix** [comment]
好，我看看怎么联系一下。

**Comment by networm** [comment]
我有时间来协作管理，加我一个吧！

**Comment by devbean** [comment]
正在联系，现在没有回复

**Comment by archermind** [comment]
@networm 大家最起码要贡献一些东西，得到这个群组里大部分人认可之后再作为collaborator吧？

**Comment by networm** [comment]
嗯，是的，我之前翻译了几篇，一直没推送，现在去处理一下。

**Comment by archermind** [comment]
各位，我们还是先让 @tonghuix 成为collaborator 。之后再根据需求调整，好吗？

**Comment by networm** [comment]
@archermind 没问题！

**Comment by oldsharp** [comment]
Maybe this thread helps: https://github.com/progit/progit2/issues/130
So there's 2 collaborators so far?  @devbean @leo108

**Comment by archermind** [comment]
目的达到了，close。Thanks everyone
