### ISSUE TITLE
Notepad++路径未显示完整

### ISSUE THREAD

**Issue by Sherry520** [progit/progit2-zh#525]
原文issue： https://github.com/progit/progit2/pull/1970
原文：
![image](https://github.com/user-attachments/assets/d583b78c-43bc-4d32-bd93-b31067e3bf3c)
中文：
![image](https://github.com/user-attachments/assets/c93d2506-3699-4800-9e2a-671740749d6b)

**Comment by Sherry520** [comment]
解决不了：
可能也是和中文有关系，把/全都换成\，也不行。生成的pdf就会显示出`+\+`
![image](https://github.com/user-attachments/assets/98ee4639-c6ef-4dbd-a70c-8757ebb933a9)

**Comment by networm** [comment]
这种需要翻解析的代码
