### ISSUE TITLE
关于章节认领的时效问题

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#53]
从 Progit 第二版英文版正式发布开始（大概是2014年11月份）我就开始关注本项目了，但是有很多人认领了并没有翻译，或者说是按时翻译；问题现在已经过去半年了，所以我觉得那个 [章节翻译认领 · Issue #7 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/7) 已经失去时效了。

我现在的策略是以现在的版本为基础，跳过已翻译的章节，并按顺序依次翻译，然后将其提交到我自己所在的分支；在推送前我会拉取一下官方翻译库 [progit/progit2-zh](https://github.com/progit/progit2-zh)，手动进行一次拉取，并将自己的分支合并至官方库的 master 分支，如果合并冲突，我会去掉冲突的章节，新建一个分支，推送并提 Pull Request 到官方库。

同时我认为多个人翻译同一个章节并不会有问题，本来翻译这个东西讲究的就是信达雅，我认为翻译要经过好几轮：第一轮粗译、第二轮审校、第三轮审校，后翻译完成的人做审校的效果更好，因为对本章的英文原文了解地更深入，对中文也有自己的思考。

**Comment by tonghuix** [comment]
不是的，翻译本身也讲求效率，如果多人翻译同一章节会导致要在多个版本之间大量操作，就如同你需要解决冲突的问题，这等于说每个翻译者都要解决冲突，而每次解决冲突都可能带来新的冲突。这就是翻译和写代码的不同。

如果可能的话，可以采用翻译平台的办法，比如用 Transifex 。可以用 po4a 工具将文档转换成 po 文件，会把章节文件打碎成一段一段来处理，这样冲突就比较小了，然后再发到 Transifex 这种平台，可以有效解决多人协作翻译的冲突问题。我用这方法试过 Latex 文件和 Markdown 文件，还没试验过 Asciidoc 文件。

另一方面，为了保证文章风格的一致性，以及审阅和修改的便捷性。一节一个人来翻译，我觉得是比较合适的粒度。

**Comment by networm** [comment]
我的意思并不是指多个人翻译同一章节，而是说多个人翻译，有一个人提交后，其他人并不提交自己的翻译，而是在其基础上，修正翻译内容、做审校。
