### ISSUE TITLE
翻译计划

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#54]
说来有些惭愧，《ProGit》之前读过第一版，后来2014年11月《ProGit》第二版正式发布后用了不到一个月的时间读完，就想要把这本书翻译一下，但是还是因为太懒了，拖到现在也没翻译。
最近有一些空闲时间，想要将其全部翻译完成，方便后来人，说实话，第二版比第一版好很多，有很多地方讲得比地一版细致得多，而且多讲了很多内容，比如说如何协作。

也就是说我会翻译所有章节，所以 @ 了所有认领章节的人。

初步计划：
version1：基于现有版本，翻译完剩余所有未翻译的部分，此为初译。
version2：同时参考英文版最新版与中文版第一版，校对内容，同时统一整理所有用词，例如“您”“你”问题。
version3：开始润色，将长句打断成短句，尽量使其信达雅。

用时：
version1：按照每天 3-5 篇的速度，刚刚统计的结果是还剩 58 篇，大概需要 20 天。
version2：初步预估，10 天。
version3：这个我认为需要协作，不确定天数。而且这一部分可作日后维护更新的内容。

问题：
什么时候进入主版本？
第一版翻译过程中；第一版翻译完成；第二版处理完成；第三版处理完成；应选择哪个阶段进入主版本？

用词问题在哪个阶段改
建议统一放到第二版处理，翻译的时候心无杂念比较好。

不知道大家有什么建议意见呢？

**Comment by networm** [comment]
@Jun995 @Qunero @devbean @leo108 @datawolf @shuaishuai @Geno1024 @kuuyee

**Comment by leo108** [comment]
不好意思，最近公司事情比较多，我之前认领的章节你可以重新认领翻译

**Comment by networm** [comment]
OK，好的，其实我的意思是说要认领所有章节，所以 @ 了你们全部认领章节的人

**Comment by tonghuix** [comment]
不建议一个人完成，还是多人协作吧。

**Comment by networm** [comment]
我觉得多人协作也不错，但问题是接下来的20天内会有人协作吗？如果没有的话那就参与第二阶段与第三阶段吧，特别是第三阶段，时间可能会很长，是个长期工作。

**Comment by Geno1024** [comment]
我高考考完啦！

**Comment by devbean** [comment]
个人认为你可以先选没有人正在翻译的章节进行翻译，免得做了无用功。如果先把所有无人认领的章节全部翻译完毕，再去通知每个人就可以了。非要加上一个期限，这就是工作，而不是兴趣了，不知道有多少人会愿意参与一个有期限压力的工作。在你一次性翻译很多文字之后，除非自己非常有把握，否则还是建议由别人再去审核之后再合并，否则翻译稿中已经很难再找出与原来的英文相对应的部分。

**Comment by networm** [comment]
@devbean 嗯，了解。
这不是工作，我只是觉得我给自己加一个期限不让自己烂尾，其他人并不需要当工作。
那我准备第一版与第二版都做完再合并；其实本来英文版的已经更新很多了，我的建议是直接用英文的最新版与翻译完的进行审校。

**Comment by networm** [comment]
@Geno1024 恭喜！

**Comment by archermind** [comment]
@networm 我同意 @devbean 的意见，请先翻译那些没人认领的章节。然后通知那些没有动静的小伙伴们，你觉得呢？

**Comment by networm** [comment]
@archermind 没有问题，我已经用邮件通知所有认领章节的人了；可能你并没在那个列表里，所以你没收到邮件。

**Comment by archermind** [comment]
@networm 不要太猛，给其他同学一点机会。

**Comment by networm** [comment]
@archermind 机会已经留了半年了，那个章节认领列表应该是在 2014 年 11 月左右就大概定下来了。我可一直有关注这个项目的翻译进度的！一个月内怎么也得看个几次，没什么变化啊！

**Comment by tonghuix** [comment]
流程也有点小问题。我认为谁要认领就发个新Issue表明自己的计划，之后就可以开始翻译了。
其他人看到Issue就可以选择避开或者准备Review这个翻译。

翻译好之后再通过 Review PR 和合并，然后close这个issue。这样这个流程就清晰了，也避免了刚开始的那种乱象。

**Comment by networm** [comment]
@tonghuix 解释一下
首先，我会先翻译无人认领的章节，再翻译有人认领的章节。
其次，我认为在我翻译完成之前，应该不会有很多人翻译导致冲突，如果有任何冲突全交给我来解决即可。

**Comment by tonghuix** [comment]
我的建议是你先发你愿意认领的章节，发出issuse来，这样也方便其他人协作，减少你后期处理冲突的工作量。

**Comment by networm** [comment]
以下是现在无人认领的所有章节，我都认领了，还需要单独提出一个 issue 吗？@tonghuix @devbean @archermind 

04-git-server
1-git-server
sections/generating-ssh-key
sections/git-daemon
sections/git-on-a-server
sections/gitlab
sections/gitweb
sections/hosted
sections/protocols
sections/setting-up-server
sections/smart-http

09-git-and-other-scms
1-git-and-other-scms
sections/client-hg
sections/client-p4
sections/client-svn
sections/client-tfs
sections/import-custom
sections/import-hg
sections/import-p4
sections/import-svn
sections/import-tfs

10-git-internals
1-git-internals
sections/environment
sections/maintenance
sections/objects
sections/packfiles
sections/plumbing-porcelain
sections/refs
sections/refspec
sections/transfer-protocols

1-git-other-environments
sections/bash
sections/eclipse
sections/guis
sections/powershell
sections/visualstudio
sections/zsh

**Comment by tonghuix** [comment]
我认领第一章和第四章吧
最近可能做一些工作，我一会发个Issue出来

**Comment by networm** [comment]
@tonghuix OK，我刚刚开始翻译第四章，那我现在去翻译第九章。

**Comment by archermind** [comment]
@networm 我最近才关注的，你说的也有道理，确实空闲太久了。

**Comment by archermind** [comment]
@networm 你之前的计划是，先全部粗略翻译完推上去，然后再一遍一遍的打磨，精细，是这样吗？

如果是的话，恐怕这样的行不通，因为git 那边会定期来拉我们的版本，生成电子书，放到这里 http://git-scm.com/book/zh/v2[] 所以，我们要尽可能的保证推送上去内容的质量，否则在完毕之前，读者就会读到半成品。这是非常不好的，你说呢？

**Comment by Geno1024** [comment]
@networm 作为刚刚变成非高三党的高三党，我强烈反对的“先全部粗略翻译完再仔细打磨”的做法，因为有些东西，你一写下去就很难再更改它，可以理解为定性思维吧，想到那方向上了那么再改方向是很难的。

我们英语老师也说过她帮别人改作文也只能修改几个词，可以将文章比作屋子吧，想改结构的话房子一定得倒掉，即使只是改几块砖也是得依照原来的布局去略微改装，不然会很不协调的还不如不要改。

**Comment by tonghuix** [comment]
@Geno1024 说的很在理啊！

**Comment by networm** [comment]
@archermind 我的计划是先粗略翻译完推送到我自己的仓库中，然后再一遍一遍的打磨，精细，打磨完后的版本再发送 Pull Request 合并到 progit2-zh 仓库中。

**Comment by networm** [comment]
@Geno1024 写作文是生成一样东西，而翻译是将已有的文字转换为另一种语言；另外，我不觉得会有定性思维，我翻译完后再去阅读《ProGit 中文版 第一版》还会有新的感悟，在做对比时会思考这句话到底翻译成什么样子比较合适。

我觉得你们不用在意过程，在我最终提交 Pull Request 时如果觉得有问题，那对应的整章翻译我都不会提交，回去重改。

**Comment by Lax** [comment]
之前认领但一直未完成的章节，也重新认领吧。

**Comment by networm** [comment]
我觉得那个[章节翻译认领 · Issue #7 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/7) 应该允许所有人编辑，这样的话就不需要协调了，直接就能认领。

**Comment by macrov** [comment]
我想参加，但是一定要用git搞么？http://www.transifex.com/这些翻译平台我觉得很不错

**Comment by networm** [comment]
@macrov 这是一本关于 Git 的书，当然要用 Git 搞！

**Comment by networm** [comment]
翻译 version 2 完成，已全部提交 Pull Request。
