### ISSUE TITLE
认领第一章和第四章的翻译

### ISSUE THREAD

**Issue by tonghuix** [progit/progit2-zh#56]
如#54 所言，会翻译+教对第一章，然后是第四章。

**Comment by networm** [comment]
@tonghuix 有没有进度更新啊，提交就算。

**Comment by tonghuix** [comment]
前一段时间略忙，今天开始校对第一章。

**Comment by networm** [comment]
@tonghuix 嗯，加油！

**Comment by networm** [comment]
@tonghuix 忘了提醒你了，你的第四章已经分出去了：[正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68)，因为我看到你都没有 Fork 这个项目，所以昨天就分配给别人了，你要是想要继续翻译的话可以选剩余未翻译的章节。

**Comment by tonghuix** [comment]
没关系，我在review和校对第一章，第四章分出去没问题

**Comment by networm** [comment]
@tonghuix 好的！

**Comment by networm** [comment]
@tonghuix 关闭所有认领 Issue，统一到 [正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68)
