### ISSUE TITLE
认领第九章、第十章、附录A、附录B的翻译

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#57]
参见
[翻译计划 · Issue #54 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/54)
[翻译 version 1 进度 · Issue #55 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/55)

其它的章节会在翻译完成此部分时继续翻译，同时会发邮件到对应的人并提 Issue @ 对应的人。

**Comment by oldsharp** [comment]
Hi, thanks for the participation.
Currently I am working on the translation of chapter 10 (see comments in #7 ).
Collaboration is welcomed.  Maybe we can share translate tasks of chapter 10 with each other?
We can discuss and update progress in this thread :-)

**Comment by networm** [comment]
@oldsharp 嗯，可以，我会先跳过第十章，先翻译其他章节。

**Comment by oldsharp** [comment]
@networm Thanks.

**Comment by networm** [comment]
@oldsharp [翻译计划 · Issue #54 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/54)

**Comment by oldsharp** [comment]
@networm I see. Will update my progress with you.

**Comment by networm** [comment]
@oldsharp 是不是没有中文输入法？

**Comment by oldsharp** [comment]
@networm Yes I have.  Just personal habit.  Maybe this can help progit guys to understand what's happening here, too :-)

**Comment by networm** [comment]
@oldsharp OK, I know.

**Comment by morstar** [comment]
@oldsharp How about share the chapter 10 with you?

**Comment by networm** [comment]
我觉得在这儿说英文没什么用，Progit 那帮人应该不会关心咱们这儿的进度，他们应该只会关心翻译完没有

**Comment by networm** [comment]
这么多个翻译的项目组，天天看讨论不疯了？

**Comment by morstar** [comment]
也是，issue #7 里面附录好像都有人认领了，想认领 第九、第十章节中未翻译小节。
@networm 是否可以认领09-git-and-other-scms/sections/import-custom.asc

**Comment by networm** [comment]
@morstar 虽然认领了，但暂时应该还没翻译，你可以先翻译附录A

**Comment by networm** [comment]
@morstar 我正在翻译第九章 @oldsharp 正在翻译第十章，在上面申请的

**Comment by networm** [comment]
@morstar 09-git-and-other-scms/sections/import-custom.asc 如果你认领这节，那我就会跳过这个。

**Comment by oldsharp** [comment]
@morstar 乐意之至。（为避免困扰，我会使用中文参与讨论。对之前表示抱歉。）
如你所见，除掉已经 merge 的序言小节，第十章剩余部分共计8个小节，分别是：

  1. include::sections/plumbing-porcelain.asc
  2. include::sections/objects.asc
  3. include::sections/refs.asc
  4. include::sections/packfiles.asc
  5. include::sections/refspec.asc
  6. include::sections/transfer-protocols.asc
  7. include::sections/maintenance.asc
  8. include::sections/environment.asc

鉴于目前 @networm 正在翻译第九章，我们可以先平分这八个小节。由我翻译前四个小节。 @morstar 你完成手头的其他翻译任务后，可以着手翻译第十章的后四个小节。是否可以？
这个安排可以根据各人进度，再作调整。
@networm 完成第九章后，也可以加入我们。

我会及时在这里 update 进度。

一个小建议：对于同一章不同小节间的协作翻译，我们可以相互审视各自的翻译文本，力求行文风格的接近。

另，很高兴看到最近这个项目活跃度剧增，之前一度沉寂 ;-)

**Comment by networm** [comment]
@oldsharp 
> 活跃度剧增

囧

**Comment by morstar** [comment]
@oldsharp 我手头没有任何其他翻译项目，现在着手翻译第十章后四个小结，我也会随时在这里更新我的进度。关于互相审视翻译文本的建议非常好，不过我们可以先各自翻，再更新 version 2。
@networm 暂时先不认领第九章，如果第十章翻译完成后，还有未完成第九章，很愿意认领。

**Comment by oldsharp** [comment]
进度更新：第十章第一小节 plumbing-porcelain 已经完成，见 #59.

**Comment by networm** [comment]
@oldsharp Good Job!
