### ISSUE TITLE
第三章有人认领吗？没人领的话，我认领第三章了！<不要跟我抢啊... :P>

### ISSUE THREAD

**Issue by archermind** [progit/progit2-zh#58]
@networm @tonghuix @devbean

**Comment by archermind** [comment]
我会首先校对已翻译部分，然后翻译剩余的部分
@Jun995 好久没见你进度更新了，你建议我去翻译吗？

**Comment by Jun995** [comment]
你翻吧

**Comment by archermind** [comment]
@Jun995 谢谢！

**Comment by networm** [comment]
@archermind 第三章剩余的部分我已经翻译完了，不过这不影响你再翻译一遍，[Commits · networm/progit2-zh](https://github.com/networm/progit2-zh/commits/first-translation)

**Comment by archermind** [comment]
@networm 我正在review你的 pulls #52

**Comment by networm** [comment]
@archermind 第三章的其他部分没有提 Pull Request，而是在我个人的仓库中；需要单独把第三章的内容提一个 Pull Request 过来还是等我把剩余的所有东西翻译完再说？

**Comment by archermind** [comment]
@networm  等等，等我们把你PR #52 review完先。OK？

**Comment by networm** [comment]
@archermind 关闭所有认领 Issue，统一到 [正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68)
