### ISSUE TITLE
关于章节标题内的术语注解问题

### ISSUE THREAD

**Issue by oldsharp** [progit/progit2-zh#66]
此 issue 旨在讨论章节标题内的术语注解问题。

一般而言，在原文中出现专业术语时，译者倾向于对其作一注解，即在译文后紧跟一括弧，内注明原文单词，以助读者理解。

[《Pro Git》第一版简体中文翻译][00]里对这个问题的处理，稍显混乱。

其中，第六章与第九章尤为突出：

![v1-06](https://cloud.githubusercontent.com/assets/980500/8122830/968cfdfe-10f2-11e5-8ea9-2480e5263004.PNG)
![v1-09](https://cloud.githubusercontent.com/assets/980500/8122837/af20420e-10f2-11e5-9584-57efc7a9ab07.PNG)

可以看到，有些小节标题作了英文注解，有些只保留中文，有些直接保留了英文原文。

我们希望对此作改进，至少做到统一。

--------

一种意见认为，**作为标题，有必要快速向读者阐明概念；因此，（如有必要）在标题内即可加入英文注解**。举例：

[原文][01]：
```
1  [[_plumbing_porcelain]]
2  === Plumbing and Porcelain
3
4  ...(ignored)...
5  These commands are generally referred to as ``plumbing'' commands, and the more user-friendly commands are called ``porcelain'' commands.
6  ...(ignored)...
```

译文：
```
1  [[_plumbing_porcelain]]
2  === 底层命令（plumbing）和高层命令（porcelain）
3
4  ...(ignored)...
5  这部分命令一般被称作“底层”命令，而那些更友好的命令则被称作“高层”命令。
6  ...(ignored)...
```
其中，line 5 是正文中首次出现 plumbing 和 porcelain 处，下同。

--------

另一种意见认为，**章节标题约定不作英文注解，只出现中文字样；如有必要，在正文中第一次出现处作注解**。举例：

原文：
如上例。

译文：
```
1  [[_plumbing_porcelain]]
2  === 底层命令和高层命令
3
4  ...(ignored)...
5  这部分命令一般被称作“底层（plumbing）”命令，而那些更友好的命令则被称作“高层（porcelain）”命令。
6  ...(ignored)...
```

--------

目前可以统一的是，**如若已作了注解，则以第一次出现处为准，不应重复**。

--------

请各位不吝抒发意见，希望最终能达成共识，并作相应约定。个人觉得有助于项目内部的标准化。谢谢。

注：问题背景与出处见 https://github.com/progit/progit2-zh/pull/63#discussion-diff-32081385 。

[00]: http://git-scm.com/book/zh/v1/ "Pro Git zh v1"
[01]: https://raw.githubusercontent.com/progit/progit2/master/book/10-git-internals/sections/plumbing-porcelain.asc "Pro Git v2"

**Comment by morstar** [comment]
感谢 @oldsharp 的总结，我的意见是作为一些容易混淆的概念或英文概念比中文翻译更多的被人理解的情况下，同时提供英文注释和中文翻译可以让读者更快的理解。尤其作为标题，非常有必要以最快的速度让读者理解。

**Comment by oldsharp** [comment]
我更倾向于在正文内做注解，个人感觉这样更优雅 ;-)

一个思路：我们可以试着找一找类似的计算机类英文著作的中文翻译，看他们是如何处理的。如果是成熟的正式出版物，则更好、更权威，因为它们通常有专业的计算机相关文学编辑把关，我们可以借鉴现成经验。

**Comment by morstar** [comment]
作为一个公益项目，我只是站在一个实用主义的读者角度，觉得这样可以照顾到更多的人。

**Comment by networm** [comment]
@oldsharp @morstar 我看了一眼手头的几本英文翻译成中文的书，大部分都不会在标题用英文注释；而我本身也更倾向于在正文内首次出现的地方使用注解，读者如果知道英文，自然会用英文搜索；另外，我觉得光看一个标题什么都理解不了。。。

**Comment by devbean** [comment]
纸质书的翻译与电子书有些区别：纸质书每页内部不会产生交叉链接，但是电子书存在这个可能，这也是本问题出现的背景。如果翻译标题，则需要将正文内部的所有交叉链接全部翻译。通常在正式文本中，标题都是翻译的，但是这是建立在原术语有公认的翻译标准，而我们的问题是不存在这种官方标准，因此翻译标题更可能造成读者的困惑（试想读者在查阅中文版时一定是在读英文发生困难时，比如，当他看到 rebase 这个命令而不知道如何使用时，他会来翻阅本书，如果翻译标题，他会找不到 rebase 这个词究竟在哪一章）。因此，个人建议是保留原标题，在正文进行翻译。（不知道这种翻译有没有相应的国家标准，有出版界的朋友可以咨询下）

**Comment by networm** [comment]
@devbean 我觉得这本书本身不是手册，如果读者需要的话直接看 git rebase --help 就可以了。
而且我认为读者的问题不是看到 rebase 怎么用，而是遇到需要将提交历史变成直线的需求再来翻书，这时看目录就能找到，并不需要提前知道 rebase 这个命令啊！

**Comment by morstar** [comment]
@devbean 同意关于“不存在官方标准”的判断。其实我的个人想法更过分，我更倾向于直接使用诸如 pull request 或 merge 等词汇，因为这些都是直接拿来用的命令，翻译了反而造成麻烦。拉回来说，现在的问题是一定要照顾到交叉连接吗？标题的意义就是给所有人一个线索，所以在某些不能达成“官方判断”或共识的情况下，建议翻译标题并且保留英文原文。
@networm 我觉得做这个电子书，不要加入过多的个人判断，本书是不是手册也不重要。重要的事尽量考虑到各种各样的读者：有些读者看英文帮助力不能及来翻中文版，直接一头雾水；有些想迅速了解某个命令的用法，如果都翻译为中文标题也是很麻烦。

**Comment by oldsharp** [comment]
@devbean

------
 
> 如果翻译标题，则需要将正文内部的所有交叉链接全部翻译。

这里你可能有些小误会，这里我们讨论的主题纯粹与翻译风格有关，并不涉及诸如交叉链接和锚记哦。

因为在 raw file 里面锚记和章节标题是独立的。

例如，有[原文][01]如下：
```
1  [[_plumbing_porcelain]]
2  === Plumbing and Porcelain
3
4  ... (rest contents) ...
```
上述 snippet 中，line 1 是[锚记][02]；line 2 是[二级段落标题][03]；余下为正文。

假设译文是：
```
1  [[_plumbing_porcelain]]
2  === 高级命令（plumbing）和低级命令（porcelain）
3
4  ...(rest translated contents)...
```

那么，后续译文中若想引用到该处，只需在 raw file 中设置交叉连接 `<<_plumbing_porcelain>>`，build 全书后，读者在该处看到的是 `高级命令（plumbing）和低级命令（porcelain）`。

关于锚记不作翻译的约定，我已另行提交至 PR #67 ，请审阅。不提。

------

> 试想读者在查阅中文版时一定是在读英文发生困难时，比如，当他看到 rebase 这个命令而不知道如何使用时，他会来翻阅本书，如果翻译标题，他会找不到 rebase 这个词究竟在哪一章

这个场景可以（并且更适合）由**术语索引**解决——例如，读者通过查阅书籍附录中“术语索引”部分的 rebase 条目，得到 rebase 在全书中首次出现的页码。

期望读者通过章节标题（目录）查找术语，不甚合理。章节标题应是特殊的正文，不应是索引。我们只需考虑译文的信、达、雅，索引的事情，交给索引去做。

（我在翻译过程中遇到 raw file 中有三个括弧“((()))”的标注，猜测是术语索引相关用途，但查阅网络资料后，未有结果。此处有待验证。）

------

综上，你的建议
> 保留原标题，在正文进行翻译

我不能赞同 :-)

（ @networm @morstar 对你们的意见的 reply 也一并在上文陈述，就不再新开一帖。）

[01]: https://raw.githubusercontent.com/progit/progit2/master/book/10-git-internals/sections/plumbing-porcelain.asc "01"
[02]: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links "02"
[03]: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles "03"

**Comment by oldsharp** [comment]
早上抽时间完善了问题描述，各位可以重新看一下。

**Comment by networm** [comment]
@oldsharp 嗯，写得很全面，表示赞同！
