### ISSUE TITLE
正式版 翻译进度

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#68]
下面是我整理的当前进度（20150611 SHA-1：57d83a594eb8c03cd10c04331076cd81aa818b4a）
每章的索引小节也包括在内，如果这一章所有小节的内容全部翻译完成，则会在这一章前打勾。

进度统一在这里管理，包括章节认领，每个人认领后都有一个截止日期，在截止日期后其他人都可任意认领。

同时将 @networm 的 v1 版本进度整合进来，这样方便大家查看整体进度。
- [x] preface @networm

01-introduction
  - [x] 1-introduction
  - [x] about-version-control
  - [x] history
  - [x] basics
  - [x] command-line
  - [x] installing
  - [x] first-time-setup @tonghuix 20150619 @networm v1
  - [x] help

02-git-basics
  - [x] 1-git-basics
  - [x] getting-a-repository
  - [x] recording-changes
  - [x] viewing-history
  - [x] undoing @networm v1
  - [x] remotes @networm v1
  - [x] tagging @networm v1
  - [x] aliases @networm v1

03-git-branching
  - [x] 1-git-branching @archermind 20150619
  - [x] nutshell @archermind 20150619
  - [x] basic-branching-and-merging @archermind 20150619 @networm v1
  - [x] branch-management @archermind 20150619 @networm v1
  - [x] workflows @archermind 20150619 PR
  - [x] remote-branches @archermind 20150619 @networm v1
  - [x] rebasing

04-git-server
  - [x] 1-git-server
  - [x] protocols @wych42 20150618 PR
  - [x] git-on-a-server @neo1218 20150618 PR
  - [ ] generating-ssh-key @oranzhang 20150618 PR
  - [ ] setting-up-server @oranzhang 20150618 PR
  - [x] git-daemon @branchzero 20150619 PR
  - [x] smart-http @branchzero 20150619 PR
  - [ ] gitweb @sanddudu 20150620 PR
  - [ ] gitlab @neo1218 20150618 PR
  - [x] hosted @branchzero 20150620 PR

05-distributed-git
  - [ ] 1-distributed-git @xiaket 20150620 PR
  - [ ] distributed-workflows @leshiv 20150620 PR
  - [ ] contributing @networm v1
  - [ ] maintaining @secondwtq 20150622 PR

06-github
  - [x] 1-github @devbean 20150619 PR
  - [x] 1-setting-up-account @devbean 20150619 PR
  - [x] 2-contributing @sanddudu 20150618 PR
  - [ ] 3-maintaining @qinglangee 20150621 PR
  - [ ] 4-managing-organization @zwpaper 20150619 PR
  - [x] 5-scripting @networm v1

07-git-tools
  - [x] 1-git-tools
  - [x] revision-selection
  - [ ] interactive-staging @networm v1
  - [ ] stashing-cleaning @networm v1
  - [ ] signing @networm v1
  - [x] searching
  - [ ] rewriting-history @networm v1
  - [ ] reset @networm v1
  - [ ] advanced-merging @networm v1
  - [ ] rerere @networm v1
  - [x] debugging
  - [ ] submodules @networm v1
  - [x] bundling
  - [ ] replace @Gnahceg 20150620 PR
  - [x] credentials

08-customizing-git
  - [ ] 1-customizing-git @spacewander 20150622 PR
  - [ ] config @spacewander 20150622 PR
  - [ ] attributes @spacewander 20150622 PR
  - [ ] hooks @spacewander 20150622 PR
  - [ ] policy @spacewander 20150622 PR

09-git-and-other-scms
  - [ ] 1-git-and-other-scms @networm v1
  - [ ] client-svn @networm v1
  - [ ] client-hg @networm v1
  - [ ] client-p4 @networm v1
  - [ ] client-tfs @networm v1
  - [ ] import-svn @networm v1
  - [ ] import-hg @networm v1
  - [ ] import-p4 @networm v1
  - [ ] import-tfs @networm v1
  - [ ] import-custom @networm v1

10-git-internals
  - [x] 1-git-internals
  - [x] plumbing-porcelain @oldsharp
  - [ ] objects @oldsharp 20150619 PR
  - [ ] refs @oldsharp 20150619 PR
  - [ ] packfiles @zwpaper 20150619 PR
  - [ ] refspec @morstar 20150619 PR
  - [ ] transfer-protocols @zwpaper 20150624 PR
  - [ ] maintenance @networm v1
  - [ ] environment @qinglangee 20150624 PR

A-git-in-other-environments
  - [ ] 1-git-other-environments @networm v1
  - [x] guis
  - [ ] visualstudio @liwenzhuo 20150618 PR
  - [x] eclipse @WispZhan 20150618 PR
  - [ ] bash @WispZhan 20150618 PR
  - [x] zsh @branchzero 20150619 PR
  - [x] powershell @branchzero 20150620 PR

B-embedding-git
  - [x] 1-embedding-git
  - [x] command-line
  - [ ] libgit2 @Geno1024 20150619 PR
  - [ ] jgit @Geno1024 20150619 PR

C-git-commands
  - [x] 1-git-commands @banxi1988 20150620 PR

**Comment by networm** [comment]
@devbean @tonghuix @archermind @oldsharp @morstar @Geno1024 @leo108 

@Lax @datawolf @VirgilMing @TenphyX @memeormatt

我在项目 Network 视图中看到你们之前都翻译了很多，不过并没有发送 Pull Request，是不是可以提交一下？

**Comment by Geno1024** [comment]
@networm 我在润色，等到 ultimatum 就 commit + push + pull request 啦啦～～～

**Comment by networm** [comment]
@Geno1024 加油！

**Comment by Geno1024** [comment]
@networm 谢谢。高考完没事干，恰好做这个玩玩。考驾照又年龄不足。（怎么叨起家常来了

**Comment by archermind** [comment]
@networm  我在翻译chapt 3 ， 并且处理了一下 该项目的其他事务，比如我刚刚发的issue #70

**Comment by networm** [comment]
@archermind 很好，我准备过段时间再编译呢

**Comment by networm** [comment]
@Geno1024 可以找些有意思的东西玩玩

**Comment by neo1218** [comment]
@networm  可以认领04章git-on-a-server 和 gitlab吗？, 正好最近结课了,

**Comment by networm** [comment]
@neo1218 已添加！

**Comment by neo1218** [comment]
ok！

**Comment by wych42** [comment]
可以认领02-undoing一节吗？

**Comment by networm** [comment]
@wych42 可以

**Comment by networm** [comment]
@wych42 能不能换个，那个我第一版翻译完了，最好换个无人认领的

**Comment by liwenzhuo** [comment]
可以认领10.2 Git Objects吗？

**Comment by networm** [comment]
@liwenzhuo 抱歉，能换一章吗？那章有人翻译了

**Comment by spacewander** [comment]
08-customizing-git 有人要不？没有我就认领哈
另外，认领之后是不是统一要在6/19号完成呢？因为我工作日的时候事儿也不算少，只有周末较有空，所以认领后可能得拖到下周一22号才能合并……

**Comment by liwenzhuo** [comment]
@networm 10.3或者10.4呢？

**Comment by networm** [comment]
所有标记 @networm v1 的表示我已经翻译我的第一版了，我会在第二版时合并入主干。

**Comment by wych42** [comment]
@networm  那就4-1 protocols吧

**Comment by networm** [comment]
@spacewander 可以，那你一定要在22号前完成哦！

**Comment by networm** [comment]
@liwenzhuo 第10章都有人翻译了，你看下上面选个没人翻译的章节？

**Comment by networm** [comment]
@wych42 可以啊

**Comment by spacewander** [comment]
@networm 
Ok，等我的pr吧。

**Comment by networm** [comment]
@wych42 @spacewander 进度上都已经更新了，要按时完成哦！

**Comment by liwenzhuo** [comment]
@networm 还有哪些没有翻译的呢？

**Comment by networm** [comment]
@liwenzhuo 上面没打勾且后面未写 @networm v1 的表过还没有人翻译

**Comment by archermind** [comment]
@neo1218 发一个issue出来，让大家都知道，等 @networm 更新了之后，再close掉你开的issue

**Comment by liwenzhuo** [comment]
@networm 那A1.1或者A1.2呢？

**Comment by networm** [comment]
@liwenzhuo 附录A还没人翻译，你可以任选。

**Comment by networm** [comment]
@devbean @tonghuix @archermind @oldsharp @morstar @Geno1024 @leo108
我去 v2ex 上发了一个招募贴
[ProGit 2nd 中文版 翻译协作计划 - V2EX](http://v2ex.com/t/198736)

**Comment by liwenzhuo** [comment]
@networm 好的，那我先领A1.1和A1.2吧~

**Comment by networm** [comment]
@liwenzhuo 你还是打英文的章节名吧，我不知道A1.1 A1.2是哪个

**Comment by liwenzhuo** [comment]
@networm A1.1 Git in Other Environments - Graphical Interfaces 和A1.2 Git in Other Environments - Git in Visual Studio

**Comment by archermind** [comment]
@networm 很好，值得庆幸的是，感觉最近关注度越来越高了。

**Comment by networm** [comment]
@liwenzhuo A1.1 已经翻译完了，看上面的进度，你可以换一个其他的；A1.2 我已经给你加上了

**Comment by networm** [comment]
@archermind 嗯，是的，你别忘了你也有翻译任务的，要按时完成哦，过期的话就交给别人了！

**Comment by liwenzhuo** [comment]
@networm 好的，那就先A1.2吧

**Comment by networm** [comment]
@liwenzhuo 好的

**Comment by WispZhan** [comment]
附录 A 1.3 eclipse 
俘虏 A 1.4 bash
应该还没有人翻译吧。

**Comment by networm** [comment]
@WispZhan 还没人翻译，有截止日期的，你先挑一个翻译吧！

**Comment by WispZhan** [comment]
@networm 这两个都很短，就这两个吧。
附录 A 1.3 eclipse 
附录 A 1.4 bash

**Comment by networm** [comment]
@WispZhan 我的意思是截止日期也很短，20150622 前能翻译完吗？

**Comment by WispZhan** [comment]
@networm 没有问题，甚至今晚或者明早就能翻译完。

**Comment by liwenzhuo** [comment]
@networm 请问有什么稳定的方法加速git clone呢？clone的速度超级慢，加--depth都clone不下来
...

**Comment by TenphyX** [comment]
我之前提过PR，但是没有merge。最近工作很忙，实在是没时间做。第四章有人想继续翻就拿去吧。

Thanks & Regards,
Tengfei

**Comment by networm** [comment]
@WispZhan 可不要小看那些工作量啊，翻译起来再加上校对还是非常消耗时间的！

**Comment by networm** [comment]
@liwenzhuo 说实话，我也没找到更快的加速方式，我的建议是你让它慢慢在那儿克隆，只要维持30K/S的话大概半个多小时也能克隆完。

**Comment by oranzhang** [comment]
可以认领 generating-ssh-key， setting-up-server吗？

**Comment by networm** [comment]
@oranzhang 可以，截止日期是 20150618 哦，一定要在截止日期前完成的！

**Comment by oranzhang** [comment]
@networm 👌

**Comment by networm** [comment]
@oranzhang 已经把你加到进度表里了！

**Comment by WispZhan** [comment]
附录A的都比较短，没问题的，一片100+词，一篇 300+词 比 新闻还短。

**Comment by networm** [comment]
@WispZhan 一定要认真翻译的，这个东西还需要仔细参考第一版本的修改，你提交 Pull Request 后还需要大家一起审核的，如果翻译得不细心的话，这个审核过程可能会花费较长时间。

**Comment by sanddudu** [comment]
希望认领 06-2-contributing
另外 contributing 应该如何翻译，我个人认为可以使用 “贡献代码”

**Comment by Geno1024** [comment]
@sanddudu 同意 “贡献代码”。

**Comment by networm** [comment]
@sanddudu 可以的；但是 contributing 这个不一定要翻译为贡献代码，因为 Github 不光是可以存放代码，其他领域的模型、图片、声音什么的都有很多存放在这儿，所以我的建议是单独提一个 Issue，来讨论一下这个问题。我个人觉得叫“贡献”就很好。

**Comment by networm** [comment]
@TenphyX 我的建议是如果有时间的话能不能再仔细对照第一版润色一下，然后再提一个 Pull Request 出来，然后大家来审核一下呢；我觉得大部分都已经翻译完了，剩下的不多；再就是之前大家可能都太忙了，没时间管理 Pull Request。

**Comment by Geno1024** [comment]
@networm 对了还有一个问题，上头规定 ultimatum 了吗？还是说我们自己想加紧啦？

**Comment by networm** [comment]
@Geno1024 上头没规定这个，就是我觉得我们应该加紧了，不能再拖了，而且我每天全力翻译也只能做到 2 - 3篇，这些翻译起来都很费时间。

**Comment by networm** [comment]
@liwenzhuo 如果你克隆还是慢的话我可以给你共享一份我的仓库的压缩包，不过你需要修改 .git/config 文件中的 origin 为自己的地址。
链接: http://pan.baidu.com/s/1sj3GTL7 密码: zz8q

**Comment by branchzero** [comment]
可以的话，我领了04-git-server的 
git-daemon
smart-http
吧，试着翻译一下这两个

**Comment by networm** [comment]
@branchzero 好的，进度已经更新，截止日期是 2015.06.19，一定要按时完成啊！

**Comment by liwenzhuo** [comment]
@networm 已经发了pull request了~  名字是git_in_visual_studio

**Comment by networm** [comment]
@liwenzhuo 好的！

**Comment by branchzero** [comment]
@networm 收到，下午水完考试开始动手翻译。

**Comment by jsenjoy** [comment]
好像很多已经认领了啊

**Comment by networm** [comment]
@branchzero 好的！
@jsenjoy 还有好多没认领的，要不要先认领一节试试看？

**Comment by zwpaper** [comment]
认领一个 06-github-3-maintaining，但是貌似比较长，能再细分或者是我端午节的时候先翻译着，过完节汇报进度吗？

**Comment by networm** [comment]
@zwpaper 的确很长，要不你选个 06-github 4-managing-organization 这个？这个 5K，很短。
因为每个任务都是 3 天截止日期，如果时间不充裕的话可以翻译短的。

**Comment by zwpaper** [comment]
@networm OK, 那我就先试试 06-github 4-managing-organization 这个。

**Comment by networm** [comment]
@zwpaper 好的，我将你加入到进度表中，截止日期是 20150619，一定要在这儿之前提交。

**Comment by Gnahceg** [comment]
望认领 7.13 Git Tools - Replace ～～

**Comment by networm** [comment]
@Gnahceg 已添加，截止日期是 2015.06.20，一定要按时完成啊。

**Comment by banxi1988** [comment]
1-git-commands 还没有人认领, 那我来认领一下吧.

**Comment by networm** [comment]
@banxi1988 好的，截止日期是 2015.06.20，一定要按时完成啊。

**Comment by garyzhucode** [comment]
认领2 getting-a-repository

**Comment by networm** [comment]
@garyzhucode 你要认领的 getting-a-repository 已经翻译完成了，换一个章节吧？

**Comment by leshiv** [comment]
望认领 5.1 distributed-git，今晚开始～

**Comment by networm** [comment]
@leshiv 建议选择其中的一小节先翻译。

**Comment by leshiv** [comment]
@networm 嗯，先就 5.1 Distributed Git - Distributed Workflows

**Comment by networm** [comment]
@leshiv 好的，截止日期 2015.06.20，要按时完成并提交 Pull Request 的。

**Comment by adaiguoguo** [comment]
等端午有空再来领，目前对07的rerere，advanced-merging感兴趣

**Comment by networm** [comment]
@adaiguoguo 好的，我正在翻译 advanced-merging。

**Comment by jiayouxjh** [comment]
06-github 5-scripting 截止日期 2015.06.20

**Comment by networm** [comment]
@jiayouxjh 好的

**Comment by xiaket** [comment]
05-distributed-git-01-distributed-git  翻译已完成, 后面有空会继续提供翻译和review.

**Comment by networm** [comment]
@xiaket 好的，我们会审查的。

**Comment by branchzero** [comment]
@networm 翻译并且稍微润色了一下，已经PR了，请验收。

**Comment by networm** [comment]
@branchzero 嗯，好的，现在 PR 比较多，可能会花一些时间来审查，注意查收邮件吧，有审查意见都会有邮件通知的。

**Comment by networm** [comment]
@networm
@Geno1024
@archermind
@neo1218
@wych42
@liwenzhuo
@spacewander
@WispZhan
@TenphyX
@oranzhang
@sanddudu
@branchzero
@jsenjoy
@zwpaper
@Gnahceg
@banxi1988
@garyzhucode
@leshiv
@adaiguoguo
@jiayouxjh
@xiaket

这里还有几章没人认领，谁有空翻译一下？

**Comment by networm** [comment]
@archermind 你先把 03-git-branching workflows 翻译了吧，那章中其他的我都翻译完了第一版。

**Comment by archermind** [comment]
@networm OK

**Comment by branchzero** [comment]
04-git-server - hosted / A-git-in-other-environments - powershell
再搞点短的吧，长的没底。。。

**Comment by garyzhucode** [comment]
认领05-distributed-git 1-distributed-git

**Comment by networm** [comment]
@garyzhucode 已经加上了

**Comment by networm** [comment]
@branchzero 加上了，两个都分给你了。

**Comment by sanddudu** [comment]
认领 04-git-server-gitweb

**Comment by branchzero** [comment]
翻译完了，附到原先的 PR 上了。

**Comment by qinglangee** [comment]
06-github3-maintaining  还没人领吗，要是可以我就领了

**Comment by networm** [comment]
@qinglangee 好的，截止日期是 2015.06.20，要按时完成；另外，这一节有点长，你确定能按时完成吗？

**Comment by qinglangee** [comment]
@networm 我估计应该没什么问题，截止到 2015.06.21可以吗，保险点

**Comment by networm** [comment]
@qinglangee 好

**Comment by secondwtq** [comment]
我似乎来晚了... 还有可以分配的任务么

**Comment by networm** [comment]
@secondwtq 05-distributed-git maintaining 这个比较长，如果想翻译短的，明天有很多到期未完成的可以领取。

**Comment by Geno1024** [comment]
@networm Pull Request 还在列表中的算未完成吗？（话说貌似可以直接打@nm 来@你哎

**Comment by networm** [comment]
@Geno1024 已经提交 PR 的不算未完成；另外 nm 不是我，是另一个人。

**Comment by Geno1024** [comment]
@networm 嗯好的。然后我的意思是在刚开始输入这个评论的时候写@nm并回车就直接@你了。。。

**Comment by secondwtq** [comment]
@networm 貌似还不算最长的，这个问题倒不算很大，主要是我第一版书也才刚看到这个位置。

如果没人认领的话我就先翻译，截止日期放到周一。

**Comment by networm** [comment]
@secondwtq 如果能在周一前翻译完就你翻译，否则我翻译。

**Comment by networm** [comment]
@secondwtq 截止日期最晚是周一，从周一开始要做全面的审校工作。

**Comment by networm** [comment]
@garyzhucode 05-distributed-git 1-distributed-git 这章已经有人两天前提交 PR 了，比你认领还早，所以这个任务就先取消了。

[Translate 05-distributed-git 1-distributed-git by xiaket · Pull Request #102 · progit/progit2-zh](https://github.com/progit/progit2-zh/pull/102)

**Comment by networm** [comment]
@spacewander @oldsharp @morstar 你们身上的任务较多，如果感觉比较紧的话可以让其他人翻译一部分。

**Comment by zwpaper** [comment]
@networm 如果有不是特别长的任务空余，可以给我安排一下，我这几天还有时候翻译，可以在周一之前完成。

**Comment by oldsharp** [comment]
@networm 

10-git-internals plumbing-porcelain 已并入主干，烦请更新对应条目状态。

我目前正在翻译的章节是 10-git-internals refs， 在此重新认领，也请更新对应条目状态。

10-git-internals packfiles 目前 pending，若有其他志愿者愿意认领此章节，欢迎。
如若我完成 refs 小节后 packfiles 小节仍为 pending 状态，我会继续认领此小节。

谢谢！

**Comment by networm** [comment]
@zwpaper 只有一个  05-distributed-git maintaining 还没有人认领，不过这节较长，544 行；其他的章节需要等认领人反馈后才能重新指认，问题还没到期。

**Comment by networm** [comment]
@oldsharp 状态已更新，之前没注意到已合并到主干。

**Comment by networm** [comment]
@zwpaper 10-git-internals packfiles 你有兴趣翻译吗？如果有的话就将它重新指派给你。

**Comment by zwpaper** [comment]
@networm OK

**Comment by banxi1988** [comment]
Hi, 晚上才能翻译初稿.明天润色提交, OK 不?

**Comment by networm** [comment]
@Geno1024
@archermind
@neo1218
@wych42
@liwenzhuo
@spacewander
@WispZhan
@TenphyX
@oranzhang
@sanddudu
@branchzero
@jsenjoy
@zwpaper
@Gnahceg
@banxi1988
@garyzhucode
@leshiv
@adaiguoguo
@jiayouxjh
@xiaket
@qinglangee
@secondwtq
@oldsharp

现在只有一个 05-distributed-git maintaining 还没有人认领，不过这节较长，全文共 544 行，不知道有没有人可以帮忙翻译？

**Comment by networm** [comment]
@banxi1988 可以，不过这节较长，共 480 行，有问题的话现在就可以说。

**Comment by banxi1988** [comment]
@networm 没有问题的.

**Comment by secondwtq** [comment]
@networm 好的，我正在翻译 05-distributed-git maintaining，争取周一之前提交。

**Comment by networm** [comment]
我更新了一下进度显示，结尾有 PR 的表示已经提交了 Pull Request；而结尾是 :worried: 的表示还未完成。

**Comment by networm** [comment]
截至目前，还有 13 篇未翻译完成的章节。

**Comment by archermind** [comment]
@networm 不好意思，我这几天电脑坏掉，刚修理好，03章 workflows 我今天提上来

**Comment by networm** [comment]
@archermind 好的，只是确认一下。

**Comment by zwpaper** [comment]
@networm 10-git-internals packfiles 已发 PR

**Comment by networm** [comment]
@zwpaper Good Job!

**Comment by archermind** [comment]
@networm 03-workflows  马上发 PR

**Comment by banxi1988** [comment]
我的附录-C 翻译得差不多了。 @networm  不过还需要审查，及让大家评点修改。
比我想像的进度慢多了。。 😂

**Comment by networm** [comment]
@banxi1988 进度慢那是当然的，因为我已经翻译了其他章节，所以我才问你有没有问题！

**Comment by networm** [comment]
10-git-internals
  transfer-protocols
  maintenance
  environment

这三章暂时还没有人翻译，请问有人可以认领吗？

**Comment by zwpaper** [comment]
@networm 明天我才能有时间，明天我先处理一下 PR，然后要是还有没人翻译的，我就翻译。

**Comment by networm** [comment]
@zwpaper 还是没有人翻译，你现在可以翻译了。

**Comment by networm** [comment]
@jiayouxjh 06-github 5-scripting 任务已经超时，分配给其他人。现在有人可以翻译这章吗？

**Comment by qinglangee** [comment]
我翻译下　10-git-internals environment吧

**Comment by networm** [comment]
@qinglangee 好的，大概多久可以完成？

**Comment by qinglangee** [comment]
最多明天吧

**Comment by networm** [comment]
@qinglangee 好的，那截止日期就定为 2015.06.24 了。

**Comment by zwpaper** [comment]
@networm 我认领 10-git-internals transfer-protocols，最晚明天晚上发 PR

**Comment by networm** [comment]
@zwpaper 好的，已记录。

**Comment by networm** [comment]
06-github 5-scripting
10-git-internals maintenance

这两章还无人认领，谁可以翻译一下？

**Comment by xiaket** [comment]
@networm 06-github 5-scripting 我认领吧, 周一前完成~

**Comment by leshiv** [comment]
@networm 可以的话认领 10-git-internals maintenance 周一前

**Comment by networm** [comment]
@xiaket 不用了，我已经翻译完这个了。
@leshiv 不用了，我正在翻译这个。

你们可以看下上面的进度，有状态变化的话都会显示在上面。

**Comment by networm** [comment]
@leshiv 10-git-internals maintenance 已经翻译完了。

**Comment by leshiv** [comment]
@networm ok

**Comment by networm** [comment]
到现在为止所有非我翻译的章节都已发送 PR。我翻译的内容正在按照计划进入 v2 阶段。

**Comment by buginux** [comment]
所以说现在所有的章节都被认领完了是么？好忧伤，之前不知道怎么参与翻译，刚进来，发现已经晚了。

**Comment by networm** [comment]
@buginux 现在主要的工作是审校，欢迎到 Pull Request 中对翻译的文章审校。

**Comment by networm** [comment]
审校协作计划 · Issue #160 · progit/progit2-zh
https://github.com/progit/progit2-zh/issues/160[]

欢迎大家继续参与审校协作计划！

**Comment by networm** [comment]
进度显示与 #160 重复，关闭此 Issue。
