### ISSUE TITLE
申请作为协作者

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#69]
到现在为止我已初步翻译完成 18 篇文章，还会按照计划继续下去。我的翻译进度 [翻译 version 1 进度 · Issue #55 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/55) 里面有整张表，所有粗体的是我初步翻译的。
我之前已经在 [翻译计划 · Issue #54 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/54) 说明了我的计划，不过有一点我忘说了，我会一直全职工作来翻译，直到翻译彻底完成。所以你们会有我翻译速度度的感觉，因为我一白天都在翻译，有时晚上也在翻译。。。
所以最近一直全天挂在 Github 上，时间充裕，可以辅助管理项目翻译。

之前我也曾买过一本《Git 权威指南》，也在网上看过很多教程，但是我认为本书是新手入门最好的书籍，没有之一。
我认为翻译人员流程有些混乱，原有的章节认领也没有更新，我认为这不利于尽快翻译完本书。

想要做以下事情：
. 更新原有章节认领 Issue，去除未参加的人员
. 统一所有章节认领到同一个 Issue
. 认领章节时增加截止日期，别人在截止日期后可以重新认领
. 加快审核 Pull Request 的速度，尽量不干扰其他人翻译

**Comment by networm** [comment]
@devbean @tonghuix @archermind @oldsharp @morstar @Geno1024 @leo108

**Comment by oldsharp** [comment]
> 最近一直全天挂在 Github 上

Hence you are a **FULL TIME CONTRIBUTOR** of the project... That's **GREAT**（俗称 碉堡了）...
The project needs full time players like you！

没话说，我举双手支持你 ;-)

（ @networm  哥们，你这让我们这些 overtime dogs，情何以堪…我最近因为处在两个项目的间隙期，所以才有时间做一些 contribution…羡慕嫉妒恨…）

**Comment by tonghuix** [comment]
超支持你！

**Comment by Geno1024** [comment]
高考完了虽然能整天泡 Github 但是感觉自己还没有能力管理这么大的 project 所以我表示支持只不过别动我还在翻译的 B 章就行啦。

**Comment by devbean** [comment]
等待原作者回复...

**Comment by archermind** [comment]
@networm 支持，加快推进我们的项目

**Comment by networm** [comment]
@oldsharp 我只不过是最近有时间，正好做点有意义的事情
@tonghuix 谢谢支持
@Geno1024 你其实可以多翻译一些的，可以去 [正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68) 申请新的任务哦
@devbean 嗯，我给原作者发邮件提 Issue @他 都没回我啊。。。
@archermind 我会努力的

**Comment by devbean** [comment]
可能需要一段时间吧，他也不是专职的，仅在业余时间才会看到吧，特别是现在全书已经截稿的情况下

**Comment by networm** [comment]
@devbean 了解

**Comment by networm** [comment]
@devbean @tonghuix @archermind @oldsharp @morstar @Geno1024 @leo108

@tonghuix 和我都已经成为协作者了，接下来会继续努力的！

**Comment by oldsharp** [comment]
Congrats!

**Comment by networm** [comment]
@oldsharp 谢谢！

**Comment by morstar** [comment]
@networm @tonghuix
Congrats!

**Comment by networm** [comment]
@morstar 谢谢！

**Comment by tonghuix** [comment]
感谢各位支持！
