### ISSUE TITLE
章节翻译认领

### ISSUE THREAD

**Issue by devbean** [progit/progit2-zh#7]
翻译人员可以在这里追加自己想翻译的章节，以便别人选择。

01-introduction
  1-introduction -- @Lax
  sections/about-version-control -- @Lax
  sections/basics -- @Lax
  sections/command-line -- @shuaishuai
  sections/first-time-setup -- @Lax
  sections/help -- @Lax
  sections/history -- @Lax
  sections/installing -- @Lax

02-git-basics
  1-git-basics -- @alamier
  sections/aliases -- @alamier / @tonghuix
  sections/getting-a-repository -- @alamier
  sections/recording-changes -- @alamier
  sections/remotes -- @alamier / @tonghuix
  sections/tagging -- @alamier / @tonghuix
  sections/undoing -- @alamier / @tonghuix
  sections/viewing-history -- @alamier / @tonghuix

03-git-branching
  1-git-branching -- @Jun995
  sections/basic-branching-and-merging -- @Jun995
  sections/branch-management -- @Jun995
  sections/nutshell -- @Jun995
  sections/rebasing -- @shuaishuai
  sections/remote-branches -- @Jun995
  sections/workflows -- @Jun995

04-git-server
  1-git-server
  sections/generating-ssh-key
  sections/git-daemon
  sections/git-on-a-server
  sections/gitlab
  sections/gitweb
  sections/hosted
  sections/protocols
  sections/setting-up-server
  sections/smart-http

05-distributed-git
  1-distributed-git -- @Qunero
  sections/contributing -- @Qunero
  sections/distributed-workflows -- @Qunero
  sections/maintaining -- @Qunero

06-github
  1-github -- @devbean
  sections/1-setting-up-account -- @devbean
  sections/2-contributing -- @devbean
  sections/3-maintaining -- @devbean
  sections/4-managing-organization -- @devbean
  sections/5-scripting -- @devbean

07-git-tools
  1-git-tools -- @leo108
  sections/advanced-merging -- @leo108
  sections/bundling -- @leo108
  sections/credentials -- @leo108
  sections/debugging -- @leo108
  sections/interactive-staging -- @leo108
  sections/notes -- @leo108
  sections/replace -- @leo108
  sections/rerere -- @leo108
  sections/reset -- @leo108
  sections/revision-selection -- @leo108
  sections/rewriting-history -- @leo108
  sections/searching -- @leo108
  sections/signing -- @leo108
  sections/stashing-cleaning -- @leo108
  sections/submodules -- @leo108
  sections/subtree-merges -- @leo108

08-customizing-git -- @datawolf
  1-customizing-git -- @datawolf
  sections/attributes -- @datawolf
  sections/config -- @datawolf
  sections/hooks -- @datawolf
  sections/policy -- @datawolf

09-git-and-other-scms
  1-git-and-other-scms
  sections/client-hg
  sections/client-p4
  sections/client-svn
  sections/client-tfs
  sections/import-custom
  sections/import-hg
  sections/import-p4
  sections/import-svn
  sections/import-tfs

10-git-internals
  1-git-internals
  sections/environment
  sections/maintenance
  sections/objects
  sections/packfiles
  sections/plumbing-porcelain
  sections/refs
  sections/refspec
  sections/transfer-protocols

A-git-in-other-environments @shuaishuai
  1-git-other-environments
  sections/bash
  sections/eclipse
  sections/guis
  sections/powershell
  sections/visualstudio
  sections/zsh

B-embedding-git @Geno1024
  1-embedding-git
  sections/command-line
  sections/jgit
  sections/libgit2

C-git-commands @kuuyee
  1-git-commands @kuuyee

**Comment by kuuyee** [comment]
C-git-commands 我来翻译这一章，@kuuyee 特此声明！

**Comment by shuaishuai** [comment]
申请翻译 A1.1 Git in Other Environments - Graphical Interfaces

**Comment by Geno1024** [comment]
我是一名高三学生，想认领B-embedding-git这一章，利用课余时间翻译，顺便提高自己的英语水平，同时体验一下作为一个contributor的成就感。。。
顺便，没有deadline吧？我看好像都得翻译很久很久的样子的感觉。。。

**Comment by shuaishuai** [comment]
@Geno1024 少年好兴致，要不要尝试一下第6章，应该很有帮助

**Comment by Geno1024** [comment]
@shuaishuai 第六章不是已经有人认领了吗。。。

**Comment by shuaishuai** [comment]
@Geno1024 咦，没注意到，我一直以为这章没人要管

**Comment by Geno1024** [comment]
@shuaishuai 其实还有一个原因就是B章看起来内容比较少。。。

**Comment by hbrls** [comment]
@devbean 我翻的 A 1.1 还包括了 sections/guis

**Comment by Jun995** [comment]
对不起啊，各位，我这两个月要实习，还要做毕业设计。。实在太忙了，今天都在加班T_T。。所以，我暂时不能抽时间翻译了，谁要翻译第三章的话请拿去。

**Comment by TenphyX** [comment]
我尝试翻译第四章04-git-server吧。

**Comment by oldsharp** [comment]
认领 第十章 Git Internals

**Comment by JiajunW** [comment]
@Jun995 我这段时间想翻译下第三章

**Comment by Jun995** [comment]
@JiajunW 你翻吧

**Comment by VirgilMing** [comment]
1.5 起步 - 安装 - Git 没翻译。我先认领了。

**Comment by archermind** [comment]
@alamier  buddy，第二章你进度怎么样？建议我从第三章开始继续你的工作吗？ Thanks

**Comment by morstar** [comment]
认领第九章 git-and-other-scms

**Comment by morstar** [comment]
那目前还有可认领的章节么？附录A？附录B？

**Comment by networm** [comment]
@morstar 我觉得你可以先翻译附录A和附录B，我现在正在翻译第九章 client-p4；我的进度：[翻译 version 1 进度 · Issue #55 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/55)

**Comment by Geno1024** [comment]
@networm @morstar 我在翻译B章，只是因为一些语序以及比较好的表述之类的问题还在润色所以还没push。

**Comment by morstar** [comment]
好的 我也将翻译进度加进 issue #55

**Comment by networm** [comment]
@devbean 这个章节认领 Issue 里的人员信息可能过时了，我在维护另一个章节认领的 [正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68)，为了不重复，关闭这个 Issue 可以吗？

**Comment by networm** [comment]
@devbean 谢谢！

**Comment by JiajunW** [comment]
@networm 建议按照章节开 issue，翻译完一个章节就关闭 issue。这样也不至于太多进度认领的交杂在一个 issue 里面显得太乱。

**Comment by networm** [comment]
@JiajunW 我个人觉得这样比较方便管理与查看，在一个 Issue 内大家可以知道总体的进度，而且认领新任务统一到一处有助于减少冲突、快速处理。

**Comment by JiajunW** [comment]
@networm 我的意思是，有一个总的用来 track 进度，每个单独的章节用一个 issue，然后谁翻译就 assign 给谁，这样不会混乱掉线索，耗时太久也可以方便 assign 给其他人，而且也能在 github 中直接看到 assign 给自己的 issue。

嘛，不过现在的主要问题是很多认领的任务就没后续直接烂尾了……

**Comment by networm** [comment]
@JiajunW 如果每个人都 assign 的话，那有多少人就得有多少个 Issue，那就太乱了。
混乱线索的问题，我觉得不是问题，每个人只翻译一两个小节，很好追踪。
耗时太久的问题，现在每一个小节指定给一个人时都只有 3 天的截止时间，如果 3 天未完成就换其他人了。
