### ISSUE TITLE
编译的时候出现了问题，bundle install failed...，懂ruby的同学请帮忙confirm一下

### ISSUE THREAD

**Issue by archermind** [progit/progit2-zh#70]
本来是打算看 issue #48 的，结果在使用bundle的时候就出现了如下错误，但是都找到了解决方法，现在请大家一起帮忙看下，我完全不懂 ruby之类的东西，以下方法全部google得来。

. ruby官方的源貌似不太问题，执行 `bundle install` 的时候，常常报网络异常。

==> 参考解决方法 http://ruby.taobao.org/[] 将官方源换成 taobao提供的镜像

. `kindlegen` 这个工具在 `bundle install` 会报错，progit 其他repo也遇到类似问题

==> 类似问题 https://github.com/tdtds/kindlegen/issues/12 
==> 参考解决方案 https://github.com/progit/progit2/pull/215

**Comment by archermind** [comment]
@tonghuix 这个你的 issue #48 background 相同，请帮忙看下，谢谢

**Comment by archermind** [comment]
建议，

1, 修改`Gemfile` 文件，将官方源改成淘宝源。
2, update `kindlegen` 到 `2.9.4` 版本

**Comment by Lax** [comment]
淘宝源的更改不建议合并，因为这假设了所有人都在国内。
bundler install 只是第一次 setup 环境时需要执行，如果报错可以只在本地更改淘宝源先把依赖包装上，以后就可以使用了，没必要合并进来。

**Comment by devbean** [comment]
建议只修改自己的文件，而不是直接提交修改过的文件；否则官方也有可能编译出错。

**Comment by tonghuix** [comment]
我是全程翻墙下载和安装的。。。

**Comment by archermind** [comment]
OK，那我们可以加一个说明的note
