### ISSUE TITLE
认领:) 第4章 git-on-server 和 gitlab

### ISSUE THREAD

**Issue by neo1218** [progit/progit2-zh#78]
认领第4章git-on-server 和 gitlab !

**Comment by archermind** [comment]
@neo1218 标题写清楚，认领那个章节。这样大家不用点进来就知道了

**Comment by networm** [comment]
@neo1218 关闭所有认领 Issue，统一到 [正式版 翻译进度 · Issue #68 · progit/progit2-zh](https://github.com/progit/progit2-zh/issues/68)
