### ISSUE TITLE
第4章的 1-git-server 中“伺服器”应该是“服务器”

### ISSUE THREAD

**Issue by spacewander** [progit/progit2-zh#79]
伺服器是港台的说法，大陆的说法是服务器。
既然是简体中文版，还是按大陆的版本来吧。

**Comment by archermind** [comment]
是的你说的对，应该翻译成 `服务器` ，虽然是一个小问题，但是还是请你提一个PR吧。Thanks

**Comment by networm** [comment]
@spacewander 提完一个 Pull Request 后就可以关闭这个 Issue 了。

**Comment by networm** [comment]
@spacewander @archermind [change all "伺服器" to "服务器" by networm · Pull Request #84 · progit/progit2-zh](https://github.com/progit/progit2-zh/pull/84) 我已经提交并合并完毕了。
