### ISSUE TITLE
contributing 应该如何翻译

### ISSUE THREAD

**Issue by sanddudu** [progit/progit2-zh#81]
引用 @networm 的话：
但是 contributing 这个不一定要翻译为贡献代码，因为 Github 不光是可以存放代码，其他领域的模型、图片、声音什么的都有很多存放在这儿，所以我的建议是单独提一个 Issue，来讨论一下这个问题。我个人觉得叫“贡献”就很好。

希望大家积极发表意见

**Comment by neo1218** [comment]
赞同“贡献”

**Comment by sanddudu** [comment]
@networm 另外，contributing 虽然可以翻译作 “贡献”，但是其他形式不行
举个例子，“contribute to an existing project” 应该怎么翻译，目前暂时翻译成 “向一个项目做出贡献”

**Comment by networm** [comment]
@sanddudu 英语翻译成中文的话需要根据语言习惯、语法、常用用语等做一些转换。

**Comment by oldsharp** [comment]
@sanddudu 最好能例举一个原文的位置，这样可以联系上下文来看一下，应该怎么翻译。

**Comment by sanddudu** [comment]
繁体中文版本翻译成 “参与”
似乎避开了这个问题

**Comment by networm** [comment]
@sanddudu 繁体中文版的这个翻译好像丢失了这个词的意思了！

**Comment by sanddudu** [comment]
@networm 并没有完全丢失，这种翻译比较符合中文语法
但是将单词本身和翻译割裂开了，可能需要添加更多注解帮助读者理解，也不利于对照英文版阅读的读者

**Comment by networm** [comment]
@sanddudu 是的，但是如果用参与的话作者就会写“join”了。

**Comment by sanddudu** [comment]
@networm 其实是因为 Github 比较倾向于使用 Contribute
比如项目中的 Contributor
但是和中文的语法有比较大的冲突

**Comment by sanddudu** [comment]
@networm 我个人认为翻译成 “参与” 其实更多的是一种妥协

**Comment by networm** [comment]
@sanddudu 我觉得很多词刚开始用的时候都觉得冲突，习惯就好了，比如卡拉OK，可口可乐之类的。

**Comment by tonghuix** [comment]
遵从翻译传统吧，“贡献”还是比较好的。或者根据上下文临时调整一下也不错。

**Comment by networm** [comment]
最终的结论是 contributing -> 贡献。
