### ISSUE TITLE
翻译参与方式

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#87]
1. 访问 [正式版 翻译进度](https://github.com/progit/progit2-zh/issues/68) 留言来认领章节，认领的每一个章节的截止时间是 3 天，所以最好先认领一个章节，翻译完成后再认领其他章节。
2. Fork progit/progit2-zh，然后 clone 到本地。如果 clone 到本地的速度实在是过慢，那么访问链接: http://pan.baidu.com/s/1sj3GTL7 密码: zz8q 下载我的版本，并且修改 .git/config 文件，如果不会修改的话再次 clone，然后将克隆目录内的 .git/config 文件拷出来覆盖这个文件。
3. 新建对应章节的分支，在上面翻译并提交、推送。
4. 到 Github 上发送 Pull Request，其他人审核、提出修改意见。
5. 根据修改意见再次提交、推送到同一个分支，这时候不需要删除仓库或分支，其他人审核通过后合并入主干。

大家的主仓库尽量让 master 分支追踪官方的源，这样可以保持最新、减少冲突，设置方法如下：

```console
git checkout master
git remote add upstream git@github.com:progit/progit2-zh.git
git fetch upstream
git branch --set-upstream-to=upstream/master master
git pull
```

这样之后每次就可以直接拉取了，要翻译新章节前进入 `master` 分支拉取一下，然后再新建分支：
```console
git checkout master
git pull
git checkout -b chapter
```

大家尽量做到实时预览，可以用浏览器插件或者特别的编辑器：
[Editing AsciiDoc with Live Preview | Asciidoctor](http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/)

**Comment by tonghuix** [comment]
补充一句，若clone太慢，可以尝试加入下列到hosts文件里
````
#GitHub START
192.30.252.131	github.com
192.30.252.131	www.github.com
192.30.252.144	nodeload.github.com
103.245.222.133	raw.github.com
103.245.222.133	documentcloud.github.com
103.245.222.133	pages.github.com
103.245.222.184	github.global.ssl.fastly.net
#GitHub END
````

**Comment by sanddudu** [comment]
在 Github Windows 附带的 Git Shell 执行 `git branch --set-upstream-to=upstream/master master` 会显示：
```
error: the requested upstream branch 'upstream/master' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
```
`git remote add upstream git@github.com:progit/progit2-zh.git` 已经执行成功，再次添加会提示：
`fatal: remote upstream already exists.`

**Comment by networm** [comment]
@sanddudu 抱歉，当时忘加一句 git fetch upstream，在 git remote add 后执行这句就可以。

**Comment by tonghuix** [comment]
git fetch不如直接运行git pull upstream更好，因为git pull会自动merge

**Comment by networm** [comment]
@tonghuix 后面还有一次 git pull

**Comment by hbrls** [comment]
用 rebase 吧，时间线会好很多

**Comment by networm** [comment]
@hbrls 我的意思是更新 `master` 分支的时候这样做，`master` 分支上本身不允许存在任何其他提交的，所以这样做是没问题的。

**Comment by robinwen** [comment]
我现在的确是没有大块的时间去做翻译，或许可以参加后期的校订工作。

**Comment by networm** [comment]
@robinwen 马上就可以校订，现在已经有 20 个 Pull Request 等待校订。

**Comment by networm** [comment]
翻译已经完毕，进入审校阶段，就不需要翻译参与方式了。
