### ISSUE TITLE
英文双引号是否需要替换为中文双引号

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#93]
键盘中并不能直接输入英文的双引号，而且那的确是 `` 与 ''，在 AsciiDoc 中转义显示为英文的双引号。

> “Double quoted text”
>    Phrases enclosed with ``two grave accents to the left and two acute accents to the right'' are rendered in quotation marks.

[AsciiDoc User Guide - 10.1. Quoted Text](http://www.methods.co.nz/asciidoc/asciidoc.css-embedded.html#X51)

具体一一个例子是：[Update README.asc by wogong · Pull Request #91 · progit/progit2-zh](https://github.com/progit/progit2-zh/pull/91#discussion_r32524496)

英文的双引号在中文的情况下显示没有留白，看起来并不太好看，见 [Git - Git 基础](http://git-scm.com/book/zh/v2/%E8%B5%B7%E6%AD%A5-Git-%E5%9F%BA%E7%A1%80) 最下方的“索引”

大家可以讨论一下这个双引号到底要不要改？

**Comment by tonghuix** [comment]
应该是要替换的，不替换会很难看。

**Comment by devbean** [comment]
个人意见是替换。所有标点都应该换成全角，除了句号有待商议（因为某些科技文献是使用的半角句号），不过为统一起见，还是用全角句号比较合适。

**Comment by networm** [comment]
@tonghuix @devbean 我认为也是需要替换，但我认为这个工作可以留到全部翻译完成后统一处理，大家觉得这样好不好？

**Comment by archermind** [comment]
@networm 可以，小问题可以留到后面一并解决

**Comment by archermind** [comment]
对于一下不伤大雅的问题，我们都可以留到最后解决，这样避免一下 *小提交* 穿插在重要提交之间，看起来很不和谐。

**Comment by networm** [comment]
@archermind 是的，而且即使改了一部分，后面提交的人没注意，还是会提交上来错误的内容。

**Comment by tonghuix** [comment]
呵呵不要担心小提交，有 `git rebase -i `这种神器呢。

**Comment by networm** [comment]
@tonghuix 主仓库不能变基的，很多人都基于这个翻译呢，如果你变基了，Pull Request 会将其再带回来的！

**Comment by archermind** [comment]
@tonghuix 主仓库不能随便`rebase`，很多人fork你了，如果你把原来分支中的提交对象发布出去，并且其他人更新下载后在其基础上开展工作，而稍后你又用 git rebase 抛弃这些提交对象，把新的重演后的提交对象发布出去的话，你的合作者就不得不重新合并他们的工作，这样当你再次从他们那里获取内容时，提交历史就会变得一团糟。

http://git-scm.com/book/zh/v1/Git-%E5%88%86%E6%94%AF-%E5%88%86%E6%94%AF%E7%9A%84%E8%A1%8D%E5%90%88#衍合的风险

**Comment by tonghuix** [comment]
是这样的，git rebase -i 的交互化可以使用 squash 操作，保证使用 commit 但将其合并到前一次提交，这样这次小提交就没有了。我在提交pull request之前会这样操作以减少不必要的小提交。

不过@networm @archermind 所言我确实没考虑到，因为主仓已经被很多人fork了。

**Comment by networm** [comment]
@devbean @tonghuix @archermind 那这个问题先关闭了，等待全部翻译完成时再处理。

**Comment by zwpaper** [comment]
在 #104 中，我还发现中文引号使用了 「」
我认为有必须及时加入标准，否则在翻译完成后，会变得比较复杂。

**Comment by Geno1024** [comment]
@zwpaper 如果我没记错的话，这个符号在大陆简体是不规范的。

**Comment by networm** [comment]
@zwpaper 这个统一用普通的双引号。
