### ISSUE TITLE
04 protocols单词`Smart` `Dumb`翻译方法商讨

### ISSUE THREAD

**Issue by wych42** [progit/progit2-zh#95]
各位：

在04 章 protocols 一节里，有这么一段：
>The newer version is often referred to as the “Smart” HTTP protocol and the older way as “Dumb” HTTP. We’ll cover the newer “smart” HTTP protocol first.

其中的Smart和Dump没有想到合适的译法，请大家一起商讨下。

**Comment by tonghuix** [comment]
我认为 Smart 译为“智能”是可以的。“Dumb” 可以译为"失聪"？

其实我也不太确定，因为看了原文，也没搞懂。https://github.com/progit/progit2-zh/blob/master/book%2F04-git-server%2Fsections%2Fprotocols.asc

**Comment by networm** [comment]
@wych42 ProGit 第一版中 Dumb HTTP 翻译为哑协议了，参见：[Git - 传输协议](https://git-scm.com/book/zh/v1/Git-%E5%86%85%E9%83%A8%E5%8E%9F%E7%90%86-%E4%BC%A0%E8%BE%93%E5%8D%8F%E8%AE%AE)，建议先将本章阅读完再翻译。

**Comment by wych42** [comment]
@networm  sorry 昨天看的时候没有看到相关的内容，似乎在github里的版本翻译的是「傻瓜」协议

**Comment by networm** [comment]
@wych42 我觉得“哑”更能体现出这个协议的特点，即只有客户端向服务器请求，没有服务器向客户端请求。

**Comment by wych42** [comment]
@networm  那么相对应的smart翻译为智能就不妥了，因为智能与哑并不对应。

**Comment by networm** [comment]
@wych42 我觉得这两个词并不一定要完全是对应的。@devbean @archermind 你们觉得该如何翻译？

**Comment by wych42** [comment]
@networm  暂时也没有更好的方案，我先按照智能和哑这个方法写下去了。在翻译时留下原文。

**Comment by networm** [comment]
@wych42 好的，那这个问题可以留在这儿一段时间，让大家共同讨论一下。

**Comment by archermind** [comment]
怎么翻译都可以，大家统一下就可以了，但是我的意见是，对于这类不*太*好翻译的词我们可以在后面加个括号把其英文给填上。

`哑协议（Dump HTTP）`

**Comment by networm** [comment]
@archermind 强烈同意！

**Comment by WispZhan** [comment]
个人感觉，想这种捉摸不定的翻译问题。你暂定一个翻译方式，然后把原词或原句直接附在后面。
就本问题而言，建议 采用 原文的格式 用引号把翻译过后的文字引用起来。这里已经不是单词本身的意思了，原作者在这里也是采取的一个引用的手法，引申了其他含义。这里2个词成对出现，就直接暂时翻译成意义相反的词语，然后应用起来。充分使用引号的含义就行了。

**Comment by oldsharp** [comment]
![capture](https://cloud.githubusercontent.com/assets/980500/8269777/0c122392-17ec-11e5-9f5f-977ee0dd166c.PNG)

“哑传输协议”、“智能 HTTP 协议”。
图片截自《Git 权威指南》。
多一个参考。

**Comment by zwpaper** [comment]
加一个总结提示，

《Git 权威指南》和本书第一版中，使用了“哑传输协议”和“智能 HTTP 协议”。

在第四章中暂时已翻译为“哑传输协议”和“智能 HTTP 协议”，我即将翻译10-git-internals transfer-protocols，也将使用“哑传输协议”和“智能 HTTP 协议”。

**Comment by oldsharp** [comment]
@zwpaper Good, 可以考虑 update TRANSLATION_NOTES.asc，把这两条加进去，然后提一个 PR。

**Comment by zwpaper** [comment]
@oldsharp 好提议，一会就做。

**Comment by zwpaper** [comment]
@wych42 这个 issue 已经暂时解决，是否考虑关闭？

**Comment by networm** [comment]
@wych42 问题已解决，关闭。
