### ISSUE TITLE
附录 B 章俩单词求探讨翻译。

### ISSUE THREAD

**Issue by Geno1024** [progit/progit2-zh#96]
在附录 B 章中的 Libgit2 篇大量出现 binding 一词，我暂且翻译为“绑定”，不过总感觉还有更好的，求支招。
文末还出现了一次 bundle 大概意思应该差不多，但是为了区分它们，我将后者翻译为“附带”，也是想到了“adt-bundled”这个词。不过总是不知道为什么感觉怪怪的。。。
顺带，过十几个小时继续提 Pull Request ，包括 Libgit2 这一篇以及 JGit 的 一点 typo 和一些修改。
话说真的有个感觉写了下去就很难修改甚至想到的那一刻就没法再修改了。。。

**Comment by tonghuix** [comment]
翻译有个技巧， 不要一次成型，一定多多多斟酌。不用非常谨慎小心，但至少三思遣词再落笔。别图快和效率，否则写出来往往不是人话。

binding一词译为”绑定“在大多数情况下是可以的。因为看到B章里有很多是关于Libgit2与编程语言绑定的内容，咱们平时也是说成”与XXX编程语言绑定”的。

bundled 原意是捆绑，后来引申为捆绑销售（在一个Package里）。而B章里最后那句的 bundle 与此再引申的，我认为“附带”是可以的，或者“随附”、“附加的”、“在一起的”都可以。

**Comment by networm** [comment]
@Geno1024 @tonghuix 我同意 @tonghuix 的看法，Libgit2 本来就是一个语言绑定的库，binding 翻译成绑定并无不妥；bundled 在这节中翻译为附带很贴切真实的意思。

**Comment by Geno1024** [comment]
@tonghuix @networm 谢谢。我还很嫩，没听说过”与XXX编程语言绑定”的说法，😄。
然后我对于翻译过程有些不同的看法。探讨一下？
我们英语老师说，我们也这样觉得，就是在做一篇阅读的时候最好一次性做完，中途不要中断，因为或多或少有一些东西总是需要按照上下文理解来得知它要表述的真正意思，如果你过一段时间再来继续做的话，重新读的时候会因为前面貌似都读过而直接扫描过，这样就可能误解了那类词而造成误解。
当然不能否认有些读两三次读不出意思，需要待一会理清一下思路再能真正理解的句子。这一次就有句子我理解并推了差不多半个小时的，都有。
因为B章的日文版已经翻译好了，所以我在翻译的时候想借助日文版稍微帮助我一下理解某句话的意思，但是日文版的真心不想吐槽了。。。

**Comment by networm** [comment]
@Geno1024 我觉得 ProGit 只是一本普通的技术书，并没有特别的用语；如果你阅读过很多其他计算机方面的中英文资料，你就会了解到一些计算机用语；除此之外，就是如果你阅读过 ProGit 第一版 中文版 会有很大帮助。

**Comment by networm** [comment]
最终结论：binding -> “绑定”。
