### ISSUE TITLE
repository 应该翻译成什么？

### ISSUE THREAD

**Issue by networm** [progit/progit2-zh#98]
现在在 TRANSLATION_NOTES 中“repository”被翻译为“版本库”。
我感觉翻译为“仓库”更好一些，更简洁一些；另外《ProGit》第一版也是使用的“仓库”。

大家有什么看法？

**Comment by tonghuix** [comment]
应以现在 Git 官方中文翻译为准。https://github.com/git/git/blob/master/po/zh_CN.po

所以还是翻译为“版本库”，虽然我本人强烈不喜欢这个翻译。。。。2333

**Comment by sanddudu** [comment]
其实 "仓库" 更加形象，"版本库" 容易理解成储存版本的数据库
我平常使用的时候经常不翻译，直接使用缩写 repo

**Comment by neo1218** [comment]
我们讨论的是 Git  下的 repository ，因此不能仅仅翻译为仓库，版本库更能体现 Git 在其中发挥的作用

**Comment by networm** [comment]
@tonghuix 现在讨论的是应该用哪个，而不是遵循哪个。如果确定“仓库”是较好的翻译，那么官方库里的翻译也是需要改的。

**Comment by tonghuix** [comment]
我更倾向于与 Git 官方保持一致。现在仔细想“仓库”一词确实也不太合适

**Comment by networm** [comment]
@tonghuix 这个 Issue 可以在这儿多放几天，让大家一起看看。

**Comment by wych42** [comment]
仓库不太合适，软件包的repo也叫做仓库，这个词更适合统称，如果放在git上，叫版本库应该更能体现出git的作用来。

**Comment by WispZhan** [comment]
这个总要以一个为准的，不管是以什么为准，都应该在 index 里定义出来，而且尽早。

**Comment by networm** [comment]
确定翻译为“仓库”了。

**Comment by englianhu** [comment]
> 确定翻译为“仓库”了。

`仓库`易记，虽然感觉怪怪的，仓库是存货的货仓，而代码是文字，**GitHub是记载所有代码与文字之库与时间（尚未包括地点）**，叫`文库`较贴切吧？（なに？！）造访者来客不就是苹果总裁的`库客`吗？@@"

`版本库`类似记载`应用版本进化史`的`史记`（公元前）般... 个人翻译成`代码库`或`应用库`... 明白意思即可吧？

**Comment by networm** [comment]
翻译成“仓库”已经是惯例了，现在连 GitHub 官方文档也是这么翻译的：* [仓库 - GitHub Docs](https://docs.github.com/cn/repositories)
仓库里放的并不全是代码，会有二进制的其他文件，可能版本库更合适一些。但是版本库字数比仓库多一个，也不够简洁。至于你提到的其他翻译，感觉更不靠谱了。

**Comment by englianhu** [comment]
👌🏻，然后以下🔗也解释得很专业。
http://www.cilin.org/jyc/b_2372.html
