### ISSUE TITLE
Github Organization 中团队的 @ 功能部分翻译求助

### ISSUE THREAD

**Issue by zwpaper** [progit/progit2-zh#99]
Github organization 中团队的 @ 功能，在所有成员都订阅了这个话题之后会怎么样呢？
也就是文中的后半句，

> Additionally, team `@mentions` (such as `@acmecorp/frontend`) work much the same as they do with individual users, except that *all* members of the team are then subscribed to the thread.

中的 

> except that *all* members of the team are then subscribed to the thread.

应该怎么翻译比较好呢？

补充一下，这是 06-github-4-managing-organization 部分。

**Comment by networm** [comment]
@zwpaper 你这种自己找到答案了可以写在回复里，我刚过来看半天没弄明白怎么回事。

**Comment by zwpaper** [comment]
@networm Sorry，以后会注意。

**Comment by networm** [comment]
@zwpaper 没事，这东西是个历史，会方便其他人来查看发生了什么，特别是协作者会收到项目的所有动态。
